// Deutsch. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let de: [String: String] = [
        "about": "Über TheeJ",
        "add_knob": "Regler hinzufügen",
        "add_profile": "Profil hinzufügen",
        "applications_only": "TheeJ aktualisiert sich nur, wenn es aus dem Ordner „Programme“ läuft.",
        "audio_text": "Um die Lautstärke einer App einzustellen, gibt TheeJ den Ton dieser App in der Lautstärke des Reglers wieder, was macOS als Aufnahme wertet. Erlaube TheeJ unter „Bildschirm- & Systemaudioaufnahme“ in „Datenschutz & Sicherheit“, beende TheeJ dann und öffne es erneut.",
        "audio_title": "TheeJ kann App-Lautstärken noch nicht einstellen",
        "auto": "Automatisch suchen",
        "available": "TheeJ {version} ist verfügbar",
        "by": "Von",
        "cal.all_found": "Alle Regler gefunden",
        "cal.all_found_text": "Dein Board sendet {n} Werte, und jeder hat jetzt seinen Regler, das sind also alle. Klicke auf „Fertig“, um festzulegen, was sie tun.",
        "cal.finish_later": "„Fertig“ hört hier auf und lässt ihn für später.",
        "cal.hold": "Deine Regler bewirken nichts, bis du fertig bist.",
        "cal.move": "Bewege Regler {letter} von Anschlag zu Anschlag.",
        "cal.move_first": "Bewege Regler {letter} von Anschlag zu Anschlag, damit TheeJ erkennt, welcher Regler welcher ist. Danach wird jeder Regler {n} Sekunden lang gedreht, was einen springenden Regler wieder sauber macht.",
        "cal.no_knob": "Wenn du keinen Regler {letter} hast, klicke auf „Fertig“.",
        "cal.paused": "Pausiert. {left}. Drehe Regler {letter} weiter.",
        "cal.skip_keeps": "Er ist schon eingerichtet, „Überspringen“ lässt ihn also, wie er ist.",
        "cal.turn": "Gefunden. Drehe ihn jetzt {n} Sekunden lang hin und her, von Anschlag zu Anschlag. Die Zeit läuft nur, solange er sich dreht. Überspringe das, wenn er nicht gereinigt werden muss.",
        "cal.waiting_board": "Warte auf die Verbindung zum Board",
        "cal.waiting_knob": "Warte darauf, dass sich Regler {letter} bewegt",
        "cal.wrong": "Das ist Regler {wrong}. Bewege stattdessen Regler {letter}.",
        "calibrate": "Kalibrieren",
        "calibration_title": "TheeJ-Kalibrierung",
        "cancel": "Abbrechen",
        "check": "Nach Updates suchen…",
        "check_connection": "Prüfe deine Verbindung und versuche es erneut.",
        "check_failed": "Suche nach Updates fehlgeschlagen",
        "checking_signature": "Signatur wird geprüft…",
        "choose": "Auswählen",
        "choose_language": "Wähle deine Sprache",
        "click_to_update": "Du hast {version}. Zum Aktualisieren klicken.",
        "close": "Schließen",
        "connected": "Verbunden: {port}",
        "continue": "Fortfahren",
        "daily": "Täglich",
        "default_profile": "Standard",
        "dock": "Im Dock behalten",
        "dock_restart": "Dock neu starten",
        "dock_restart_text": "Dafür muss macOS das Dock neu starten. Bildschirm und Menüleiste flackern dabei kurz.",
        "dock_restart_title": "Dock neu starten?",
        "download": "Download",
        "download_failed": "Der Download ist fehlgeschlagen.",
        "downloading": "Version {version} wird geladen…",
        "finish": "Fertig",
        "hide_icon": "Symbol in der Menüleiste ausblenden",
        "hide_icon_note": "Öffne TheeJ erneut, um hierher zurückzukommen.",
        "icon": "Symbol",
        "icon.app": "App-Symbol",
        "icon.dial": "Drehregler",
        "icon.mixer": "Mischpult",
        "inspired_by": "Inspiriert von",
        "install_now": "Version {version} jetzt installieren",
        "installed": "Version {version} ist installiert.",
        "installing": "Wird installiert…",
        "invert": "Regler umkehren",
        "invert_note": "Für andersherum verdrahtete Potis.",
        "job.brightness": "Helligkeit von Display {n}",
        "job.builtin_brightness": "Helligkeit des integrierten Displays",
        "job.builtin_contrast": "Kontrast des integrierten Displays",
        "job.builtin_keyboard": "Beleuchtung der integrierten Tastatur",
        "job.contrast": "Kontrast von Display {n}",
        "job.external_keyboard": "Beleuchtung der externen Tastatur",
        "job.master": "Gesamtlautstärke",
        "job.microphone": "Mikrofonlautstärke",
        "job.night_shift": "Night Shift-Farbtemperatur",
        "job.nothing": "Nichts",
        "job.zoom": "Bildschirmzoom",
        "jobs_note": "Hake pro Regler eine oder mehrere Aufgaben an.",
        "knob": "Regler {letter}",
        "knobs": "Regler",
        "knobs_found.one": "{n} Regler gefunden",
        "knobs_found.other": "{n} Regler gefunden",
        "language": "Sprache",
        "language_note": "Du kannst sie später in den Einstellungen oder im Menü ändern.",
        "later": "Später",
        "login": "Beim Anmelden starten",
        "m1ddc.note": "Für Helligkeit und Kontrast externer Displays",
        "m1ddc.installed": "Installiert",
        "m1ddc.missing": "Nicht installiert",
        "m1ddc.install": "Installieren",
        "m1ddc.refresh": "Aktualisieren",
        "m1ddc.support": "Support:",
        "made_by": "Erstellt von",
        "menu_bar": "Menüleiste",
        "name": "Name",
        "needs_calibration": "Muss kalibriert werden",
        "never": "Nie",
        "newest": "TheeJ {version} ist die neueste verfügbare Version.",
        "next_profile": "Nächstes Profil",
        "no_knobs": "Keine Regler. „Kalibrieren“ findet sie, oder drücke +, um einen hinzuzufügen.",
        "not_connected": "Nicht verbunden",
        "not_signed": "Der Download ist nicht von Zolfer Figueiredo signiert.",
        "now_using": "Du verwendest jetzt TheeJ {version}, die neueste verfügbare Version.",
        "ok": "OK",
        "open_settings": "Systemeinstellungen öffnen",
        "other": "Andere…",
        "press_shortcut": "Kurzbefehl drücken",
        "previous_profile": "Vorheriges Profil",
        "profile": "Profil",
        "profile_list": "Profilliste",
        "profile_n": "Profil {n}",
        "profiles": "Profile",
        "quit": "TheeJ beenden",
        "reconnect": "Neu verbinden",
        "record_shortcut": "Kurzbefehl setzen",
        "remove": "Entfernen",
        "remove_knob": "Letzten Regler entfernen",
        "remove_knob_info": "Seine Aufgaben in allen Profilen werden mit entfernt.",
        "remove_knob_q": "Regler {letter} entfernen?",
        "remove_named": "„{name}“ entfernen?",
        "remove_profile": "Dieses Profil entfernen",
        "remove_profile_info": "Seine Reglerbelegung und sein Kurzbefehl werden mit entfernt.",
        "remove_shortcut": "Kurzbefehl entfernen",
        "remove_this_profile": "Dieses Profil entfernen?",
        "reopen": "Neu öffnen",
        "reopen_failed": "Neu öffnen fehlgeschlagen: {error} Beende die App und öffne sie selbst.",
        "save": "Sichern",
        "seconds_left.one": "Noch {n} Sekunde",
        "seconds_left.other": "Noch {n} Sekunden",
        "section.apps": "Apps",
        "section.brightness": "Helligkeit",
        "section.contrast": "Kontrast",
        "section.keyboard": "Tastaturbeleuchtung",
        "section.night_shift": "Night Shift",
        "section.volume": "Lautstärke",
        "section.zoom": "Zoom",
        "sensitivity": "Empfindlichkeit",
        "settings": "Einstellungen",
        "short.builtin": "Integriert",
        "short.builtin_display": "Integriertes Display",
        "short.external": "Extern",
        "short.screen": "Display {n}",
        "short.warmth": "Farbtemperatur",
        "shortcut": "Kurzbefehl",
        "shortcut_tip": "Verwende ⌘ oder ⌃ mit einer Taste. Die Rückschritttaste löscht ihn, Escape bricht ab.",
        "shortcuts": "Kurzbefehle",
        "show_data": "Daten unten anzeigen",
        "show_name": "Profilnamen anzeigen",
        "skip": "Überspringen",
        "space": "Leertaste",
        "speed": "Geschwindigkeit",
        "speed.fast": "Schnell",
        "speed.medium": "Mittel",
        "speed.slow": "Langsam (empfohlen)",
        "speed.superFast": "Sehr schnell",
        "speed_note": "Wie schnell eine Drehung wirkt.",
        "tab.about": "Info",
        "tab.app": "App-Einstellungen",
        "tab.general": "Allgemein",
        "tool_failed": "{tool} fehlgeschlagen ({code}).",
        "up_to_date": "Du bist auf dem neuesten Stand!",
        "update_available": "Update verfügbar!",
        "update_complete": "Update abgeschlossen!",
        "update_failed": "Update konnte nicht installiert werden",
        "update_now": "Jetzt installieren",
        "update_question": "Du hast {version}. Jetzt aktualisieren?",
        "updating_to": "TheeJ wird auf {version} aktualisiert",
        "version": "Version {version}",
        "website": "Website",
        "weekly": "Wöchentlich",
        "wrong_download": "Der Download ist nicht TheeJ {version}.",
    ]
}
