// Deutsch. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let de: [String: String] = [
        "about": "Über TheeJ",
        "action.close_app": "App schließen",
        "action.go_profile": "Zu {name}",
        "action.group.apps": "Apps",
        "action.group.fkeys": "Funktionstasten",
        "action.group.knobs": "Regler",
        "action.group.media": "Medien",
        "action.group.system": "System",
        "action.keys": "Tastenkürzel drücken",
        "action.lights_off": "Tastenbeleuchtung aus",
        "action.lights_on": "Tastenbeleuchtung an",
        "action.lock": "Mac sperren",
        "action.mute": "{name} stummschalten",
        "action.mute_all": "Ton aus",
        "action.mute_mic": "Mikrofon stumm",
        "action.next_lights": "Nächste Tastenbeleuchtung",
        "action.next_track": "Nächster Titel",
        "action.night_light": "Night Shift an/aus",
        "action.open_app": "App öffnen",
        "action.open_settings": "Einstellungen öffnen",
        "action.open_url": "Website öffnen",
        "action.pause": "Pause",
        "action.play": "Wiedergabe",
        "action.play_pause": "Wiedergabe/Pause",
        "action.previous_lights": "Vorherige Tastenbeleuchtung",
        "action.previous_track": "Vorheriger Titel",
        "action.screens_off": "Bildschirme ausschalten",
        "action.sleep": "Energie sparen",
        "action.volume_down": "Leiser",
        "action.volume_up": "Lauter",
        "add.add": "Hinzufügen",
        "add.name_hint": "Schreibtisch",
        "add.next": "Weiter",
        "add.title": "Board hinzufügen",
        "add.type_note.diy": "Ein Arduino, der seine Regler über USB sendet, wie bei deej.",
        "add.type_note.midi": "Jeder andere MIDI-Controller. Du zeigst TheeJ, welches Element welches ist.",
        "add.type_note.smc": "Ein M-VAVE SMC-Mixer. Seine Bedienelemente sind bekannt, er braucht keine Kalibrierung.",
        "add_profile": "Profil hinzufügen",
        "applications_only": "TheeJ aktualisiert sich nur, wenn es aus dem Ordner „Programme“ läuft.",
        "apply": "Anwenden",
        "audio_text": "Um die Lautstärke einer App einzustellen, gibt TheeJ den Ton dieser App in der Lautstärke des Reglers wieder, was macOS als Aufnahme wertet. Erlaube TheeJ unter „Bildschirm- & Systemaudioaufnahme“ in „Datenschutz & Sicherheit“, beende TheeJ dann und öffne es erneut.",
        "audio_title": "TheeJ kann App-Lautstärken noch nicht einstellen",
        "auto": "Automatisch suchen",
        "available": "TheeJ {version} ist verfügbar",
        "baud_note": "Muss zu Serial.begin() im Sketch deines Boards passen.",
        "baud_rate": "Baudrate",
        "board.button": "Taste {letter}",
        "board.empty": "Dieses Board hat keine Bedienelemente.",
        "board.fader": "Fader {letter}",
        "board.hint": "Bewege oder drück ein Bedienelement am Board oder klicke es hier an, um festzulegen, was es tut.",
        "boards.add": "Board hinzufügen",
        "boards.none": "Noch keine Boards.",
        "boards.none_connected": "Kein Board ist verbunden.",
        "boards.on": "{name} an",
        "boards.set_up": "Boards einrichten",
        "boards.settings": "Board-Einstellungen",
        "boards.settings_of": "Einstellungen von {name}",
        "boards.title": "Boards",
        "by": "Von",
        "calibrate": "Kalibrieren",
        "cancel": "Abbrechen",
        "check": "Nach Updates suchen…",
        "check_connection": "Prüfe deine Verbindung und versuche es erneut.",
        "check_failed": "Suche nach Updates fehlgeschlagen",
        "checking_signature": "Signatur wird geprüft…",
        "choose": "Auswählen",
        "choose_language": "Wähle deine Sprache",
        "clear": "Löschen",
        "click_to_update": "Du hast {version}. Zum Aktualisieren klicken.",
        "close": "Schließen",
        "connected": "Verbunden: {port}",
        "continue": "Fortfahren",
        "daily": "Täglich",
        "default_profile": "Standard",
        "device.pick_input": "MIDI-Eingang wählen",
        "device.remove": "Board entfernen",
        "device.remove_info": "Seine Profile und seine Kalibrierung gehen mit.",
        "device.type": "Typ",
        "device.type.diy": "Eigenbau (Arduino)",
        "device.type.midi": "Anderes MIDI",
        "device.type.smc": "SMC-Mixer",
        "device.used_by": "{port} (genutzt von {board})",
        "dock": "Im Dock behalten",
        "dock_restart": "Dock neu starten",
        "dock_restart_text": "Dafür muss macOS das Dock neu starten. Bildschirm und Menüleiste flackern dabei kurz.",
        "dock_restart_title": "Dock neu starten?",
        "download": "Download",
        "download_failed": "Der Download ist fehlgeschlagen.",
        "downloading": "Version {version} wird geladen…",
        "finish": "Fertig",
        "general.app": "App",
        "hide_icon": "Symbol in der Menüleiste ausblenden",
        "hide_icon_note": "Öffne TheeJ erneut, um hierher zurückzukommen.",
        "icon": "Symbol",
        "icon.app": "App-Symbol",
        "icon.dial": "Drehregler",
        "icon.mixer": "Mischpult",
        "inspired_by": "Inspiriert von",
        "install_now": "Version {version} jetzt installieren",
        "installed": "Version {version} ist installiert.",
        "installing": "Wird installiert…",
        "job.brightness": "Helligkeit von Display {n}",
        "job.builtin_brightness": "Helligkeit des integrierten Displays",
        "job.builtin_contrast": "Kontrast des integrierten Displays",
        "job.builtin_keyboard": "Beleuchtung der integrierten Tastatur",
        "job.contrast": "Kontrast von Display {n}",
        "job.empty": "Leer",
        "job.external_keyboard": "Beleuchtung der externen Tastatur",
        "job.master": "Gesamtlautstärke",
        "job.microphone": "Mikrofonlautstärke",
        "job.night_shift": "Night Shift-Farbtemperatur",
        "job.nothing": "Nichts",
        "job.zoom": "Bildschirmzoom",
        "knob": "Regler {letter}",
        "knobs": "Regler",
        "language": "Sprache",
        "language_note": "Du kannst sie später in den Einstellungen oder im Menü ändern.",
        "later": "Später",
        "lights": "Tastenbeleuchtung",
        "lights.ball": "Ball",
        "lights.bars": "Balken",
        "lights.blink": "Blinken",
        "lights.bounce": "Pendel",
        "lights.breathe": "Atmen",
        "lights.chase": "Lauflicht",
        "lights.checker": "Schachbrett",
        "lights.clock": "Binäruhr",
        "lights.comet": "Komet",
        "lights.eq": "EQ",
        "lights.eq2": "EQ 2",
        "lights.eqgame": "EQ Gaming",
        "lights.explode": "Explosion",
        "lights.fill": "Füllen",
        "lights.fire": "Feuer",
        "lights.heartbeat": "Herzschlag",
        "lights.helix": "Helix",
        "lights.matrix": "Matrix",
        "lights.off": "Aus",
        "lights.on": "An",
        "lights.orbit": "Umlauf",
        "lights.rain": "Regen",
        "lights.random": "Zufall",
        "lights.rise": "Aufsteigen",
        "lights.snake": "Schlange",
        "lights.sparkle": "Funkeln",
        "lights.stars": "Sterne",
        "lights.wave": "Welle",
        "lights.zigzag": "Zickzack",
        "lights_note": "Gedrückte Tasten und Stummschaltungen leuchten weiterhin.",
        "list.buttons": "Tasten",
        "list.faders": "Fader",
        "list.none": "Keine",
        "login": "Beim Anmelden starten",
        "m1ddc.note": "Für Helligkeit und Kontrast externer Displays",
        "m1ddc.installed": "Installiert",
        "m1ddc.missing": "Nicht installiert",
        "m1ddc.install": "Installieren",
        "m1ddc.refresh": "Aktualisieren",
        "m1ddc.support": "Support:",
        "made_by": "Erstellt von",
        "menu.board": "{name}: {status}",
        "mixer.fader": "Fader {n}",
        "mixer.knob": "Regler {n}",
        "mixer_port_note": "Wähle deinen MIDI-Mixer, um ihn neben dem Board zu nutzen.",
        "name": "Name",
        "needs_calibration": "Muss kalibriert werden",
        "never": "Nie",
        "newest": "TheeJ {version} ist die neueste verfügbare Version.",
        "next_profile": "Nächstes Profil",
        "not_connected": "Nicht verbunden",
        "not_signed": "Der Download ist nicht von Zolfer Figueiredo signiert.",
        "now_using": "Du verwendest jetzt TheeJ {version}, die neueste verfügbare Version.",
        "ok": "OK",
        "on_windows": "Unter Windows? Hol dir",
        "open_settings": "Systemeinstellungen öffnen",
        "other": "Andere…",
        "port": "Gerät",
        "port_auto": "Automatisch",
        "port_busy": "{port} wird von einer anderen App verwendet",
        "port_forced": "Beim Start von TheeJ auf {port} festgelegt.",
        "port_note": "Automatisch findet dein Board von selbst.",
        "press_shortcut": "Kurzbefehl drücken",
        "previous_profile": "Vorheriges Profil",
        "profile": "Profil",
        "profile.edit": "Profil bearbeiten…",
        "profile_list": "Profilliste",
        "profile_n": "Profil {n}",
        "quit": "TheeJ beenden",
        "reconnect": "Neu verbinden",
        "record_shortcut": "Kurzbefehl setzen",
        "refresh": "Aktualisieren",
        "remove": "Entfernen",
        "remove_named": "„{name}“ entfernen?",
        "remove_profile": "Dieses Profil entfernen",
        "remove_profile_info": "Seine Reglerbelegung und sein Kurzbefehl werden mit entfernt.",
        "remove_shortcut": "Kurzbefehl entfernen",
        "remove_this_profile": "Dieses Profil entfernen?",
        "reopen": "Neu öffnen",
        "reopen_failed": "Neu öffnen fehlgeschlagen: {error} Beende die App und öffne sie selbst.",
        "save": "Speichern",
        "section.apps": "Apps",
        "section.brightness": "Helligkeit",
        "section.contrast": "Kontrast",
        "section.keyboard": "Tastaturbeleuchtung",
        "section.night_shift": "Night Shift",
        "section.volume": "Lautstärke",
        "section.zoom": "Zoom",
        "settings": "Einstellungen",
        "short.builtin": "Integriert",
        "short.builtin_display": "Integriertes Display",
        "short.external": "Extern",
        "short.screen": "Display {n}",
        "short.warmth": "Farbtemperatur",
        "shortcut": "Kurzbefehl",
        "shortcut.also_used": "Auch genutzt von {names}",
        "shortcut.clash": "Dieses Board nutzt diesen Kurzbefehl schon. Probiere einen anderen.",
        "shortcut.taken": "Eine andere App nutzt diesen Kurzbefehl. Probiere einen anderen.",
        "shortcut_tip": "Verwende ⌘ oder ⌃ mit einer Taste. Die Rückschritttaste löscht ihn, Escape bricht ab.",
        "show_data": "Daten unten anzeigen",
        "show_name": "Profilnamen anzeigen",
        "skip": "Überspringen",
        "smc.bank_left": "Vorherige Bank",
        "smc.bank_right": "Nächste Bank",
        "smc.down": "Runter",
        "smc.hint": "Bewege oder drück ein Bedienelement am Mixer oder klicke es hier an, um festzulegen, was es tut.",
        "smc.left": "Links",
        "smc.record": "Aufnahme",
        "smc.right": "Rechts",
        "smc.square": "Quadrat {n}",
        "smc.up": "Hoch",
        "space": "Leertaste",
        "speed": "Geschwindigkeit",
        "speed.fast": "Schnell",
        "speed.medium": "Mittel",
        "speed.slow": "Langsam (empfohlen)",
        "speed.superFast": "Sehr schnell",
        "speed_note": "Wie schnell eine Drehung wirkt.",
        "status": "Status",
        "status.connected": "Verbunden",
        "status.disconnected": "Getrennt",
        "status.off": "Aus",
        "tab.about": "Info",
        "tab.boards": "Boards",
        "tab.general": "Allgemein",
        "tool_failed": "{tool} fehlgeschlagen ({code}).",
        "up_to_date": "Du bist auf dem neuesten Stand!",
        "update_available": "Update verfügbar!",
        "update_complete": "Update abgeschlossen!",
        "update_failed": "Update konnte nicht installiert werden",
        "update_now": "Jetzt installieren",
        "update_question": "Du hast {version}. Jetzt aktualisieren?",
        "updating_to": "TheeJ wird auf {version} aktualisiert",
        "version": "Version {version}",
        "view.draw": "Zeichnung",
        "view.list": "Liste",
        "website": "Website",
        "weekly": "Wöchentlich",
        "wizard.count": "{n} von {of}",
        "wizard.done": "Alle Elemente gefunden. Drücke Fertig, um sie zu behalten.",
        "wizard.find": "Stelle {name} wieder auf 0 %.",
        "wizard.full": "Stelle jetzt jeden Regler und Fader auf 100 % und drücke dann Weiter.",
        "wizard.mismatch": "Das war eine andere Taste. Drücke {name} dreimal.",
        "wizard.nothing": "Zwischen 0 % und 100 % hat sich nichts bewegt.",
        "wizard.press": "Drücke {name} dreimal.",
        "wizard.redo": "Neu beginnen",
        "wizard.step": "{i} von {n}",
        "wizard.title": "{name} kalibrieren",
        "wizard.unswept": "Dieser hat sich zwischen 0 % und 100 % nicht bewegt. Drücke auf Neu beginnen.",
        "wizard.waiting": "Warte, bis {name} verbunden ist.",
        "wizard.wrong": "Das ist {other}. Bewege stattdessen {name}.",
        "wizard.zero": "Stelle jeden Regler und Fader auf 0 % und drücke dann Weiter.",
        "wrong_download": "Der Download ist nicht TheeJ {version}.",
    ]
}
