// English. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let en: [String: String] = [
        "about": "About TheeJ",
        "add_knob": "Add a knob",
        "add_profile": "Add a profile",
        "applications_only": "TheeJ updates itself only when it runs from the Applications folder.",
        "audio_text": "To set an app’s volume, TheeJ plays that app’s sound back at the knob’s level, which macOS counts as recording it. Allow TheeJ under Screen & System Audio Recording in Privacy & Security, then quit TheeJ and open it again.",
        "audio_title": "TheeJ can’t set app volumes yet",
        "auto": "Check automatically",
        "available": "TheeJ {version} is available",
        "by": "By",
        "cal.all_found": "All knobs found",
        "cal.all_found_text": "Your board sends {n} values, and each one has its knob now, so that’s all of them. Click Finish to choose what they do.",
        "cal.finish_later": "Finish stops here and leaves it for later.",
        "cal.hold": "Your knobs hold still until you finish.",
        "cal.move": "Move knob {letter} from one end to the other.",
        "cal.move_first": "Move knob {letter} from one end to the other, so TheeJ can tell which knob is which. Each knob then gets {n} seconds of turning, which cleans a jumpy one.",
        "cal.no_knob": "If you don’t have a knob {letter}, click Finish.",
        "cal.paused": "Paused with {left}. Keep turning knob {letter}.",
        "cal.skip_keeps": "It’s already set up, so Skip keeps it as it is.",
        "cal.turn": "Found it. Now turn it back and forth, from one end to the other, for {n} seconds. The timer only runs while it turns. Skip if it doesn’t need cleaning.",
        "cal.waiting_board": "Waiting for the board to connect",
        "cal.waiting_knob": "Waiting for knob {letter} to move",
        "cal.wrong": "That’s knob {wrong}. Move knob {letter} instead.",
        "calibrate": "Calibrate",
        "calibration_title": "TheeJ Calibration",
        "cancel": "Cancel",
        "check": "Check for updates…",
        "check_connection": "Check your connection and try again.",
        "check_failed": "Couldn’t check for updates",
        "checking_signature": "Checking the signature…",
        "choose": "Choose",
        "choose_language": "Choose your language",
        "click_to_update": "You have {version}. Click to update.",
        "close": "Close",
        "connected": "Connected: {port}",
        "continue": "Continue",
        "daily": "Daily",
        "default_profile": "Default",
        "dock": "Keep in Dock",
        "download": "Download",
        "download_failed": "The download failed.",
        "downloading": "Downloading version {version}…",
        "finish": "Finish",
        "hide_icon": "Hide menu bar icon",
        "hide_icon_note": "Open TheeJ again to get back here.",
        "icon": "Icon",
        "icon.app": "App icon",
        "icon.dial": "Dial",
        "icon.mixer": "Mixer",
        "inspired_by": "Inspired by",
        "install_now": "Install version {version} now",
        "installed": "Version {version} is installed.",
        "installing": "Installing…",
        "invert": "Invert knobs",
        "invert_note": "For pots wired the other way round.",
        "job.brightness": "Screen {n} brightness",
        "job.builtin_brightness": "Built-in display brightness",
        "job.builtin_contrast": "Built-in display contrast",
        "job.builtin_keyboard": "Built-in keyboard backlight",
        "job.contrast": "Screen {n} contrast",
        "job.external_keyboard": "External keyboard backlight",
        "job.master": "Master volume",
        "job.microphone": "Microphone volume",
        "job.night_shift": "Night Shift warmth",
        "job.nothing": "Nothing",
        "jobs_note": "Tick one or more jobs per knob, for this profile.",
        "knob": "Knob {letter}",
        "knobs": "Knobs",
        "knobs_found.one": "{n} knob found",
        "knobs_found.other": "{n} knobs found",
        "language": "Language",
        "language_note": "You can change it later in Settings or in the menu.",
        "later": "Later",
        "login": "Launch at login",
        "m1ddc.note": "For external screen brightness and contrast",
        "m1ddc.installed": "Installed",
        "m1ddc.missing": "Not installed",
        "m1ddc.install": "Install",
        "m1ddc.refresh": "Refresh",
        "m1ddc.support": "Support:",
        "made_by": "Made by",
        "menu_bar": "Menu bar",
        "name": "Name",
        "needs_calibration": "Needs calibration",
        "never": "Never",
        "newest": "TheeJ {version} is currently the newest version available.",
        "next_profile": "Next profile",
        "no_knobs": "No knobs. Calibrate finds them, or press + to add one.",
        "not_connected": "Not connected",
        "not_signed": "The download isn’t signed by Zolfer Figueiredo.",
        "now_using": "You’re now using TheeJ {version}, the newest version available.",
        "ok": "OK",
        "open_settings": "Open System Settings",
        "other": "Other…",
        "press_shortcut": "Press Shortcut",
        "previous_profile": "Previous profile",
        "profile": "Profile",
        "profile_list": "Profile list",
        "profile_n": "Profile {n}",
        "profiles": "Profiles",
        "quit": "Quit TheeJ",
        "reconnect": "Reconnect",
        "record_shortcut": "Record Shortcut",
        "remove": "Remove",
        "remove_knob": "Remove the last knob",
        "remove_knob_info": "What it does in every profile goes with it.",
        "remove_knob_q": "Remove knob {letter}?",
        "remove_named": "Remove “{name}”?",
        "remove_profile": "Remove this profile",
        "remove_profile_info": "Its knob choices and shortcut go with it.",
        "remove_shortcut": "Remove shortcut",
        "remove_this_profile": "Remove this profile?",
        "reopen": "Reopen",
        "reopen_failed": "Couldn’t reopen: {error} Quit and open it yourself.",
        "save": "Save",
        "seconds_left.one": "{n} second left",
        "seconds_left.other": "{n} seconds left",
        "section.apps": "Apps",
        "section.brightness": "Brightness",
        "section.contrast": "Contrast",
        "section.keyboard": "Keyboard backlight",
        "section.night_shift": "Night Shift",
        "section.volume": "Volume",
        "sensitivity": "Sensitivity",
        "settings": "Settings",
        "short.builtin": "Built-in",
        "short.builtin_display": "Built-in display",
        "short.external": "External",
        "short.screen": "Screen {n}",
        "short.warmth": "Warmth",
        "shortcut": "Shortcut",
        "shortcut_tip": "Use ⌘ or ⌃ with a key. Delete clears it, Escape cancels.",
        "shortcuts": "Shortcuts",
        "show_data": "Show data below",
        "show_name": "Show profile name",
        "skip": "Skip",
        "space": "Space",
        "speed": "Speed",
        "speed.fast": "Fast",
        "speed.medium": "Medium",
        "speed.slow": "Slow (Recommended)",
        "speed.superFast": "Super fast",
        "speed_note": "How soon a change lands after a turn.",
        "tab.about": "About",
        "tab.app": "App settings",
        "tab.general": "General",
        "tool_failed": "{tool} failed ({code}).",
        "up_to_date": "You're up to date!",
        "update_available": "Update available!",
        "update_complete": "Update complete!",
        "update_failed": "Couldn’t install the update",
        "update_now": "Update Now",
        "update_question": "You have {version}. Update now?",
        "updating_to": "Updating TheeJ to {version}",
        "version": "Version {version}",
        "website": "Website",
        "weekly": "Weekly",
        "wrong_download": "The download isn’t TheeJ {version}.",
    ]
}
