// English. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let en: [String: String] = [
        "about": "About TheeJ",
        "action.close_app": "Close an app",
        "action.go_profile": "Go to {name}",
        "action.group.apps": "Apps",
        "action.group.fkeys": "Function keys",
        "action.group.knobs": "Knobs",
        "action.group.media": "Media",
        "action.group.system": "System",
        "action.keys": "Press a shortcut",
        "action.lights_off": "Button lights off",
        "action.lights_on": "Button lights on",
        "action.lock": "Lock the Mac",
        "action.mute": "Mute {name}",
        "action.mute_all": "Mute all sound",
        "action.mute_mic": "Mute microphone",
        "action.next_lights": "Next button lights",
        "action.next_track": "Next track",
        "action.night_light": "Night Shift on/off",
        "action.open_app": "Open an app",
        "action.open_settings": "Open Settings",
        "action.open_url": "Open a website",
        "action.pause": "Pause",
        "action.play": "Play",
        "action.play_pause": "Play/pause",
        "action.previous_lights": "Previous button lights",
        "action.previous_track": "Previous track",
        "action.screens_off": "Turn off screens",
        "action.sleep": "Sleep",
        "action.volume_down": "Volume down",
        "action.volume_up": "Volume up",
        "add.add": "Add",
        "add.name_hint": "Desk",
        "add.next": "Next",
        "add.title": "Add a board",
        "add.type_note.diy": "An Arduino that sends its knobs over USB, like deej’s.",
        "add.type_note.midi": "Any other MIDI controller. You show TheeJ which control is which.",
        "add.type_note.smc": "An M-VAVE SMC-Mixer. Its controls are known, so it needs no calibration.",
        "add_profile": "Add a profile",
        "applications_only": "TheeJ updates itself only when it runs from the Applications folder.",
        "apply": "Apply",
        "audio_text": "To set an app’s volume, TheeJ plays that app’s sound back at the knob’s level, which macOS counts as recording it. Allow TheeJ under Screen & System Audio Recording in Privacy & Security, then quit TheeJ and open it again.",
        "audio_title": "TheeJ can’t set app volumes yet",
        "auto": "Check automatically",
        "available": "TheeJ {version} is available",
        "baud_note": "Must match Serial.begin() in your board’s sketch.",
        "baud_rate": "Baud rate",
        "board.arrange": "Arrange the drawing",
        "board.button": "Button {letter}",
        "board.down": "Move down a row",
        "board.empty": "This board has no controls.",
        "board.fader": "Fader {letter}",
        "board.hint": "Move or press a control on your board, or click it here, to choose what it does.",
        "board.left": "Move left",
        "board.right": "Move right",
        "board.up": "Move up a row",
        "boards.add": "Add board",
        "boards.none": "No boards yet.",
        "boards.none_connected": "No board is connected.",
        "boards.on": "{name} on",
        "boards.set_up": "Set up boards",
        "boards.settings": "Board settings",
        "boards.settings_of": "{name} settings",
        "boards.title": "Boards",
        "by": "By",
        "calibrate": "Calibrate",
        "cancel": "Cancel",
        "check": "Check for updates…",
        "check_connection": "Check your connection and try again.",
        "check_failed": "Couldn’t check for updates",
        "checking_signature": "Checking the signature…",
        "choose": "Choose",
        "choose_language": "Choose your language",
        "clear": "Clear",
        "click_to_update": "You have {version}. Click to update.",
        "close": "Close",
        "connected": "Connected: {port}",
        "continue": "Continue",
        "daily": "Daily",
        "default_profile": "Default",
        "device.pick_input": "Pick a MIDI input",
        "device.remove": "Remove board",
        "device.remove_info": "Its profiles and calibration go with it.",
        "device.type": "Type",
        "device.type.diy": "DIY (Arduino)",
        "device.type.midi": "Other MIDI",
        "device.type.smc": "SMC-Mixer",
        "device.used_by": "{port} (used by {board})",
        "dock": "Keep in Dock",
        "dock_restart": "Restart Dock",
        "dock_restart_text": "To change this, macOS has to restart the Dock. Your screen and the menu bar will blink for a moment.",
        "dock_restart_title": "Restart the Dock?",
        "download": "Download",
        "download_failed": "The download failed.",
        "downloading": "Downloading version {version}…",
        "finish": "Finish",
        "general.app": "App",
        "hide_icon": "Hide menu bar icon",
        "hide_icon_note": "Open TheeJ again to get back here.",
        "icon": "Icon",
        "icon.app": "App icon",
        "icon.dial": "Dial",
        "icon.mixer": "Mixer",
        "import_failed": "Couldn’t read that file.",
        "import_skipped": "Not imported: {items}",
        "inspired_by": "Inspired by",
        "install_now": "Install version {version} now",
        "installed": "Version {version} is installed.",
        "installing": "Installing…",
        "job.brightness": "Screen {n} brightness",
        "job.builtin_brightness": "Built-in display brightness",
        "job.builtin_contrast": "Built-in display contrast",
        "job.builtin_keyboard": "Built-in keyboard backlight",
        "job.contrast": "Screen {n} contrast",
        "job.empty": "Empty",
        "job.external_keyboard": "External keyboard backlight",
        "job.focused_app": "Focused app",
        "job.master": "Master volume",
        "job.microphone": "Microphone volume",
        "job.night_shift": "Night Shift warmth",
        "job.nothing": "Nothing",
        "job.other_apps": "Other apps",
        "job.system_sounds": "System sounds",
        "job.zoom": "Screen zoom",
        "knob": "Knob {letter}",
        "knobs": "Knobs",
        "language": "Language",
        "language_note": "You can change it later in Settings or in the menu.",
        "later": "Later",
        "lights": "Button lights",
        "lights.ball": "Ball",
        "lights.bars": "Bars",
        "lights.blink": "Blink",
        "lights.bounce": "Bounce",
        "lights.breathe": "Breathe",
        "lights.chase": "Chase",
        "lights.checker": "Checkers",
        "lights.clock": "Binary clock",
        "lights.comet": "Comet",
        "lights.eq": "EQ",
        "lights.eq2": "EQ 2",
        "lights.eqgame": "EQ Gaming",
        "lights.explode": "Explode",
        "lights.fill": "Fill",
        "lights.fire": "Fire",
        "lights.heartbeat": "Heartbeat",
        "lights.helix": "Helix",
        "lights.matrix": "Matrix",
        "lights.off": "Off",
        "lights.on": "On",
        "lights.orbit": "Orbit",
        "lights.rain": "Rain",
        "lights.random": "Random",
        "lights.rise": "Rise",
        "lights.snake": "Snake",
        "lights.sparkle": "Sparkle",
        "lights.stars": "Stars",
        "lights.wave": "Wave",
        "lights.zigzag": "Zigzag",
        "lights_note": "Pressed buttons and mutes still light up.",
        "list.buttons": "Buttons",
        "list.faders": "Faders",
        "list.none": "None",
        "login": "Launch at login",
        "m1ddc.note": "For external screen brightness and contrast",
        "m1ddc.installed": "Installed",
        "m1ddc.missing": "Not installed",
        "m1ddc.install": "Install",
        "m1ddc.refresh": "Refresh",
        "m1ddc.support": "Support:",
        "made_by": "Made by",
        "menu.board": "{name}: {status}",
        "mixer.fader": "Fader {n}",
        "mixer.knob": "Knob {n}",
        "mixer_port_note": "Pick your MIDI mixer to use it next to the board.",
        "name": "Name",
        "needs_calibration": "Needs calibration",
        "never": "Never",
        "newest": "TheeJ {version} is currently the newest version available.",
        "next_profile": "Next profile",
        "not_connected": "Not connected",
        "not_signed": "The download isn’t signed by Zolfer Figueiredo.",
        "now_using": "You’re now using TheeJ {version}, the newest version available.",
        "ok": "OK",
        "on_windows": "On Windows? Get",
        "open_settings": "Open System Settings",
        "other": "Other…",
        "port": "Device",
        "port_auto": "Automatic",
        "port_busy": "{port} is in use by another app",
        "port_forced": "Set to {port} when TheeJ was started.",
        "port_note": "Automatic finds your board by itself.",
        "press_shortcut": "Press Shortcut",
        "previous_profile": "Previous profile",
        "profile": "Profile",
        "profile.edit": "Edit profile…",
        "profile.export": "Export…",
        "profile.export_failed": "Couldn’t save the profile.",
        "profile.import": "Import…",
        "profile_list": "Profile list in tray menu",
        "profile_n": "Profile {n}",
        "quit": "Quit TheeJ",
        "reconnect": "Reconnect",
        "record_shortcut": "Record Shortcut",
        "refresh": "Refresh",
        "remove": "Remove",
        "remove_named": "Remove “{name}”?",
        "remove_profile": "Remove this profile",
        "remove_profile_info": "Its knob choices and shortcut go with it.",
        "remove_shortcut": "Remove shortcut",
        "remove_this_profile": "Remove this profile?",
        "reopen": "Reopen",
        "reopen_failed": "Couldn’t reopen: {error} Quit and open it yourself.",
        "save": "Save",
        "section.apps": "Apps",
        "section.brightness": "Brightness",
        "section.contrast": "Contrast",
        "section.keyboard": "Keyboard backlight",
        "section.night_shift": "Night Shift",
        "section.volume": "Volume",
        "section.zoom": "Zoom",
        "settings": "Settings",
        "setup.board": "Board {n} of {of}",
        "setup.note": "Count your Arduino boards, SMC-Mixers and other MIDI controllers. You add them one by one.",
        "setup.title": "How many boards do you have?",
        "short.builtin": "Built-in",
        "short.builtin_display": "Built-in display",
        "short.external": "External",
        "short.screen": "Screen {n}",
        "short.warmth": "Warmth",
        "shortcut": "Shortcut",
        "shortcut.also_used": "Also used by {names}",
        "shortcut.clash": "This board already uses that shortcut. Try another.",
        "shortcut.taken": "Another app uses that shortcut. Try another.",
        "shortcut_tip": "Use ⌘ or ⌃ with a key. Delete clears it, Escape cancels.",
        "show_data": "Show data below",
        "show_name": "Show profile name",
        "skip": "Skip",
        "smc.bank_left": "Previous bank",
        "smc.bank_right": "Next bank",
        "smc.down": "Down",
        "smc.hint": "Move or press a control on the mixer, or click it here, to choose what it does.",
        "smc.left": "Left",
        "smc.record": "Record",
        "smc.right": "Right",
        "smc.square": "Square {n}",
        "smc.up": "Up",
        "space": "Space",
        "speed": "Speed",
        "speed.fast": "Fast",
        "speed.medium": "Medium",
        "speed.slow": "Slow (Recommended)",
        "speed.superFast": "Super fast",
        "speed_note": "How soon a change lands after a turn.",
        "status": "Status",
        "status.connected": "Connected",
        "status.disconnected": "Disconnected",
        "status.off": "Off",
        "tab.about": "About",
        "tab.boards": "Boards",
        "tab.general": "General",
        "tool_failed": "{tool} failed ({code}).",
        "up_to_date": "You're up to date!",
        "update_available": "Update available!",
        "update_complete": "Update complete!",
        "update_failed": "Couldn’t install the update",
        "update_now": "Update Now",
        "update_question": "You have {version}. Update now?",
        "updating_to": "Updating TheeJ to {version}",
        "version": "Version {version}",
        "view.draw": "Draw",
        "view.list": "List",
        "website": "Website",
        "weekly": "Weekly",
        "wizard.count": "{n} of {of}",
        "wizard.done": "Every control is found. Press Finish to keep them.",
        "wizard.find": "Turn {name} back to 0%.",
        "wizard.full": "Now turn every knob and fader to 100%, then press Next.",
        "wizard.mismatch": "That was another button. Press {name} three times.",
        "wizard.nothing": "Nothing moved between 0% and 100%.",
        "wizard.press": "Press {name} three times.",
        "wizard.redo": "Start again",
        "wizard.step": "{i} of {n}",
        "wizard.title": "Calibrate {name}",
        "wizard.unswept": "That one didn’t move between 0% and 100%. Press Start again.",
        "wizard.waiting": "Waiting for {name} to connect.",
        "wizard.wrong": "That is {other}. Move {name} instead.",
        "wizard.zero": "Turn every knob and fader to 0%, then press Next.",
        "wrong_download": "The download isn’t TheeJ {version}.",
    ]
}
