// Español. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let es: [String: String] = [
        "about": "Acerca de TheeJ",
        "action.close_app": "Cerrar una app",
        "action.go_profile": "Ir a {name}",
        "action.group.apps": "Apps",
        "action.group.fkeys": "Teclas de función",
        "action.group.knobs": "Controles",
        "action.group.media": "Multimedia",
        "action.group.system": "Sistema",
        "action.keys": "Pulsar un atajo",
        "action.lights_off": "Apagar luces de los botones",
        "action.lights_on": "Encender luces de los botones",
        "action.lock": "Bloquear el Mac",
        "action.mute": "Silenciar {name}",
        "action.mute_all": "Silenciar todo",
        "action.mute_mic": "Silenciar micrófono",
        "action.next_lights": "Siguientes luces de los botones",
        "action.next_track": "Pista siguiente",
        "action.night_light": "Night Shift sí/no",
        "action.open_app": "Abrir una app",
        "action.open_settings": "Abrir Ajustes",
        "action.open_url": "Abrir un sitio web",
        "action.pause": "Pausa",
        "action.play": "Reproducir",
        "action.play_pause": "Reproducir/pausa",
        "action.previous_lights": "Luces de los botones anteriores",
        "action.previous_track": "Pista anterior",
        "action.screens_off": "Apagar pantallas",
        "action.sleep": "Suspender",
        "action.volume_down": "Bajar volumen",
        "action.volume_up": "Subir volumen",
        "add.add": "Añadir",
        "add.name_hint": "Escritorio",
        "add.next": "Siguiente",
        "add.title": "Añadir una placa",
        "add.type_note.diy": "Un Arduino que envía sus mandos por USB, como el de deej.",
        "add.type_note.midi": "Cualquier otro controlador MIDI. Le muestras a TheeJ qué control es cuál.",
        "add.type_note.smc": "Un M-VAVE SMC-Mixer. Sus controles ya se conocen, así que no necesita calibración.",
        "add_profile": "Añadir un perfil",
        "applications_only": "TheeJ solo se actualiza cuando se ejecuta desde la carpeta Aplicaciones.",
        "apply": "Aplicar",
        "audio_text": "Para ajustar el volumen de una app, TheeJ reproduce el sonido de esa app al nivel del control, y macOS lo considera una grabación. Permite TheeJ en «Grabación de pantalla y audio del sistema», dentro de «Privacidad y seguridad», y después cierra TheeJ y vuelve a abrirlo.",
        "audio_title": "TheeJ aún no puede ajustar el volumen de las apps",
        "auto": "Buscar automáticamente",
        "available": "TheeJ {version} está disponible",
        "baud_note": "Debe coincidir con Serial.begin() en el sketch de tu placa.",
        "baud_rate": "Velocidad (baudios)",
        "board.arrange": "Organizar el dibujo",
        "board.button": "Botón {letter}",
        "board.down": "Bajar una fila",
        "board.empty": "Esta placa no tiene controles.",
        "board.fader": "Fader {letter}",
        "board.hint": "Mueve o pulsa un control de la placa, o haz clic en él aquí, para elegir qué hace.",
        "board.left": "Mover a la izquierda",
        "board.right": "Mover a la derecha",
        "board.up": "Subir una fila",
        "boards.add": "Añadir placa",
        "boards.none": "Aún no hay placas.",
        "boards.none_connected": "No hay ninguna placa conectada.",
        "boards.on": "{name} encendida",
        "boards.set_up": "Configurar placas",
        "boards.settings": "Ajustes de la placa",
        "boards.settings_of": "Ajustes de {name}",
        "boards.title": "Placas",
        "by": "Por",
        "calibrate": "Calibrar",
        "cancel": "Cancelar",
        "check": "Buscar actualizaciones…",
        "check_connection": "Comprueba tu conexión e inténtalo de nuevo.",
        "check_failed": "No se pudieron buscar actualizaciones",
        "checking_signature": "Comprobando la firma…",
        "choose": "Elegir",
        "choose_language": "Elige tu idioma",
        "clear": "Borrar",
        "click_to_update": "Tienes la {version}. Haz clic para actualizar.",
        "close": "Cerrar",
        "connected": "Conectado: {port}",
        "continue": "Continuar",
        "daily": "Cada día",
        "default_profile": "Predeterminado",
        "device.pick_input": "Elige una entrada MIDI",
        "device.remove": "Quitar placa",
        "device.remove_info": "Sus perfiles y su calibración se van con ella.",
        "device.type": "Tipo",
        "device.type.diy": "Casera (Arduino)",
        "device.type.midi": "Otro MIDI",
        "device.type.smc": "SMC-Mixer",
        "device.used_by": "{port} (en uso por {board})",
        "dock": "Mantener en el Dock",
        "dock_restart": "Reiniciar el Dock",
        "dock_restart_text": "Para cambiar esto, macOS tiene que reiniciar el Dock. La pantalla y la barra de menús parpadearán un momento.",
        "dock_restart_title": "¿Reiniciar el Dock?",
        "download": "Descargar",
        "download_failed": "La descarga falló.",
        "downloading": "Descargando la versión {version}…",
        "finish": "Terminar",
        "general.app": "Aplicación",
        "hide_icon": "Ocultar el icono de la barra de menús",
        "hide_icon_note": "Abre TheeJ de nuevo para volver aquí.",
        "icon": "Icono",
        "icon.app": "Icono de la app",
        "icon.dial": "Dial",
        "icon.mixer": "Mezclador",
        "import_failed": "No se pudo leer ese archivo.",
        "import_skipped": "No se importó: {items}",
        "inspired_by": "Inspirado en",
        "install_now": "Instalar la versión {version} ahora",
        "installed": "La versión {version} está instalada.",
        "installing": "Instalando…",
        "job.brightness": "Brillo de la pantalla {n}",
        "job.builtin_brightness": "Brillo de la pantalla integrada",
        "job.builtin_contrast": "Contraste de la pantalla integrada",
        "job.builtin_keyboard": "Luz del teclado integrado",
        "job.contrast": "Contraste de la pantalla {n}",
        "job.empty": "Vacío",
        "job.external_keyboard": "Luz del teclado externo",
        "job.focused_app": "App en primer plano",
        "job.master": "Volumen general",
        "job.microphone": "Volumen del micrófono",
        "job.night_shift": "Calidez de Night Shift",
        "job.nothing": "Nada",
        "job.other_apps": "Otras apps",
        "job.system_sounds": "Sonidos del sistema",
        "job.zoom": "Zoom de pantalla",
        "knob": "Control {letter}",
        "knobs": "Controles",
        "language": "Idioma",
        "language_note": "Puedes cambiarlo más tarde en Ajustes o en el menú.",
        "later": "Más tarde",
        "lights": "Luces de los botones",
        "lights.ball": "Pelota",
        "lights.bars": "Barras",
        "lights.blink": "Parpadeo",
        "lights.bounce": "Rebote",
        "lights.breathe": "Respiración",
        "lights.chase": "Persecución",
        "lights.checker": "Damero",
        "lights.clock": "Reloj binario",
        "lights.comet": "Cometa",
        "lights.eq": "Ecualizador",
        "lights.eq2": "Ecualizador 2",
        "lights.eqgame": "Ecualizador gaming",
        "lights.explode": "Explosión",
        "lights.fill": "Llenar",
        "lights.fire": "Fuego",
        "lights.heartbeat": "Latido",
        "lights.helix": "Hélice",
        "lights.matrix": "Matrix",
        "lights.off": "Apagadas",
        "lights.on": "Encendidas",
        "lights.orbit": "Órbita",
        "lights.rain": "Lluvia",
        "lights.random": "Aleatorio",
        "lights.rise": "Subida",
        "lights.snake": "Serpiente",
        "lights.sparkle": "Destellos",
        "lights.stars": "Estrellas",
        "lights.wave": "Ola",
        "lights.zigzag": "Zigzag",
        "lights_note": "Los botones pulsados y los silencios se siguen iluminando.",
        "list.buttons": "Botones",
        "list.faders": "Faders",
        "list.none": "Ninguno",
        "login": "Abrir al iniciar sesión",
        "m1ddc.note": "Para el brillo y el contraste de pantallas externas",
        "m1ddc.installed": "Instalado",
        "m1ddc.missing": "No instalado",
        "m1ddc.install": "Instalar",
        "m1ddc.refresh": "Actualizar",
        "m1ddc.support": "Soporte:",
        "made_by": "Hecho por",
        "menu.board": "{name}: {status}",
        "mixer.fader": "Fader {n}",
        "mixer.knob": "Control {n}",
        "mixer_port_note": "Elige tu mezclador MIDI para usarlo junto a la placa.",
        "name": "Nombre",
        "needs_calibration": "Necesita calibración",
        "never": "Nunca",
        "newest": "TheeJ {version} es la versión más reciente disponible.",
        "next_profile": "Perfil siguiente",
        "not_connected": "Sin conexión",
        "not_signed": "La descarga no está firmada por Zolfer Figueiredo.",
        "now_using": "Ahora usas TheeJ {version}, la versión más reciente disponible.",
        "ok": "OK",
        "on_windows": "¿En Windows? Descarga",
        "open_settings": "Abrir Ajustes del Sistema",
        "other": "Otra…",
        "port": "Dispositivo",
        "port_auto": "Automático",
        "port_busy": "{port} está en uso por otra app",
        "port_forced": "Fijado en {port} al iniciar TheeJ.",
        "port_note": "En automático, TheeJ encuentra tu placa por sí solo.",
        "press_shortcut": "Pulsa el atajo",
        "previous_profile": "Perfil anterior",
        "profile": "Perfil",
        "profile.edit": "Editar perfil…",
        "profile.export": "Exportar…",
        "profile.export_failed": "No se pudo guardar el perfil.",
        "profile.import": "Importar…",
        "profile_list": "Lista de perfiles en el menú de la barra de menús",
        "profile_n": "Perfil {n}",
        "quit": "Salir de TheeJ",
        "reconnect": "Reconectar",
        "record_shortcut": "Grabar atajo",
        "refresh": "Actualizar",
        "remove": "Eliminar",
        "remove_named": "¿Eliminar «{name}»?",
        "remove_profile": "Eliminar este perfil",
        "remove_profile_info": "Sus funciones y su atajo se eliminan con él.",
        "remove_shortcut": "Eliminar atajo",
        "remove_this_profile": "¿Eliminar este perfil?",
        "reopen": "Volver a abrir",
        "reopen_failed": "No se pudo volver a abrir: {error} Sal de la app y ábrela tú.",
        "save": "Guardar",
        "section.apps": "Apps",
        "section.brightness": "Brillo",
        "section.contrast": "Contraste",
        "section.keyboard": "Luz del teclado",
        "section.night_shift": "Night Shift",
        "section.volume": "Volumen",
        "section.zoom": "Zoom",
        "settings": "Ajustes",
        "setup.board": "Placa {n} de {of}",
        "setup.note": "Cuenta tus placas Arduino, SMC-Mixer y otros controladores MIDI. Las añades una a una.",
        "setup.title": "¿Cuántas placas tienes?",
        "short.builtin": "Integrado",
        "short.builtin_display": "Pantalla integrada",
        "short.external": "Externo",
        "short.screen": "Pantalla {n}",
        "short.warmth": "Calidez",
        "shortcut": "Atajo",
        "shortcut.also_used": "También en uso por {names}",
        "shortcut.clash": "Esta placa ya usa ese atajo. Prueba otro.",
        "shortcut.taken": "Otra app ya usa ese atajo. Prueba otro.",
        "shortcut_tip": "Usa ⌘ o ⌃ con una tecla. Borrar lo elimina, Escape cancela.",
        "show_data": "Mostrar datos abajo",
        "show_name": "Mostrar el nombre del perfil",
        "skip": "Omitir",
        "smc.bank_left": "Banco anterior",
        "smc.bank_right": "Banco siguiente",
        "smc.down": "Abajo",
        "smc.hint": "Mueve o pulsa un control del mezclador, o haz clic en él aquí, para elegir qué hace.",
        "smc.left": "Izquierda",
        "smc.record": "Grabar",
        "smc.right": "Derecha",
        "smc.square": "Cuadrado {n}",
        "smc.up": "Arriba",
        "space": "Espacio",
        "speed": "Velocidad",
        "speed.fast": "Rápida",
        "speed.medium": "Media",
        "speed.slow": "Lenta (recomendada)",
        "speed.superFast": "Muy rápida",
        "speed_note": "Cuánto tarda un giro en aplicarse.",
        "status": "Estado",
        "status.connected": "Conectada",
        "status.disconnected": "Desconectada",
        "status.off": "Apagada",
        "tab.about": "Acerca de",
        "tab.boards": "Placas",
        "tab.general": "General",
        "tool_failed": "{tool} falló ({code}).",
        "up_to_date": "¡Estás al día!",
        "update_available": "¡Actualización disponible!",
        "update_complete": "¡Actualización completada!",
        "update_failed": "No se pudo instalar la actualización",
        "update_now": "Instalar ahora",
        "update_question": "Tienes la {version}. ¿Actualizar ahora?",
        "updating_to": "Actualizando TheeJ a {version}",
        "version": "Versión {version}",
        "view.draw": "Dibujo",
        "view.list": "Lista",
        "website": "Sitio web",
        "weekly": "Cada semana",
        "wizard.count": "{n} de {of}",
        "wizard.done": "Todos los controles encontrados. Pulsa Terminar para guardarlos.",
        "wizard.find": "Vuelve a poner {name} al 0 %.",
        "wizard.full": "Ahora pon cada mando y fader al 100 % y pulsa Siguiente.",
        "wizard.mismatch": "Era otro botón. Pulsa {name} tres veces.",
        "wizard.nothing": "Nada se movió entre el 0 % y el 100 %.",
        "wizard.press": "Pulsa {name} tres veces.",
        "wizard.redo": "Empezar de nuevo",
        "wizard.step": "{i} de {n}",
        "wizard.title": "Calibrar {name}",
        "wizard.unswept": "Ese no se movió entre el 0 % y el 100 %. Pulsa Empezar de nuevo.",
        "wizard.waiting": "Esperando a que {name} se conecte.",
        "wizard.wrong": "Ese es {other}. Mueve {name}.",
        "wizard.zero": "Pon cada mando y fader al 0 % y pulsa Siguiente.",
        "wrong_download": "La descarga no es TheeJ {version}.",
    ]
}
