// Español. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let es: [String: String] = [
        "about": "Acerca de TheeJ",
        "add_knob": "Añadir un control",
        "add_profile": "Añadir un perfil",
        "applications_only": "TheeJ solo se actualiza cuando se ejecuta desde la carpeta Aplicaciones.",
        "audio_text": "Para ajustar el volumen de una app, TheeJ reproduce el sonido de esa app al nivel del control, y macOS lo considera una grabación. Permite TheeJ en «Grabación de pantalla y audio del sistema», dentro de «Privacidad y seguridad», y después cierra TheeJ y vuelve a abrirlo.",
        "audio_title": "TheeJ aún no puede ajustar el volumen de las apps",
        "auto": "Buscar automáticamente",
        "available": "TheeJ {version} está disponible",
        "by": "Por",
        "cal.all_found": "Todos los controles encontrados",
        "cal.all_found_text": "Tu placa envía {n} valores y cada uno ya tiene su control, así que están todos. Haz clic en Terminar para elegir qué hacen.",
        "cal.finish_later": "Terminar se detiene aquí y lo deja para más tarde.",
        "cal.hold": "Tus controles no hacen nada hasta que termines.",
        "cal.move": "Mueve el control {letter} de un extremo al otro.",
        "cal.move_first": "Mueve el control {letter} de un extremo al otro, para que TheeJ sepa cuál es cada control. Después, cada control se gira durante {n} segundos, lo que limpia uno que salta.",
        "cal.no_knob": "Si no tienes un control {letter}, haz clic en Terminar.",
        "cal.paused": "En pausa. {left}. Sigue girando el control {letter}.",
        "cal.skip_keeps": "Ya está configurado, así que Omitir lo deja como está.",
        "cal.turn": "Encontrado. Ahora gíralo de un lado a otro, de un extremo al otro, durante {n} segundos. El tiempo solo corre mientras gira. Omítelo si no necesita limpieza.",
        "cal.waiting_board": "Esperando a que se conecte la placa",
        "cal.waiting_knob": "Esperando a que se mueva el control {letter}",
        "cal.wrong": "Ese es el control {wrong}. Mueve el control {letter}.",
        "calibrate": "Calibrar",
        "calibration_title": "Calibración de TheeJ",
        "cancel": "Cancelar",
        "check": "Buscar actualizaciones…",
        "check_connection": "Comprueba tu conexión e inténtalo de nuevo.",
        "check_failed": "No se pudieron buscar actualizaciones",
        "checking_signature": "Comprobando la firma…",
        "choose": "Elegir",
        "choose_language": "Elige tu idioma",
        "clear": "Borrar",
        "click_to_update": "Tienes la {version}. Haz clic para actualizar.",
        "close": "Cerrar",
        "connected": "Conectado: {port}",
        "continue": "Continuar",
        "daily": "Cada día",
        "default_profile": "Predeterminado",
        "dock": "Mantener en el Dock",
        "dock_restart": "Reiniciar el Dock",
        "dock_restart_text": "Para cambiar esto, macOS tiene que reiniciar el Dock. La pantalla y la barra de menús parpadearán un momento.",
        "dock_restart_title": "¿Reiniciar el Dock?",
        "download": "Descargar",
        "download_failed": "La descarga falló.",
        "downloading": "Descargando la versión {version}…",
        "finish": "Terminar",
        "hide_icon": "Ocultar el icono de la barra de menús",
        "hide_icon_note": "Abre TheeJ de nuevo para volver aquí.",
        "icon": "Icono",
        "icon.app": "Icono de la app",
        "icon.dial": "Dial",
        "icon.mixer": "Mezclador",
        "inspired_by": "Inspirado en",
        "install_now": "Instalar la versión {version} ahora",
        "installed": "La versión {version} está instalada.",
        "installing": "Instalando…",
        "invert": "Invertir controles",
        "invert_note": "Para potenciómetros cableados al revés.",
        "job.brightness": "Brillo de la pantalla {n}",
        "job.builtin_brightness": "Brillo de la pantalla integrada",
        "job.builtin_contrast": "Contraste de la pantalla integrada",
        "job.builtin_keyboard": "Luz del teclado integrado",
        "job.contrast": "Contraste de la pantalla {n}",
        "job.external_keyboard": "Luz del teclado externo",
        "job.master": "Volumen general",
        "job.microphone": "Volumen del micrófono",
        "job.night_shift": "Calidez de Night Shift",
        "job.nothing": "Nada",
        "job.zoom": "Zoom de pantalla",
        "jobs_note": "Marca una o varias funciones por control, para este perfil.",
        "knob": "Control {letter}",
        "knobs": "Controles",
        "knobs_found.one": "{n} control encontrado",
        "knobs_found.other": "{n} controles encontrados",
        "language": "Idioma",
        "language_note": "Puedes cambiarlo más tarde en Ajustes o en el menú.",
        "later": "Más tarde",
        "login": "Abrir al iniciar sesión",
        "m1ddc.note": "Para el brillo y el contraste de pantallas externas",
        "m1ddc.installed": "Instalado",
        "m1ddc.missing": "No instalado",
        "m1ddc.install": "Instalar",
        "m1ddc.refresh": "Actualizar",
        "m1ddc.support": "Soporte:",
        "made_by": "Hecho por",
        "menu_bar": "Barra de menús",
        "name": "Nombre",
        "needs_calibration": "Necesita calibración",
        "never": "Nunca",
        "newest": "TheeJ {version} es la versión más reciente disponible.",
        "next_profile": "Perfil siguiente",
        "no_knobs": "No hay controles. Calibrar los encuentra, o pulsa + para añadir uno.",
        "not_connected": "Sin conexión",
        "not_signed": "La descarga no está firmada por Zolfer Figueiredo.",
        "now_using": "Ahora usas TheeJ {version}, la versión más reciente disponible.",
        "ok": "OK",
        "open_settings": "Abrir Ajustes del Sistema",
        "other": "Otra…",
        "press_shortcut": "Pulsa el atajo",
        "previous_profile": "Perfil anterior",
        "profile": "Perfil",
        "profile_list": "Lista de perfiles",
        "profile_n": "Perfil {n}",
        "profiles": "Perfiles",
        "quit": "Salir de TheeJ",
        "reconnect": "Reconectar",
        "record_shortcut": "Grabar atajo",
        "remove": "Eliminar",
        "remove_knob": "Eliminar el último control",
        "remove_knob_info": "Lo que hace en todos los perfiles se elimina con él.",
        "remove_knob_q": "¿Eliminar el control {letter}?",
        "remove_named": "¿Eliminar «{name}»?",
        "remove_profile": "Eliminar este perfil",
        "remove_profile_info": "Sus funciones y su atajo se eliminan con él.",
        "remove_shortcut": "Eliminar atajo",
        "remove_this_profile": "¿Eliminar este perfil?",
        "reopen": "Volver a abrir",
        "reopen_failed": "No se pudo volver a abrir: {error} Sal de la app y ábrela tú.",
        "save": "Guardar",
        "seconds_left.one": "Queda {n} segundo",
        "seconds_left.other": "Quedan {n} segundos",
        "section.apps": "Apps",
        "section.brightness": "Brillo",
        "section.contrast": "Contraste",
        "section.keyboard": "Luz del teclado",
        "section.night_shift": "Night Shift",
        "section.volume": "Volumen",
        "section.zoom": "Zoom",
        "sensitivity": "Sensibilidad",
        "settings": "Ajustes",
        "short.builtin": "Integrado",
        "short.builtin_display": "Pantalla integrada",
        "short.external": "Externo",
        "short.screen": "Pantalla {n}",
        "short.warmth": "Calidez",
        "shortcut": "Atajo",
        "shortcut_tip": "Usa ⌘ o ⌃ con una tecla. Borrar lo elimina, Escape cancela.",
        "shortcuts": "Atajos",
        "show_data": "Mostrar datos abajo",
        "show_name": "Mostrar el nombre del perfil",
        "skip": "Omitir",
        "space": "Espacio",
        "speed": "Velocidad",
        "speed.fast": "Rápida",
        "speed.medium": "Media",
        "speed.slow": "Lenta (recomendada)",
        "speed.superFast": "Muy rápida",
        "speed_note": "Cuánto tarda un giro en aplicarse.",
        "tab.about": "Acerca de",
        "tab.app": "Ajustes de la app",
        "tab.general": "General",
        "tool_failed": "{tool} falló ({code}).",
        "up_to_date": "¡Estás al día!",
        "update_available": "¡Actualización disponible!",
        "update_complete": "¡Actualización completada!",
        "update_failed": "No se pudo instalar la actualización",
        "update_now": "Instalar ahora",
        "update_question": "Tienes la {version}. ¿Actualizar ahora?",
        "updating_to": "Actualizando TheeJ a {version}",
        "version": "Versión {version}",
        "website": "Sitio web",
        "weekly": "Cada semana",
        "wrong_download": "La descarga no es TheeJ {version}.",
    ]
}
