// Français. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let fr: [String: String] = [
        "about": "À propos de TheeJ",
        "add_knob": "Ajouter un bouton",
        "add_profile": "Ajouter un profil",
        "applications_only": "TheeJ ne se met à jour que lorsqu’il est lancé depuis le dossier Applications.",
        "audio_text": "Pour régler le volume d’une app, TheeJ rejoue le son de cette app au niveau du bouton, ce que macOS considère comme un enregistrement. Autorisez TheeJ dans « Enregistrement de l’écran et de l’audio système », sous « Confidentialité et sécurité », puis quittez TheeJ et rouvrez-le.",
        "audio_title": "TheeJ ne peut pas encore régler le volume des apps",
        "auto": "Vérifier automatiquement",
        "available": "TheeJ {version} est disponible",
        "by": "Par",
        "cal.all_found": "Tous les boutons sont trouvés",
        "cal.all_found_text": "Votre carte envoie {n} valeurs et chacune a maintenant son bouton, ils y sont donc tous. Cliquez sur Terminer pour choisir ce qu’ils font.",
        "cal.finish_later": "Terminer s’arrête ici et le laisse pour plus tard.",
        "cal.hold": "Vos boutons n’agissent pas tant que vous n’avez pas terminé.",
        "cal.move": "Tournez le bouton {letter} d’une butée à l’autre.",
        "cal.move_first": "Tournez le bouton {letter} d’une butée à l’autre, pour que TheeJ sache quel bouton est lequel. Chaque bouton est ensuite tourné pendant {n} secondes, ce qui nettoie un bouton capricieux.",
        "cal.no_knob": "Si vous n’avez pas de bouton {letter}, cliquez sur Terminer.",
        "cal.paused": "En pause, {left}. Continuez à tourner le bouton {letter}.",
        "cal.skip_keeps": "Il est déjà configuré, donc Ignorer le laisse tel quel.",
        "cal.turn": "Trouvé. Tournez-le maintenant dans les deux sens, d’une butée à l’autre, pendant {n} secondes. Le temps ne s’écoule que pendant la rotation. Ignorez cette étape s’il n’a pas besoin d’être nettoyé.",
        "cal.waiting_board": "En attente de la connexion de la carte",
        "cal.waiting_knob": "En attente d’un mouvement du bouton {letter}",
        "cal.wrong": "C’est le bouton {wrong}. Tournez plutôt le bouton {letter}.",
        "calibrate": "Calibrer",
        "calibration_title": "Calibrage de TheeJ",
        "cancel": "Annuler",
        "check": "Rechercher les mises à jour…",
        "check_connection": "Vérifiez votre connexion et réessayez.",
        "check_failed": "Impossible de rechercher les mises à jour",
        "checking_signature": "Vérification de la signature…",
        "choose": "Choisir",
        "choose_language": "Choisissez votre langue",
        "click_to_update": "Vous avez la {version}. Cliquez pour mettre à jour.",
        "connected": "Connecté : {port}",
        "continue": "Continuer",
        "daily": "Chaque jour",
        "default_profile": "Par défaut",
        "dock": "Garder dans le Dock",
        "download": "Télécharger",
        "download_failed": "Le téléchargement a échoué.",
        "downloading": "Téléchargement de la version {version}…",
        "finish": "Terminer",
        "hide_icon": "Masquer l’icône de la barre des menus",
        "hide_icon_note": "Ouvrez TheeJ à nouveau pour revenir ici.",
        "icon": "Icône",
        "icon.app": "Icône de l’app",
        "icon.dial": "Molette",
        "icon.mixer": "Table de mixage",
        "inspired_by": "Inspiré de",
        "install_now": "Installer la version {version} maintenant",
        "installed": "La version {version} est installée.",
        "installing": "Installation…",
        "invert": "Inverser les boutons",
        "invert_note": "Pour les potentiomètres câblés à l’envers.",
        "job.brightness": "Luminosité de l’écran {n}",
        "job.builtin_brightness": "Luminosité de l’écran intégré",
        "job.builtin_contrast": "Contraste de l’écran intégré",
        "job.builtin_keyboard": "Rétroéclairage du clavier intégré",
        "job.contrast": "Contraste de l’écran {n}",
        "job.external_keyboard": "Rétroéclairage du clavier externe",
        "job.master": "Volume général",
        "job.microphone": "Volume du micro",
        "job.night_shift": "Chaleur de Night Shift",
        "job.nothing": "Rien",
        "jobs_note": "Cochez une ou plusieurs fonctions par bouton de ce profil.",
        "knob": "Bouton {letter}",
        "knobs": "Boutons",
        "knobs_found.one": "{n} bouton trouvé",
        "knobs_found.other": "{n} boutons trouvés",
        "language": "Langue",
        "language_note": "Vous pourrez la changer plus tard dans Réglages ou dans le menu.",
        "later": "Plus tard",
        "login": "Ouvrir à la connexion",
        "m1ddc.note": "Pour la luminosité et le contraste des écrans externes",
        "m1ddc.installed": "Installé",
        "m1ddc.missing": "Non installé",
        "m1ddc.install": "Installer",
        "m1ddc.refresh": "Actualiser",
        "m1ddc.support": "Assistance :",
        "made_by": "Créé par",
        "menu_bar": "Barre des menus",
        "name": "Nom",
        "needs_calibration": "À calibrer",
        "never": "Jamais",
        "newest": "TheeJ {version} est la version la plus récente.",
        "next_profile": "Profil suivant",
        "no_knobs": "Aucun bouton. Calibrer les trouve, ou appuyez sur + pour en ajouter un.",
        "not_connected": "Non connecté",
        "not_signed": "Le téléchargement n’est pas signé par Zolfer Figueiredo.",
        "now_using": "Vous utilisez maintenant TheeJ {version}, la version la plus récente.",
        "ok": "OK",
        "open_settings": "Ouvrir Réglages Système",
        "other": "Autre…",
        "press_shortcut": "Tapez le raccourci",
        "previous_profile": "Profil précédent",
        "profile": "Profil",
        "profile_list": "Liste des profils",
        "profile_n": "Profil {n}",
        "profiles": "Profils",
        "quit": "Quitter TheeJ",
        "reconnect": "Reconnecter",
        "record_shortcut": "Définir un raccourci",
        "remove": "Supprimer",
        "remove_knob": "Supprimer le dernier bouton",
        "remove_knob_info": "Ce qu’il fait dans chaque profil est supprimé avec lui.",
        "remove_knob_q": "Supprimer le bouton {letter} ?",
        "remove_named": "Supprimer « {name} » ?",
        "remove_profile": "Supprimer ce profil",
        "remove_profile_info": "Ses fonctions et son raccourci sont supprimés avec lui.",
        "remove_shortcut": "Supprimer le raccourci",
        "remove_this_profile": "Supprimer ce profil ?",
        "reopen": "Rouvrir",
        "reopen_failed": "Impossible de rouvrir : {error} Quittez l’app et ouvrez-la vous-même.",
        "save": "Enregistrer",
        "seconds_left.one": "{n} seconde restante",
        "seconds_left.other": "{n} secondes restantes",
        "section.apps": "Apps",
        "section.brightness": "Luminosité",
        "section.contrast": "Contraste",
        "section.keyboard": "Rétroéclairage du clavier",
        "section.night_shift": "Night Shift",
        "section.volume": "Volume",
        "sensitivity": "Sensibilité",
        "settings": "Réglages",
        "short.builtin": "Intégré",
        "short.builtin_display": "Écran intégré",
        "short.external": "Externe",
        "short.screen": "Écran {n}",
        "short.warmth": "Chaleur",
        "shortcut": "Raccourci",
        "shortcut_tip": "Utilisez ⌘ ou ⌃ avec une touche. Supprimer l’efface, Échap annule.",
        "shortcuts": "Raccourcis",
        "show_data": "Afficher les données ci-dessous",
        "show_name": "Afficher le nom du profil",
        "skip": "Ignorer",
        "space": "Espace",
        "speed": "Vitesse",
        "speed.fast": "Rapide",
        "speed.medium": "Moyenne",
        "speed.slow": "Lente (recommandée)",
        "speed.superFast": "Très rapide",
        "speed_note": "Délai avant qu’une rotation s’applique.",
        "tab.about": "À propos",
        "tab.app": "Réglages de l’app",
        "tab.general": "Général",
        "tool_failed": "{tool} a échoué ({code}).",
        "up_to_date": "Vous êtes à jour !",
        "update_available": "Mise à jour disponible !",
        "update_complete": "Mise à jour terminée !",
        "update_failed": "Impossible d’installer la mise à jour",
        "update_now": "Mettre à jour",
        "update_question": "Vous avez la {version}. Mettre à jour maintenant ?",
        "updating_to": "Mise à jour de TheeJ vers {version}",
        "version": "Version {version}",
        "website": "Site web",
        "weekly": "Chaque semaine",
        "wrong_download": "Le téléchargement n’est pas TheeJ {version}.",
    ]
}
