// Français. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let fr: [String: String] = [
        "about": "À propos de TheeJ",
        "action.close_app": "Fermer une app",
        "action.go_profile": "Aller à {name}",
        "action.group.apps": "Apps",
        "action.group.fkeys": "Touches de fonction",
        "action.group.knobs": "Boutons",
        "action.group.media": "Multimédia",
        "action.group.system": "Système",
        "action.keys": "Appuyer sur un raccourci",
        "action.lights_off": "Éteindre l'éclairage des boutons",
        "action.lights_on": "Allumer l'éclairage des boutons",
        "action.lock": "Verrouiller le Mac",
        "action.mute": "Couper {name}",
        "action.mute_all": "Couper tout le son",
        "action.mute_mic": "Couper le micro",
        "action.next_lights": "Éclairage des boutons suivant",
        "action.next_track": "Piste suivante",
        "action.night_light": "Night Shift oui/non",
        "action.open_app": "Ouvrir une app",
        "action.open_settings": "Ouvrir les Réglages",
        "action.open_url": "Ouvrir un site web",
        "action.pause": "Pause",
        "action.play": "Lecture",
        "action.play_pause": "Lecture/pause",
        "action.previous_lights": "Éclairage des boutons précédent",
        "action.previous_track": "Piste précédente",
        "action.screens_off": "Éteindre les écrans",
        "action.sleep": "Mettre en veille",
        "action.volume_down": "Volume -",
        "action.volume_up": "Volume +",
        "add.add": "Ajouter",
        "add.name_hint": "Bureau",
        "add.next": "Suivant",
        "add.title": "Ajouter un boîtier",
        "add.type_note.diy": "Un Arduino qui envoie ses boutons par USB, comme celui de deej.",
        "add.type_note.midi": "Tout autre contrôleur MIDI. Vous montrez à TheeJ quelle commande est laquelle.",
        "add.type_note.smc": "Un M-VAVE SMC-Mixer. Ses commandes sont connues, il n'a pas besoin de calibrage.",
        "add_profile": "Ajouter un profil",
        "applications_only": "TheeJ ne se met à jour que lorsqu’il est lancé depuis le dossier Applications.",
        "apply": "Appliquer",
        "audio_text": "Pour régler le volume d’une app, TheeJ rejoue le son de cette app au niveau du bouton, ce que macOS considère comme un enregistrement. Autorisez TheeJ dans « Enregistrement de l’écran et de l’audio système », sous « Confidentialité et sécurité », puis quittez TheeJ et rouvrez-le.",
        "audio_title": "TheeJ ne peut pas encore régler le volume des apps",
        "auto": "Vérifier automatiquement",
        "available": "TheeJ {version} est disponible",
        "baud_note": "Doit correspondre à Serial.begin() dans le sketch de votre carte.",
        "baud_rate": "Débit (bauds)",
        "board.button": "Touche {letter}",
        "board.empty": "Ce boîtier n’a aucune commande.",
        "board.fader": "Fader {letter}",
        "board.hint": "Bougez ou appuyez sur une commande du boîtier, ou cliquez dessus ici, pour choisir ce qu’elle fait.",
        "boards.add": "Ajouter un boîtier",
        "boards.none": "Aucun boîtier pour l'instant.",
        "boards.none_connected": "Aucun boîtier n’est connecté.",
        "boards.on": "{name} allumé",
        "boards.set_up": "Configurer les boîtiers",
        "boards.settings": "Réglages du boîtier",
        "boards.settings_of": "Réglages de {name}",
        "boards.title": "Boîtiers",
        "by": "Par",
        "calibrate": "Calibrer",
        "cancel": "Annuler",
        "check": "Rechercher les mises à jour…",
        "check_connection": "Vérifiez votre connexion et réessayez.",
        "check_failed": "Impossible de rechercher les mises à jour",
        "checking_signature": "Vérification de la signature…",
        "choose": "Choisir",
        "choose_language": "Choisissez votre langue",
        "clear": "Effacer",
        "click_to_update": "Vous avez la {version}. Cliquez pour mettre à jour.",
        "close": "Fermer",
        "connected": "Connecté : {port}",
        "continue": "Continuer",
        "daily": "Chaque jour",
        "default_profile": "Par défaut",
        "device.pick_input": "Choisir une entrée MIDI",
        "device.remove": "Retirer le boîtier",
        "device.remove_info": "Ses profils et son calibrage partent avec lui.",
        "device.type": "Type",
        "device.type.diy": "Fait maison (Arduino)",
        "device.type.midi": "Autre MIDI",
        "device.type.smc": "SMC-Mixer",
        "device.used_by": "{port} (utilisé par {board})",
        "dock": "Garder dans le Dock",
        "dock_restart": "Redémarrer le Dock",
        "dock_restart_text": "Pour changer cela, macOS doit redémarrer le Dock. L’écran et la barre des menus clignoteront un instant.",
        "dock_restart_title": "Redémarrer le Dock ?",
        "download": "Télécharger",
        "download_failed": "Le téléchargement a échoué.",
        "downloading": "Téléchargement de la version {version}…",
        "finish": "Terminer",
        "general.app": "Application",
        "hide_icon": "Masquer l’icône de la barre des menus",
        "hide_icon_note": "Ouvrez TheeJ à nouveau pour revenir ici.",
        "icon": "Icône",
        "icon.app": "Icône de l’app",
        "icon.dial": "Molette",
        "icon.mixer": "Table de mixage",
        "inspired_by": "Inspiré de",
        "install_now": "Installer la version {version} maintenant",
        "installed": "La version {version} est installée.",
        "installing": "Installation…",
        "job.brightness": "Luminosité de l’écran {n}",
        "job.builtin_brightness": "Luminosité de l’écran intégré",
        "job.builtin_contrast": "Contraste de l’écran intégré",
        "job.builtin_keyboard": "Rétroéclairage du clavier intégré",
        "job.contrast": "Contraste de l’écran {n}",
        "job.empty": "Vide",
        "job.external_keyboard": "Rétroéclairage du clavier externe",
        "job.master": "Volume général",
        "job.microphone": "Volume du micro",
        "job.night_shift": "Chaleur de Night Shift",
        "job.nothing": "Rien",
        "job.zoom": "Zoom de l’écran",
        "knob": "Bouton {letter}",
        "knobs": "Boutons",
        "language": "Langue",
        "language_note": "Vous pourrez la changer plus tard dans Réglages ou dans le menu.",
        "later": "Plus tard",
        "lights": "Éclairage des boutons",
        "lights.ball": "Balle",
        "lights.bars": "Barres",
        "lights.blink": "Clignotement",
        "lights.bounce": "Rebond",
        "lights.breathe": "Respiration",
        "lights.chase": "Chenillard",
        "lights.checker": "Damier",
        "lights.clock": "Horloge binaire",
        "lights.comet": "Comète",
        "lights.eq": "Égaliseur",
        "lights.eq2": "Égaliseur 2",
        "lights.eqgame": "Égaliseur gaming",
        "lights.explode": "Explosion",
        "lights.fill": "Remplissage",
        "lights.fire": "Feu",
        "lights.heartbeat": "Battement de cœur",
        "lights.helix": "Hélice",
        "lights.matrix": "Matrix",
        "lights.off": "Éteint",
        "lights.on": "Allumé",
        "lights.orbit": "Orbite",
        "lights.rain": "Pluie",
        "lights.random": "Aléatoire",
        "lights.rise": "Montée",
        "lights.snake": "Serpent",
        "lights.sparkle": "Scintillement",
        "lights.stars": "Étoiles",
        "lights.wave": "Vague",
        "lights.zigzag": "Zigzag",
        "lights_note": "Les boutons appuyés et les sourdines restent allumés.",
        "list.buttons": "Boutons",
        "list.faders": "Faders",
        "list.none": "Aucun",
        "login": "Ouvrir à la connexion",
        "m1ddc.note": "Pour la luminosité et le contraste des écrans externes",
        "m1ddc.installed": "Installé",
        "m1ddc.missing": "Non installé",
        "m1ddc.install": "Installer",
        "m1ddc.refresh": "Actualiser",
        "m1ddc.support": "Assistance :",
        "made_by": "Créé par",
        "menu.board": "{name} : {status}",
        "mixer.fader": "Fader {n}",
        "mixer.knob": "Bouton {n}",
        "mixer_port_note": "Choisissez votre table de mixage MIDI pour l’utiliser à côté de la carte.",
        "name": "Nom",
        "needs_calibration": "À calibrer",
        "never": "Jamais",
        "newest": "TheeJ {version} est la version la plus récente.",
        "next_profile": "Profil suivant",
        "not_connected": "Non connecté",
        "not_signed": "Le téléchargement n’est pas signé par Zolfer Figueiredo.",
        "now_using": "Vous utilisez maintenant TheeJ {version}, la version la plus récente.",
        "ok": "OK",
        "on_windows": "Sous Windows ? Téléchargez",
        "open_settings": "Ouvrir Réglages Système",
        "other": "Autre…",
        "port": "Appareil",
        "port_auto": "Automatique",
        "port_busy": "{port} est utilisé par une autre app",
        "port_forced": "Fixé sur {port} au démarrage de TheeJ.",
        "port_note": "En automatique, TheeJ trouve votre carte tout seul.",
        "press_shortcut": "Tapez le raccourci",
        "previous_profile": "Profil précédent",
        "profile": "Profil",
        "profile.edit": "Modifier le profil…",
        "profile_list": "Liste des profils",
        "profile_n": "Profil {n}",
        "quit": "Quitter TheeJ",
        "reconnect": "Reconnecter",
        "record_shortcut": "Définir un raccourci",
        "refresh": "Actualiser",
        "remove": "Supprimer",
        "remove_named": "Supprimer « {name} » ?",
        "remove_profile": "Supprimer ce profil",
        "remove_profile_info": "Ses fonctions et son raccourci sont supprimés avec lui.",
        "remove_shortcut": "Supprimer le raccourci",
        "remove_this_profile": "Supprimer ce profil ?",
        "reopen": "Rouvrir",
        "reopen_failed": "Impossible de rouvrir : {error} Quittez l’app et ouvrez-la vous-même.",
        "save": "Enregistrer",
        "section.apps": "Apps",
        "section.brightness": "Luminosité",
        "section.contrast": "Contraste",
        "section.keyboard": "Rétroéclairage du clavier",
        "section.night_shift": "Night Shift",
        "section.volume": "Volume",
        "section.zoom": "Zoom",
        "settings": "Réglages",
        "short.builtin": "Intégré",
        "short.builtin_display": "Écran intégré",
        "short.external": "Externe",
        "short.screen": "Écran {n}",
        "short.warmth": "Chaleur",
        "shortcut": "Raccourci",
        "shortcut.also_used": "Aussi utilisé par {names}",
        "shortcut.clash": "Ce boîtier utilise déjà ce raccourci. Essayez-en un autre.",
        "shortcut.taken": "Une autre app utilise déjà ce raccourci. Essayez-en un autre.",
        "shortcut_tip": "Utilisez ⌘ ou ⌃ avec une touche. Supprimer l’efface, Échap annule.",
        "show_data": "Afficher les données ci-dessous",
        "show_name": "Afficher le nom du profil",
        "skip": "Ignorer",
        "smc.bank_left": "Banque précédente",
        "smc.bank_right": "Banque suivante",
        "smc.down": "Bas",
        "smc.hint": "Bougez ou appuyez sur une commande de la table de mixage, ou cliquez dessus ici, pour choisir ce qu’elle fait.",
        "smc.left": "Gauche",
        "smc.record": "Enregistrer",
        "smc.right": "Droite",
        "smc.square": "Carré {n}",
        "smc.up": "Haut",
        "space": "Espace",
        "speed": "Vitesse",
        "speed.fast": "Rapide",
        "speed.medium": "Moyenne",
        "speed.slow": "Lente (recommandée)",
        "speed.superFast": "Très rapide",
        "speed_note": "Délai avant qu’une rotation s’applique.",
        "status": "État",
        "status.connected": "Connecté",
        "status.disconnected": "Déconnecté",
        "status.off": "Éteint",
        "tab.about": "À propos",
        "tab.boards": "Boîtiers",
        "tab.general": "Général",
        "tool_failed": "{tool} a échoué ({code}).",
        "up_to_date": "Vous êtes à jour !",
        "update_available": "Mise à jour disponible !",
        "update_complete": "Mise à jour terminée !",
        "update_failed": "Impossible d’installer la mise à jour",
        "update_now": "Mettre à jour",
        "update_question": "Vous avez la {version}. Mettre à jour maintenant ?",
        "updating_to": "Mise à jour de TheeJ vers {version}",
        "version": "Version {version}",
        "view.draw": "Dessin",
        "view.list": "Liste",
        "website": "Site web",
        "weekly": "Chaque semaine",
        "wizard.count": "{n} sur {of}",
        "wizard.done": "Toutes les commandes sont trouvées. Appuyez sur Terminer pour les garder.",
        "wizard.find": "Remettez {name} à 0 %.",
        "wizard.full": "Mettez maintenant chaque bouton et fader à 100 %, puis appuyez sur Suivant.",
        "wizard.mismatch": "C'était un autre bouton. Appuyez trois fois sur {name}.",
        "wizard.nothing": "Rien n'a bougé entre 0 % et 100 %.",
        "wizard.press": "Appuyez trois fois sur {name}.",
        "wizard.redo": "Recommencer",
        "wizard.step": "{i} sur {n}",
        "wizard.title": "Calibrer {name}",
        "wizard.unswept": "Celui-ci n'a pas bougé entre 0 % et 100 %. Appuyez sur Recommencer.",
        "wizard.waiting": "En attente de la connexion de {name}.",
        "wizard.wrong": "C'est {other}. Déplacez plutôt {name}.",
        "wizard.zero": "Mettez chaque bouton et fader à 0 %, puis appuyez sur Suivant.",
        "wrong_download": "Le téléchargement n’est pas TheeJ {version}.",
    ]
}
