// Italiano. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let it: [String: String] = [
        "about": "Informazioni su TheeJ",
        "add_knob": "Aggiungi una manopola",
        "add_profile": "Aggiungi un profilo",
        "applications_only": "TheeJ si aggiorna da solo soltanto se viene eseguito dalla cartella Applicazioni.",
        "audio_text": "Per regolare il volume di un’app, TheeJ riproduce l’audio di quell’app al livello della manopola, cosa che macOS considera una registrazione. Consenti TheeJ in “Registrazione schermo e audio di sistema”, in “Privacy e sicurezza”, poi esci da TheeJ e riaprilo.",
        "audio_title": "TheeJ non può ancora regolare il volume delle app",
        "auto": "Cerca automaticamente",
        "available": "TheeJ {version} è disponibile",
        "by": "Di",
        "cal.all_found": "Tutte le manopole trovate",
        "cal.all_found_text": "La tua scheda invia {n} valori e ognuno ha ora la sua manopola, quindi ci sono tutte. Fai clic su Fine per scegliere cosa fanno.",
        "cal.finish_later": "Fine si ferma qui e la lascia per dopo.",
        "cal.hold": "Le tue manopole non fanno nulla finché non hai finito.",
        "cal.move": "Muovi la manopola {letter} da un estremo all’altro.",
        "cal.move_first": "Muovi la manopola {letter} da un estremo all’altro, così TheeJ capisce qual è ciascuna manopola. Poi ogni manopola viene girata per {n} secondi, il che ripulisce una manopola ballerina.",
        "cal.no_knob": "Se non hai una manopola {letter}, fai clic su Fine.",
        "cal.paused": "In pausa. {left}. Continua a girare la manopola {letter}.",
        "cal.skip_keeps": "È già configurata, quindi Salta la lascia com’è.",
        "cal.turn": "Trovata. Ora girala avanti e indietro, da un estremo all’altro, per {n} secondi. Il tempo scorre solo mentre gira. Salta se non ha bisogno di pulizia.",
        "cal.waiting_board": "In attesa che la scheda si colleghi",
        "cal.waiting_knob": "In attesa che la manopola {letter} si muova",
        "cal.wrong": "Quella è la manopola {wrong}. Muovi invece la manopola {letter}.",
        "calibrate": "Calibra",
        "calibration_title": "Calibrazione di TheeJ",
        "cancel": "Annulla",
        "check": "Cerca aggiornamenti…",
        "check_connection": "Controlla la connessione e riprova.",
        "check_failed": "Impossibile cercare aggiornamenti",
        "checking_signature": "Verifica della firma…",
        "choose": "Scegli",
        "choose_language": "Scegli la tua lingua",
        "click_to_update": "Hai la {version}. Fai clic per aggiornare.",
        "close": "Chiudi",
        "connected": "Connesso: {port}",
        "continue": "Continua",
        "daily": "Ogni giorno",
        "default_profile": "Predefinito",
        "dock": "Mantieni nel Dock",
        "dock_restart": "Riavvia il Dock",
        "dock_restart_text": "Per cambiarlo, macOS deve riavviare il Dock. Lo schermo e la barra dei menu lampeggeranno per un attimo.",
        "dock_restart_title": "Riavviare il Dock?",
        "download": "Scarica",
        "download_failed": "Download non riuscito.",
        "downloading": "Download della versione {version}…",
        "finish": "Fine",
        "hide_icon": "Nascondi l’icona nella barra dei menu",
        "hide_icon_note": "Apri di nuovo TheeJ per tornare qui.",
        "icon": "Icona",
        "icon.app": "Icona dell’app",
        "icon.dial": "Manopola",
        "icon.mixer": "Mixer",
        "inspired_by": "Ispirato a",
        "install_now": "Installa ora la versione {version}",
        "installed": "La versione {version} è installata.",
        "installing": "Installazione…",
        "invert": "Inverti le manopole",
        "invert_note": "Per potenziometri cablati al contrario.",
        "job.brightness": "Luminosità dello schermo {n}",
        "job.builtin_brightness": "Luminosità dello schermo integrato",
        "job.builtin_contrast": "Contrasto dello schermo integrato",
        "job.builtin_keyboard": "Retroilluminazione della tastiera integrata",
        "job.contrast": "Contrasto dello schermo {n}",
        "job.external_keyboard": "Retroilluminazione della tastiera esterna",
        "job.master": "Volume principale",
        "job.microphone": "Volume del microfono",
        "job.night_shift": "Calore di Night Shift",
        "job.nothing": "Niente",
        "job.zoom": "Zoom dello schermo",
        "jobs_note": "Spunta uno o più compiti per manopola, per questo profilo.",
        "knob": "Manopola {letter}",
        "knobs": "Manopole",
        "knobs_found.one": "{n} manopola trovata",
        "knobs_found.other": "{n} manopole trovate",
        "language": "Lingua",
        "language_note": "Puoi cambiarla più tardi in Impostazioni o nel menu.",
        "later": "Più tardi",
        "login": "Apri all’accesso",
        "m1ddc.note": "Per luminosità e contrasto degli schermi esterni",
        "m1ddc.installed": "Installato",
        "m1ddc.missing": "Non installato",
        "m1ddc.install": "Installa",
        "m1ddc.refresh": "Aggiorna",
        "m1ddc.support": "Supporto:",
        "made_by": "Creato da",
        "menu_bar": "Barra dei menu",
        "name": "Nome",
        "needs_calibration": "Da calibrare",
        "never": "Mai",
        "newest": "TheeJ {version} è la versione più recente disponibile.",
        "next_profile": "Profilo successivo",
        "no_knobs": "Nessuna manopola. Calibra le trova, oppure premi + per aggiungerne una.",
        "not_connected": "Non connesso",
        "not_signed": "Il download non è firmato da Zolfer Figueiredo.",
        "now_using": "Ora stai usando TheeJ {version}, la versione più recente disponibile.",
        "ok": "OK",
        "open_settings": "Apri Impostazioni di Sistema",
        "other": "Altra…",
        "press_shortcut": "Premi i tasti",
        "previous_profile": "Profilo precedente",
        "profile": "Profilo",
        "profile_list": "Elenco dei profili",
        "profile_n": "Profilo {n}",
        "profiles": "Profili",
        "quit": "Esci da TheeJ",
        "reconnect": "Riconnetti",
        "record_shortcut": "Nuova abbreviazione",
        "remove": "Rimuovi",
        "remove_knob": "Rimuovi l’ultima manopola",
        "remove_knob_info": "Ciò che fa in ogni profilo viene rimosso insieme alla manopola.",
        "remove_knob_q": "Rimuovere la manopola {letter}?",
        "remove_named": "Rimuovere “{name}”?",
        "remove_profile": "Rimuovi questo profilo",
        "remove_profile_info": "I suoi compiti e la sua abbreviazione vengono rimossi insieme al profilo.",
        "remove_shortcut": "Rimuovi abbreviazione",
        "remove_this_profile": "Rimuovere questo profilo?",
        "reopen": "Riapri",
        "reopen_failed": "Impossibile riaprire: {error} Esci dall’app e riaprila tu.",
        "save": "Salva",
        "seconds_left.one": "Manca {n} secondo",
        "seconds_left.other": "Mancano {n} secondi",
        "section.apps": "App",
        "section.brightness": "Luminosità",
        "section.contrast": "Contrasto",
        "section.keyboard": "Retroilluminazione tastiera",
        "section.night_shift": "Night Shift",
        "section.volume": "Volume",
        "section.zoom": "Zoom",
        "sensitivity": "Sensibilità",
        "settings": "Impostazioni",
        "short.builtin": "Integrata",
        "short.builtin_display": "Schermo integrato",
        "short.external": "Esterna",
        "short.screen": "Schermo {n}",
        "short.warmth": "Calore",
        "shortcut": "Abbreviazione",
        "shortcut_tip": "Usa ⌘ o ⌃ con un tasto. Cancella la elimina, Esc annulla.",
        "shortcuts": "Abbreviazioni",
        "show_data": "Mostra i dati qui sotto",
        "show_name": "Mostra il nome del profilo",
        "skip": "Salta",
        "space": "Spazio",
        "speed": "Velocità",
        "speed.fast": "Veloce",
        "speed.medium": "Media",
        "speed.slow": "Lenta (consigliata)",
        "speed.superFast": "Velocissima",
        "speed_note": "Quanto presto agisce una rotazione.",
        "tab.about": "Informazioni",
        "tab.app": "Impostazioni app",
        "tab.general": "Generali",
        "tool_failed": "{tool} non riuscito ({code}).",
        "up_to_date": "Hai già l’ultima versione!",
        "update_available": "Aggiornamento disponibile!",
        "update_complete": "Aggiornamento completato!",
        "update_failed": "Impossibile installare l’aggiornamento",
        "update_now": "Installa ora",
        "update_question": "Hai la {version}. Aggiornare ora?",
        "updating_to": "Aggiornamento di TheeJ alla {version}",
        "version": "Versione {version}",
        "website": "Sito web",
        "weekly": "Ogni settimana",
        "wrong_download": "Il download non è TheeJ {version}.",
    ]
}
