// 日本語. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let ja: [String: String] = [
        "about": "TheeJ について",
        "action.close_app": "アプリを閉じる",
        "action.go_profile": "{name} に切り替え",
        "action.group.apps": "アプリ",
        "action.group.fkeys": "ファンクションキー",
        "action.group.knobs": "ノブ",
        "action.group.media": "メディア",
        "action.group.system": "システム",
        "action.keys": "ショートカットを押す",
        "action.lights_off": "ボタンのライトをオフ",
        "action.lights_on": "ボタンのライトをオン",
        "action.lock": "Mac をロック",
        "action.mute": "{name} をミュート",
        "action.mute_all": "すべての音をミュート",
        "action.mute_mic": "マイクをミュート",
        "action.next_lights": "次のボタンのライト",
        "action.next_track": "次のトラック",
        "action.night_light": "Night Shiftのオン/オフ",
        "action.open_app": "アプリを開く",
        "action.open_settings": "設定を開く",
        "action.open_url": "Web サイトを開く",
        "action.pause": "一時停止",
        "action.play": "再生",
        "action.play_pause": "再生/一時停止",
        "action.previous_lights": "前のボタンのライト",
        "action.previous_track": "前のトラック",
        "action.screens_off": "画面をオフにする",
        "action.sleep": "スリープ",
        "action.volume_down": "音量を下げる",
        "action.volume_up": "音量を上げる",
        "add.add": "追加",
        "add.name_hint": "デスク",
        "add.next": "次へ",
        "add.title": "ボードを追加",
        "add.type_note.diy": "deej のように、ノブの値を USB で送る Arduino。",
        "add.type_note.midi": "そのほかの MIDI コントローラー。どの操作部がどれかを TheeJ に教えます。",
        "add.type_note.smc": "M-VAVE SMC-Mixer。操作部はわかっているので、キャリブレーションは不要です。",
        "add_profile": "プロファイルを追加",
        "applications_only": "TheeJ は「アプリケーション」フォルダから実行しているときだけ自動でアップデートします。",
        "apply": "適用",
        "audio_text": "アプリの音量を設定するために、TheeJ はそのアプリの音をノブのレベルで再生し直します。macOS はこれを録音として扱います。「プライバシーとセキュリティ」の「画面収録とシステムオーディオ録音」で TheeJ を許可してから、TheeJ を終了してもう一度開いてください。",
        "audio_title": "TheeJ はまだアプリの音量を設定できません",
        "auto": "自動で確認",
        "available": "TheeJ {version} が利用できます",
        "baud_note": "ボードのスケッチの Serial.begin() と同じにしてください。",
        "baud_rate": "ボーレート",
        "board.button": "ボタン {letter}",
        "board.empty": "このボードには操作部がありません。",
        "board.fader": "フェーダー {letter}",
        "board.hint": "ボードの操作部を動かすか押す、またはここでクリックすると、その役割を選べます。",
        "boards.add": "ボードを追加",
        "boards.none": "ボードはまだありません。",
        "boards.none_connected": "接続されているボードはありません。",
        "boards.on": "{name} オン",
        "boards.set_up": "ボードを設定",
        "boards.settings": "ボードの設定",
        "boards.settings_of": "{name} の設定",
        "boards.title": "ボード",
        "by": "制作:",
        "calibrate": "キャリブレーション",
        "cancel": "キャンセル",
        "check": "アップデートを確認…",
        "check_connection": "接続を確認して、もう一度お試しください。",
        "check_failed": "アップデートを確認できませんでした",
        "checking_signature": "署名を確認中…",
        "choose": "選択",
        "choose_language": "言語を選択",
        "clear": "クリア",
        "click_to_update": "現在は {version} です。クリックしてアップデート。",
        "close": "閉じる",
        "connected": "接続済み: {port}",
        "continue": "続ける",
        "daily": "毎日",
        "default_profile": "デフォルト",
        "device.pick_input": "MIDI 入力を選択",
        "device.remove": "ボードを削除",
        "device.remove_info": "プロファイルとキャリブレーションも一緒に削除されます。",
        "device.type": "種類",
        "device.type.diy": "自作 (Arduino)",
        "device.type.midi": "ほかの MIDI",
        "device.type.smc": "SMC-Mixer",
        "device.used_by": "{port} ({board} が使用中)",
        "dock": "Dock に残す",
        "dock_restart": "Dock を再起動",
        "dock_restart_text": "変更するには、macOS が Dock を再起動する必要があります。画面とメニューバーが一瞬ちらつきます。",
        "dock_restart_title": "Dock を再起動しますか？",
        "download": "ダウンロード",
        "download_failed": "ダウンロードに失敗しました。",
        "downloading": "バージョン {version} をダウンロード中…",
        "finish": "完了",
        "general.app": "アプリ",
        "hide_icon": "メニューバーのアイコンを隠す",
        "hide_icon_note": "TheeJ をもう一度開くと、ここに戻れます。",
        "icon": "アイコン",
        "icon.app": "アプリアイコン",
        "icon.dial": "ダイヤル",
        "icon.mixer": "ミキサー",
        "inspired_by": "着想元:",
        "install_now": "バージョン {version} を今すぐインストール",
        "installed": "バージョン {version} をインストールしました。",
        "installing": "インストール中…",
        "job.brightness": "画面 {n} の輝度",
        "job.builtin_brightness": "内蔵ディスプレイの輝度",
        "job.builtin_contrast": "内蔵ディスプレイのコントラスト",
        "job.builtin_keyboard": "内蔵キーボードのバックライト",
        "job.contrast": "画面 {n} のコントラスト",
        "job.empty": "空",
        "job.external_keyboard": "外部キーボードのバックライト",
        "job.master": "マスター音量",
        "job.microphone": "マイク音量",
        "job.night_shift": "Night Shift 色温度",
        "job.nothing": "なし",
        "job.zoom": "画面のズーム",
        "knob": "ノブ {letter}",
        "knobs": "ノブ",
        "language": "言語",
        "language_note": "あとで設定またはメニューから変更できます。",
        "later": "あとで",
        "lights": "ボタンのライト",
        "lights.ball": "ボール",
        "lights.bars": "バー",
        "lights.blink": "点滅",
        "lights.bounce": "バウンス",
        "lights.breathe": "呼吸",
        "lights.chase": "チェイス",
        "lights.checker": "市松模様",
        "lights.clock": "2進時計",
        "lights.comet": "彗星",
        "lights.eq": "イコライザー",
        "lights.eq2": "イコライザー 2",
        "lights.eqgame": "ゲーム用イコライザー",
        "lights.explode": "爆発",
        "lights.fill": "フィル",
        "lights.fire": "炎",
        "lights.heartbeat": "鼓動",
        "lights.helix": "らせん",
        "lights.matrix": "マトリックス",
        "lights.off": "オフ",
        "lights.on": "オン",
        "lights.orbit": "周回",
        "lights.rain": "雨",
        "lights.random": "ランダム",
        "lights.rise": "上昇",
        "lights.snake": "ヘビ",
        "lights.sparkle": "きらめき",
        "lights.stars": "星",
        "lights.wave": "ウェーブ",
        "lights.zigzag": "ジグザグ",
        "lights_note": "押したボタンとミュートは引き続き点灯します。",
        "list.buttons": "ボタン",
        "list.faders": "フェーダー",
        "list.none": "なし",
        "login": "ログイン時に起動",
        "m1ddc.note": "外部画面の輝度とコントラストに使います",
        "m1ddc.installed": "インストール済み",
        "m1ddc.missing": "未インストール",
        "m1ddc.install": "インストール",
        "m1ddc.refresh": "再確認",
        "m1ddc.support": "サポート:",
        "made_by": "制作:",
        "menu.board": "{name}: {status}",
        "mixer.fader": "フェーダー {n}",
        "mixer.knob": "ノブ {n}",
        "mixer_port_note": "MIDI ミキサーを選ぶと、ボードと一緒に使えます。",
        "name": "名前",
        "needs_calibration": "キャリブレーションが必要",
        "never": "しない",
        "newest": "TheeJ {version} は現在入手できる最新バージョンです。",
        "next_profile": "次のプロファイル",
        "not_connected": "未接続",
        "not_signed": "ダウンロードしたファイルには Zolfer Figueiredo の署名がありません。",
        "now_using": "TheeJ {version} を使用中です。現在入手できる最新バージョンです。",
        "ok": "OK",
        "on_windows": "Windows 版:",
        "open_settings": "システム設定を開く",
        "other": "その他…",
        "port": "デバイス",
        "port_auto": "自動",
        "port_busy": "{port} は別のアプリが使用中です",
        "port_forced": "TheeJ の起動時に {port} に指定されています。",
        "port_note": "自動にすると、TheeJ がボードを見つけます。",
        "press_shortcut": "ショートカットを押す",
        "previous_profile": "前のプロファイル",
        "profile": "プロファイル",
        "profile.edit": "プロファイルを編集…",
        "profile_list": "プロファイル一覧",
        "profile_n": "プロファイル {n}",
        "quit": "TheeJ を終了",
        "reconnect": "再接続",
        "record_shortcut": "ショートカットを記録",
        "refresh": "更新",
        "remove": "削除",
        "remove_named": "“{name}”を削除しますか？",
        "remove_profile": "このプロファイルを削除",
        "remove_profile_info": "ノブの役割とショートカットも一緒に削除されます。",
        "remove_shortcut": "ショートカットを削除",
        "remove_this_profile": "このプロファイルを削除しますか？",
        "reopen": "開き直す",
        "reopen_failed": "開き直せませんでした: {error} アプリを終了して、自分で開いてください。",
        "save": "保存",
        "section.apps": "アプリ",
        "section.brightness": "輝度",
        "section.contrast": "コントラスト",
        "section.keyboard": "キーボードのバックライト",
        "section.night_shift": "Night Shift",
        "section.volume": "音量",
        "section.zoom": "ズーム",
        "settings": "設定",
        "short.builtin": "内蔵",
        "short.builtin_display": "内蔵ディスプレイ",
        "short.external": "外部",
        "short.screen": "画面 {n}",
        "short.warmth": "色温度",
        "shortcut": "ショートカット",
        "shortcut.also_used": "{names} でも使用中",
        "shortcut.clash": "このボードはこのショートカットを使用中です。別のキーを押してください。",
        "shortcut.taken": "ほかのアプリがこのショートカットを使用中です。別のキーを押してください。",
        "shortcut_tip": "⌘ または ⌃ とキーを組み合わせてください。Delete で消去、Escape でキャンセル。",
        "show_data": "下にデータを表示",
        "show_name": "プロファイル名を表示",
        "skip": "スキップ",
        "smc.bank_left": "前のバンク",
        "smc.bank_right": "次のバンク",
        "smc.down": "下",
        "smc.hint": "ミキサーの操作部を動かすか押す、またはここでクリックすると、その役割を選べます。",
        "smc.left": "左",
        "smc.record": "録音",
        "smc.right": "右",
        "smc.square": "四角 {n}",
        "smc.up": "上",
        "space": "スペース",
        "speed": "速度",
        "speed.fast": "速い",
        "speed.medium": "普通",
        "speed.slow": "遅い（推奨）",
        "speed.superFast": "とても速い",
        "speed_note": "回したあと、変更が反映されるまでの早さ。",
        "status": "状態",
        "status.connected": "接続済み",
        "status.disconnected": "未接続",
        "status.off": "オフ",
        "tab.about": "このアプリについて",
        "tab.boards": "ボード",
        "tab.general": "一般",
        "tool_failed": "{tool} が失敗しました（{code}）。",
        "up_to_date": "最新の状態です",
        "update_available": "アップデートがあります",
        "update_complete": "アップデート完了",
        "update_failed": "アップデートをインストールできませんでした",
        "update_now": "今すぐアップデート",
        "update_question": "現在は {version} です。今すぐアップデートしますか？",
        "updating_to": "TheeJ を {version} にアップデート中",
        "version": "バージョン {version}",
        "view.draw": "図",
        "view.list": "一覧",
        "website": "Web サイト",
        "weekly": "毎週",
        "wizard.count": "{n} / {of}",
        "wizard.done": "すべての操作部が見つかりました。保持するには完了を押してください。",
        "wizard.find": "{name} を 0% に戻してください。",
        "wizard.full": "次に、すべてのノブとフェーダーを 100% にして、「次へ」を押してください。",
        "wizard.mismatch": "別のボタンでした。{name} を 3 回押してください。",
        "wizard.nothing": "0% と 100% のあいだで何も動きませんでした。",
        "wizard.press": "{name} を 3 回押してください。",
        "wizard.redo": "やり直す",
        "wizard.step": "{i} / {n}",
        "wizard.title": "{name} をキャリブレーション",
        "wizard.unswept": "それは 0% と 100% のあいだで動いていません。「やり直す」を押してください。",
        "wizard.waiting": "{name} の接続を待っています。",
        "wizard.wrong": "それは {other} です。{name} を動かしてください。",
        "wizard.zero": "すべてのノブとフェーダーを 0% にして、「次へ」を押してください。",
        "wrong_download": "ダウンロードしたファイルは TheeJ {version} ではありません。",
    ]
}
