// 日本語. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let ja: [String: String] = [
        "about": "TheeJ について",
        "add_knob": "ノブを追加",
        "add_profile": "プロファイルを追加",
        "applications_only": "TheeJ は「アプリケーション」フォルダから実行しているときだけ自動でアップデートします。",
        "audio_text": "アプリの音量を設定するために、TheeJ はそのアプリの音をノブのレベルで再生し直します。macOS はこれを録音として扱います。「プライバシーとセキュリティ」の「画面収録とシステムオーディオ録音」で TheeJ を許可してから、TheeJ を終了してもう一度開いてください。",
        "audio_title": "TheeJ はまだアプリの音量を設定できません",
        "auto": "自動で確認",
        "available": "TheeJ {version} が利用できます",
        "by": "制作:",
        "cal.all_found": "すべてのノブが見つかりました",
        "cal.all_found_text": "ボードは {n} 個の値を送っていて、それぞれにノブが割り当てられたので、これで全部です。「完了」をクリックして、役割を選びます。",
        "cal.finish_later": "「完了」するとここで止まり、このノブはあとに回します。",
        "cal.hold": "完了するまで、ノブは何も操作しません。",
        "cal.move": "ノブ {letter} を端から端まで動かします。",
        "cal.move_first": "ノブ {letter} を端から端まで動かすと、TheeJ がどのノブかを判別できます。そのあと各ノブを {n} 秒間回して、暴れるノブをきれいにします。",
        "cal.no_knob": "ノブ {letter} がない場合は「完了」をクリックします。",
        "cal.paused": "一時停止中、{left}。ノブ {letter} を回し続けてください。",
        "cal.skip_keeps": "すでに設定済みなので、「スキップ」するとそのまま残ります。",
        "cal.turn": "見つかりました。今度は端から端まで、{n} 秒間、左右に回します。タイマーは回している間だけ進みます。クリーニングが不要ならスキップします。",
        "cal.waiting_board": "ボードの接続を待っています",
        "cal.waiting_knob": "ノブ {letter} が動くのを待っています",
        "cal.wrong": "それはノブ {wrong} です。ノブ {letter} を動かしてください。",
        "calibrate": "キャリブレーション",
        "calibration_title": "TheeJ キャリブレーション",
        "cancel": "キャンセル",
        "check": "アップデートを確認…",
        "check_connection": "接続を確認して、もう一度お試しください。",
        "check_failed": "アップデートを確認できませんでした",
        "checking_signature": "署名を確認中…",
        "choose": "選択",
        "choose_language": "言語を選択",
        "click_to_update": "現在は {version} です。クリックしてアップデート。",
        "connected": "接続済み: {port}",
        "continue": "続ける",
        "daily": "毎日",
        "default_profile": "デフォルト",
        "dock": "Dock に残す",
        "download": "ダウンロード",
        "download_failed": "ダウンロードに失敗しました。",
        "downloading": "バージョン {version} をダウンロード中…",
        "finish": "完了",
        "hide_icon": "メニューバーのアイコンを隠す",
        "hide_icon_note": "TheeJ をもう一度開くと、ここに戻れます。",
        "icon": "アイコン",
        "icon.app": "アプリアイコン",
        "icon.dial": "ダイヤル",
        "icon.mixer": "ミキサー",
        "inspired_by": "着想元:",
        "install_now": "バージョン {version} を今すぐインストール",
        "installed": "バージョン {version} をインストールしました。",
        "installing": "インストール中…",
        "invert": "ノブを反転",
        "invert_note": "ポットの配線が逆の場合に。",
        "job.brightness": "画面 {n} の輝度",
        "job.builtin_brightness": "内蔵ディスプレイの輝度",
        "job.builtin_contrast": "内蔵ディスプレイのコントラスト",
        "job.builtin_keyboard": "内蔵キーボードのバックライト",
        "job.contrast": "画面 {n} のコントラスト",
        "job.external_keyboard": "外部キーボードのバックライト",
        "job.master": "マスター音量",
        "job.microphone": "マイク音量",
        "job.night_shift": "Night Shift 色温度",
        "job.nothing": "なし",
        "jobs_note": "ノブごとに役割をひとつ以上チェックします。",
        "knob": "ノブ {letter}",
        "knobs": "ノブ",
        "knobs_found.other": "{n} 個のノブが見つかりました",
        "language": "言語",
        "language_note": "あとで設定またはメニューから変更できます。",
        "later": "あとで",
        "login": "ログイン時に起動",
        "m1ddc.note": "外部画面の輝度とコントラストに使います",
        "m1ddc.installed": "インストール済み",
        "m1ddc.missing": "未インストール",
        "m1ddc.install": "インストール",
        "m1ddc.refresh": "再確認",
        "m1ddc.support": "サポート:",
        "made_by": "制作:",
        "menu_bar": "メニューバー",
        "name": "名前",
        "needs_calibration": "キャリブレーションが必要",
        "never": "しない",
        "newest": "TheeJ {version} は現在入手できる最新バージョンです。",
        "next_profile": "次のプロファイル",
        "no_knobs": "ノブがありません。「キャリブレーション」で見つけるか、+ を押して追加します。",
        "not_connected": "未接続",
        "not_signed": "ダウンロードしたファイルには Zolfer Figueiredo の署名がありません。",
        "now_using": "TheeJ {version} を使用中です。現在入手できる最新バージョンです。",
        "ok": "OK",
        "open_settings": "システム設定を開く",
        "other": "その他…",
        "press_shortcut": "ショートカットを押す",
        "previous_profile": "前のプロファイル",
        "profile": "プロファイル",
        "profile_list": "プロファイル一覧",
        "profile_n": "プロファイル {n}",
        "profiles": "プロファイル",
        "quit": "TheeJ を終了",
        "reconnect": "再接続",
        "record_shortcut": "ショートカットを記録",
        "remove": "削除",
        "remove_knob": "最後のノブを削除",
        "remove_knob_info": "すべてのプロファイルでの役割も一緒に削除されます。",
        "remove_knob_q": "ノブ {letter} を削除しますか？",
        "remove_named": "“{name}”を削除しますか？",
        "remove_profile": "このプロファイルを削除",
        "remove_profile_info": "ノブの役割とショートカットも一緒に削除されます。",
        "remove_shortcut": "ショートカットを削除",
        "remove_this_profile": "このプロファイルを削除しますか？",
        "reopen": "開き直す",
        "reopen_failed": "開き直せませんでした: {error} アプリを終了して、自分で開いてください。",
        "save": "保存",
        "seconds_left.other": "残り {n} 秒",
        "section.apps": "アプリ",
        "section.brightness": "輝度",
        "section.contrast": "コントラスト",
        "section.keyboard": "キーボードのバックライト",
        "section.night_shift": "Night Shift",
        "section.volume": "音量",
        "sensitivity": "感度",
        "settings": "設定",
        "short.builtin": "内蔵",
        "short.builtin_display": "内蔵ディスプレイ",
        "short.external": "外部",
        "short.screen": "画面 {n}",
        "short.warmth": "色温度",
        "shortcut": "ショートカット",
        "shortcut_tip": "⌘ または ⌃ とキーを組み合わせてください。Delete で消去、Escape でキャンセル。",
        "shortcuts": "ショートカット",
        "show_data": "下にデータを表示",
        "show_name": "プロファイル名を表示",
        "skip": "スキップ",
        "space": "スペース",
        "speed": "速度",
        "speed.fast": "速い",
        "speed.medium": "普通",
        "speed.slow": "遅い（推奨）",
        "speed.superFast": "とても速い",
        "speed_note": "回したあと、変更が反映されるまでの早さ。",
        "tab.about": "このアプリについて",
        "tab.app": "アプリの設定",
        "tab.general": "一般",
        "tool_failed": "{tool} が失敗しました（{code}）。",
        "up_to_date": "最新の状態です",
        "update_available": "アップデートがあります",
        "update_complete": "アップデート完了",
        "update_failed": "アップデートをインストールできませんでした",
        "update_now": "今すぐアップデート",
        "update_question": "現在は {version} です。今すぐアップデートしますか？",
        "updating_to": "TheeJ を {version} にアップデート中",
        "version": "バージョン {version}",
        "website": "Web サイト",
        "weekly": "毎週",
        "wrong_download": "ダウンロードしたファイルは TheeJ {version} ではありません。",
    ]
}
