// 한국어. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let ko: [String: String] = [
        "about": "TheeJ에 관하여",
        "add_knob": "노브 추가",
        "add_profile": "프로필 추가",
        "applications_only": "TheeJ은(는) 응용 프로그램 폴더에서 실행할 때만 스스로 업데이트합니다.",
        "audio_text": "앱의 음량을 조절하기 위해 TheeJ는 그 앱의 소리를 노브의 레벨로 다시 재생하며, macOS는 이를 녹음으로 봅니다. ‘개인정보 보호 및 보안’의 ‘화면 및 시스템 오디오 녹음’에서 TheeJ를 허용한 다음 TheeJ를 종료하고 다시 여세요.",
        "audio_title": "TheeJ가 아직 앱 음량을 조절할 수 없습니다",
        "auto": "자동으로 확인",
        "available": "TheeJ {version} 사용 가능",
        "by": "제작:",
        "cal.all_found": "모든 노브를 찾았습니다",
        "cal.all_found_text": "보드가 값 {n}개를 보내고 있고 각각 노브가 정해졌으므로 이것이 전부입니다. ‘완료’를 클릭해 기능을 고르세요.",
        "cal.finish_later": "‘완료’를 누르면 여기서 멈추고 이 노브는 나중으로 미룹니다.",
        "cal.hold": "완료할 때까지 노브는 아무것도 조절하지 않습니다.",
        "cal.move": "노브 {letter}을(를) 끝에서 끝까지 움직이세요.",
        "cal.move_first": "노브 {letter}을(를) 끝에서 끝까지 움직이면 TheeJ가 어느 노브인지 알 수 있습니다. 그다음 각 노브를 {n}초 동안 돌리면 튀는 노브가 깨끗해집니다.",
        "cal.no_knob": "노브 {letter}이(가) 없으면 ‘완료’를 클릭하세요.",
        "cal.paused": "일시 정지됨, {left}. 노브 {letter}을(를) 계속 돌리세요.",
        "cal.skip_keeps": "이미 설정되어 있으므로 ‘건너뛰기’를 누르면 그대로 둡니다.",
        "cal.turn": "찾았습니다. 이제 끝에서 끝까지 {n}초 동안 좌우로 돌리세요. 타이머는 돌리는 동안에만 갑니다. 청소가 필요 없으면 건너뛰세요.",
        "cal.waiting_board": "보드 연결을 기다리는 중",
        "cal.waiting_knob": "노브 {letter}이(가) 움직이기를 기다리는 중",
        "cal.wrong": "그것은 노브 {wrong}입니다. 노브 {letter}을(를) 움직이세요.",
        "calibrate": "보정",
        "calibration_title": "TheeJ 보정",
        "cancel": "취소",
        "check": "업데이트 확인…",
        "check_connection": "연결을 확인하고 다시 시도하세요.",
        "check_failed": "업데이트를 확인할 수 없음",
        "checking_signature": "서명 확인 중…",
        "choose": "선택",
        "choose_language": "언어 선택",
        "click_to_update": "현재 {version}입니다. 클릭하여 업데이트하세요.",
        "connected": "연결됨: {port}",
        "continue": "계속",
        "daily": "매일",
        "default_profile": "기본",
        "dock": "Dock에 유지",
        "download": "다운로드",
        "download_failed": "다운로드에 실패했습니다.",
        "downloading": "버전 {version} 다운로드 중…",
        "finish": "완료",
        "hide_icon": "메뉴 막대 아이콘 가리기",
        "hide_icon_note": "TheeJ를 다시 열면 여기로 돌아옵니다.",
        "icon": "아이콘",
        "icon.app": "앱 아이콘",
        "icon.dial": "다이얼",
        "icon.mixer": "믹서",
        "inspired_by": "영감:",
        "install_now": "지금 버전 {version} 설치",
        "installed": "버전 {version}이(가) 설치되었습니다.",
        "installing": "설치 중…",
        "invert": "노브 반전",
        "invert_note": "반대로 배선된 가변저항용.",
        "job.brightness": "화면 {n} 밝기",
        "job.builtin_brightness": "내장 디스플레이 밝기",
        "job.builtin_contrast": "내장 디스플레이 대비",
        "job.builtin_keyboard": "내장 키보드 백라이트",
        "job.contrast": "화면 {n} 대비",
        "job.external_keyboard": "외장 키보드 백라이트",
        "job.master": "마스터 음량",
        "job.microphone": "마이크 음량",
        "job.night_shift": "Night Shift 색온도",
        "job.nothing": "없음",
        "jobs_note": "이 프로필에서 노브마다 기능을 하나 이상 체크하세요.",
        "knob": "노브 {letter}",
        "knobs": "노브",
        "knobs_found.other": "노브 {n}개를 찾았습니다",
        "language": "언어",
        "language_note": "나중에 설정이나 메뉴에서 바꿀 수 있습니다.",
        "later": "나중에",
        "login": "로그인 시 실행",
        "m1ddc.note": "외부 화면의 밝기와 대비에 필요합니다",
        "m1ddc.installed": "설치됨",
        "m1ddc.missing": "설치되지 않음",
        "m1ddc.install": "설치",
        "m1ddc.refresh": "새로 고침",
        "m1ddc.support": "지원:",
        "made_by": "제작:",
        "menu_bar": "메뉴 막대",
        "name": "이름",
        "needs_calibration": "보정 필요",
        "never": "안 함",
        "newest": "TheeJ {version}은(는) 현재 사용 가능한 최신 버전입니다.",
        "next_profile": "다음 프로필",
        "no_knobs": "노브가 없습니다. ‘보정’으로 찾거나 +를 눌러 하나 추가하세요.",
        "not_connected": "연결 안 됨",
        "not_signed": "다운로드한 파일에 Zolfer Figueiredo의 서명이 없습니다.",
        "now_using": "이제 TheeJ {version}을(를) 사용 중입니다. 현재 사용 가능한 최신 버전입니다.",
        "ok": "확인",
        "open_settings": "시스템 설정 열기",
        "other": "기타…",
        "press_shortcut": "단축키를 누르세요",
        "previous_profile": "이전 프로필",
        "profile": "프로필",
        "profile_list": "프로필 목록",
        "profile_n": "프로필 {n}",
        "profiles": "프로필",
        "quit": "TheeJ 종료",
        "reconnect": "다시 연결",
        "record_shortcut": "단축키 기록",
        "remove": "제거",
        "remove_knob": "마지막 노브 제거",
        "remove_knob_info": "모든 프로필에서 이 노브가 하는 기능도 함께 제거됩니다.",
        "remove_knob_q": "노브 {letter}을(를) 제거하시겠습니까?",
        "remove_named": "‘{name}’을(를) 제거하시겠습니까?",
        "remove_profile": "이 프로필 제거",
        "remove_profile_info": "노브 기능과 단축키도 함께 제거됩니다.",
        "remove_shortcut": "단축키 제거",
        "remove_this_profile": "이 프로필을 제거하시겠습니까?",
        "reopen": "다시 열기",
        "reopen_failed": "다시 열 수 없음: {error} 앱을 종료한 후 직접 여세요.",
        "save": "저장",
        "seconds_left.other": "{n}초 남음",
        "section.apps": "앱",
        "section.brightness": "밝기",
        "section.contrast": "대비",
        "section.keyboard": "키보드 백라이트",
        "section.night_shift": "Night Shift",
        "section.volume": "음량",
        "sensitivity": "민감도",
        "settings": "설정",
        "short.builtin": "내장",
        "short.builtin_display": "내장 디스플레이",
        "short.external": "외장",
        "short.screen": "화면 {n}",
        "short.warmth": "색온도",
        "shortcut": "단축키",
        "shortcut_tip": "⌘ 또는 ⌃를 키와 함께 사용하세요. Delete는 지우고 Escape는 취소합니다.",
        "shortcuts": "단축키",
        "show_data": "아래에 데이터 표시",
        "show_name": "프로필 이름 보기",
        "skip": "건너뛰기",
        "space": "스페이스",
        "speed": "속도",
        "speed.fast": "빠르게",
        "speed.medium": "보통",
        "speed.slow": "느리게(권장)",
        "speed.superFast": "매우 빠르게",
        "speed_note": "돌린 뒤 변경이 적용되기까지의 빠르기.",
        "tab.about": "정보",
        "tab.app": "앱 설정",
        "tab.general": "일반",
        "tool_failed": "{tool} 실패({code}).",
        "up_to_date": "최신 버전입니다!",
        "update_available": "업데이트가 있습니다!",
        "update_complete": "업데이트 완료!",
        "update_failed": "업데이트를 설치할 수 없음",
        "update_now": "지금 업데이트",
        "update_question": "현재 {version}입니다. 지금 업데이트할까요?",
        "updating_to": "TheeJ을(를) {version}(으)로 업데이트 중",
        "version": "버전 {version}",
        "website": "웹사이트",
        "weekly": "매주",
        "wrong_download": "다운로드한 파일이 TheeJ {version}이(가) 아닙니다.",
    ]
}
