// Polski. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let pl: [String: String] = [
        "about": "O TheeJ",
        "add_knob": "Dodaj pokrętło",
        "add_profile": "Dodaj profil",
        "applications_only": "TheeJ uaktualnia się sam tylko wtedy, gdy działa z folderu Aplikacje.",
        "audio_text": "Aby ustawić głośność aplikacji, TheeJ odtwarza jej dźwięk na poziomie pokrętła, co macOS traktuje jak nagrywanie. Zezwól TheeJ w „Nagrywanie ekranu i dźwięku systemowego” w „Prywatność i ochrona”, a potem zakończ TheeJ i otwórz go ponownie.",
        "audio_title": "TheeJ nie może jeszcze ustawiać głośności aplikacji",
        "auto": "Sprawdzaj automatycznie",
        "available": "Dostępna jest wersja TheeJ {version}",
        "by": "Autor:",
        "cal.all_found": "Znaleziono wszystkie pokrętła",
        "cal.all_found_text": "Liczba wartości wysyłanych przez płytkę: {n}. Każda ma już swoje pokrętło, więc to wszystkie. Kliknij Zakończ, aby wybrać, co robią.",
        "cal.finish_later": "Zakończ zatrzymuje się tutaj i zostawia je na później.",
        "cal.hold": "Pokrętła nic nie robią, dopóki nie skończysz.",
        "cal.move": "Przekręć pokrętło {letter} od końca do końca.",
        "cal.move_first": "Przekręć pokrętło {letter} od końca do końca, aby TheeJ wiedział, które pokrętło jest które. Potem każde pokrętło jest kręcone przez {n} sekund, co czyści skaczące pokrętło.",
        "cal.no_knob": "Jeśli nie masz pokrętła {letter}, kliknij Zakończ.",
        "cal.paused": "Wstrzymano. {left}. Kręć dalej pokrętłem {letter}.",
        "cal.skip_keeps": "Jest już ustawione, więc Pomiń zostawia je bez zmian.",
        "cal.turn": "Znalezione. Teraz kręć nim tam i z powrotem, od końca do końca, przez {n} sekund. Czas płynie tylko wtedy, gdy się obraca. Pomiń, jeśli nie wymaga czyszczenia.",
        "cal.waiting_board": "Czekam na połączenie z płytką",
        "cal.waiting_knob": "Czekam na ruch pokrętła {letter}",
        "cal.wrong": "To jest pokrętło {wrong}. Przekręć pokrętło {letter}.",
        "calibrate": "Kalibruj",
        "calibration_title": "Kalibracja TheeJ",
        "cancel": "Anuluj",
        "check": "Sprawdź uaktualnienia…",
        "check_connection": "Sprawdź połączenie i spróbuj ponownie.",
        "check_failed": "Nie udało się sprawdzić uaktualnień",
        "checking_signature": "Sprawdzanie podpisu…",
        "choose": "Wybierz",
        "choose_language": "Wybierz język",
        "click_to_update": "Masz wersję {version}. Kliknij, aby uaktualnić.",
        "close": "Zamknij",
        "connected": "Połączono: {port}",
        "continue": "Dalej",
        "daily": "Codziennie",
        "default_profile": "Domyślny",
        "dock": "Zostaw w Docku",
        "dock_restart": "Uruchom ponownie Dock",
        "dock_restart_text": "Aby to zmienić, macOS musi ponownie uruchomić Dock. Ekran i pasek menu na chwilę mrugną.",
        "dock_restart_title": "Uruchomić ponownie Dock?",
        "download": "Pobierz",
        "download_failed": "Pobieranie nie powiodło się.",
        "downloading": "Pobieranie wersji {version}…",
        "finish": "Zakończ",
        "hide_icon": "Ukryj ikonę na pasku menu",
        "hide_icon_note": "Otwórz TheeJ ponownie, aby tu wrócić.",
        "icon": "Ikona",
        "icon.app": "Ikona aplikacji",
        "icon.dial": "Pokrętło",
        "icon.mixer": "Mikser",
        "inspired_by": "Inspiracja:",
        "install_now": "Zainstaluj teraz wersję {version}",
        "installed": "Wersja {version} jest zainstalowana.",
        "installing": "Instalowanie…",
        "invert": "Odwróć pokrętła",
        "invert_note": "Dla potencjometrów podłączonych odwrotnie.",
        "job.brightness": "Jasność ekranu {n}",
        "job.builtin_brightness": "Jasność wbudowanego ekranu",
        "job.builtin_contrast": "Kontrast wbudowanego ekranu",
        "job.builtin_keyboard": "Podświetlenie wbudowanej klawiatury",
        "job.contrast": "Kontrast ekranu {n}",
        "job.external_keyboard": "Podświetlenie zewnętrznej klawiatury",
        "job.master": "Głośność główna",
        "job.microphone": "Głośność mikrofonu",
        "job.night_shift": "Ciepło Night Shift",
        "job.nothing": "Nic",
        "jobs_note": "Zaznacz jedno lub kilka zadań na pokrętło, w tym profilu.",
        "knob": "Pokrętło {letter}",
        "knobs": "Pokrętła",
        "knobs_found.few": "Znaleziono {n} pokrętła",
        "knobs_found.many": "Znaleziono {n} pokręteł",
        "knobs_found.one": "Znaleziono {n} pokrętło",
        "knobs_found.other": "Znaleziono {n} pokręteł",
        "language": "Język",
        "language_note": "Możesz go później zmienić w Ustawieniach lub w menu.",
        "later": "Później",
        "login": "Uruchamiaj przy logowaniu",
        "m1ddc.note": "Do jasności i kontrastu ekranów zewnętrznych",
        "m1ddc.installed": "Zainstalowano",
        "m1ddc.missing": "Nie zainstalowano",
        "m1ddc.install": "Zainstaluj",
        "m1ddc.refresh": "Odśwież",
        "m1ddc.support": "Pomoc:",
        "made_by": "Autor:",
        "menu_bar": "Pasek menu",
        "name": "Nazwa",
        "needs_calibration": "Wymaga kalibracji",
        "never": "Nigdy",
        "newest": "TheeJ {version} to obecnie najnowsza dostępna wersja.",
        "next_profile": "Następny profil",
        "no_knobs": "Brak pokręteł. Kalibruj je znajdzie, albo naciśnij +, aby dodać jedno.",
        "not_connected": "Nie połączono",
        "not_signed": "Pobrany plik nie jest podpisany przez Zolfer Figueiredo.",
        "now_using": "Używasz teraz TheeJ {version}, najnowszej dostępnej wersji.",
        "ok": "OK",
        "open_settings": "Otwórz Ustawienia systemowe",
        "other": "Inna…",
        "press_shortcut": "Naciśnij skrót",
        "previous_profile": "Poprzedni profil",
        "profile": "Profil",
        "profile_list": "Lista profili",
        "profile_n": "Profil {n}",
        "profiles": "Profile",
        "quit": "Zakończ TheeJ",
        "reconnect": "Połącz ponownie",
        "record_shortcut": "Nagraj skrót",
        "remove": "Usuń",
        "remove_knob": "Usuń ostatnie pokrętło",
        "remove_knob_info": "To, co robi w każdym profilu, zniknie razem z nim.",
        "remove_knob_q": "Usunąć pokrętło {letter}?",
        "remove_named": "Usunąć „{name}”?",
        "remove_profile": "Usuń ten profil",
        "remove_profile_info": "Jego zadania pokręteł i skrót znikną razem z nim.",
        "remove_shortcut": "Usuń skrót",
        "remove_this_profile": "Usunąć ten profil?",
        "reopen": "Otwórz ponownie",
        "reopen_failed": "Nie udało się otworzyć ponownie: {error} Zakończ aplikację i otwórz ją samodzielnie.",
        "save": "Zapisz",
        "seconds_left.few": "Zostały {n} sekundy",
        "seconds_left.many": "Zostało {n} sekund",
        "seconds_left.one": "Została {n} sekunda",
        "seconds_left.other": "Zostało {n} sekund",
        "section.apps": "Aplikacje",
        "section.brightness": "Jasność",
        "section.contrast": "Kontrast",
        "section.keyboard": "Podświetlenie klawiatury",
        "section.night_shift": "Night Shift",
        "section.volume": "Głośność",
        "sensitivity": "Czułość",
        "settings": "Ustawienia",
        "short.builtin": "Wbudowana",
        "short.builtin_display": "Wbudowany ekran",
        "short.external": "Zewnętrzna",
        "short.screen": "Ekran {n}",
        "short.warmth": "Ciepło",
        "shortcut": "Skrót",
        "shortcut_tip": "Użyj ⌘ lub ⌃ z klawiszem. Delete usuwa skrót, Escape anuluje.",
        "shortcuts": "Skróty",
        "show_data": "Pokaż dane poniżej",
        "show_name": "Pokazuj nazwę profilu",
        "skip": "Pomiń",
        "space": "Spacja",
        "speed": "Szybkość",
        "speed.fast": "Szybko",
        "speed.medium": "Średnio",
        "speed.slow": "Wolno (zalecane)",
        "speed.superFast": "Bardzo szybko",
        "speed_note": "Jak szybko zmiana działa po obrocie.",
        "tab.about": "Informacje",
        "tab.app": "Ustawienia aplikacji",
        "tab.general": "Ogólne",
        "tool_failed": "{tool}: niepowodzenie ({code}).",
        "up_to_date": "Masz najnowszą wersję!",
        "update_available": "Dostępne uaktualnienie!",
        "update_complete": "Uaktualnienie zakończone!",
        "update_failed": "Nie udało się zainstalować uaktualnienia",
        "update_now": "Uaktualnij teraz",
        "update_question": "Masz wersję {version}. Uaktualnić teraz?",
        "updating_to": "Uaktualnianie TheeJ do {version}",
        "version": "Wersja {version}",
        "website": "Strona",
        "weekly": "Co tydzień",
        "wrong_download": "Pobrany plik to nie TheeJ {version}.",
    ]
}
