// Polski. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let pl: [String: String] = [
        "about": "O TheeJ",
        "action.close_app": "Zamknij aplikację",
        "action.go_profile": "Przejdź do: {name}",
        "action.group.apps": "Aplikacje",
        "action.group.fkeys": "Klawisze funkcyjne",
        "action.group.knobs": "Pokrętła",
        "action.group.media": "Multimedia",
        "action.group.system": "System",
        "action.keys": "Naciśnij skrót",
        "action.lights_off": "Wyłącz podświetlenie przycisków",
        "action.lights_on": "Włącz podświetlenie przycisków",
        "action.lock": "Zablokuj Maca",
        "action.mute": "Wycisz: {name}",
        "action.mute_all": "Wycisz cały dźwięk",
        "action.mute_mic": "Wycisz mikrofon",
        "action.next_lights": "Następne podświetlenie przycisków",
        "action.next_track": "Następny utwór",
        "action.night_light": "Night Shift wł./wył.",
        "action.open_app": "Otwórz aplikację",
        "action.open_settings": "Otwórz Ustawienia",
        "action.open_url": "Otwórz stronę",
        "action.pause": "Pauza",
        "action.play": "Odtwórz",
        "action.play_pause": "Odtwórz/pauza",
        "action.previous_lights": "Poprzednie podświetlenie przycisków",
        "action.previous_track": "Poprzedni utwór",
        "action.screens_off": "Wyłącz ekrany",
        "action.sleep": "Uśpij",
        "action.volume_down": "Ciszej",
        "action.volume_up": "Głośniej",
        "add.add": "Dodaj",
        "add.name_hint": "Biurko",
        "add.next": "Dalej",
        "add.title": "Dodaj płytkę",
        "add.type_note.diy": "Arduino wysyłające pokrętła przez USB, jak w deej.",
        "add.type_note.midi": "Dowolny inny kontroler MIDI. Pokazujesz TheeJ, który element jest który.",
        "add.type_note.smc": "M-VAVE SMC-Mixer. Jego elementy są znane, więc nie wymaga kalibracji.",
        "add_profile": "Dodaj profil",
        "applications_only": "TheeJ uaktualnia się sam tylko wtedy, gdy działa z folderu Aplikacje.",
        "apply": "Zastosuj",
        "audio_text": "Aby ustawić głośność aplikacji, TheeJ odtwarza jej dźwięk na poziomie pokrętła, co macOS traktuje jak nagrywanie. Zezwól TheeJ w „Nagrywanie ekranu i dźwięku systemowego” w „Prywatność i ochrona”, a potem zakończ TheeJ i otwórz go ponownie.",
        "audio_title": "TheeJ nie może jeszcze ustawiać głośności aplikacji",
        "auto": "Sprawdzaj automatycznie",
        "available": "Dostępna jest wersja TheeJ {version}",
        "baud_note": "Musi zgadzać się z Serial.begin() w szkicu płytki.",
        "baud_rate": "Prędkość transmisji",
        "board.button": "Przycisk {letter}",
        "board.empty": "Ta płytka nie ma żadnych elementów.",
        "board.fader": "Suwak {letter}",
        "board.hint": "Porusz lub naciśnij element na płytce albo kliknij go tutaj, aby wybrać, co robi.",
        "boards.add": "Dodaj płytkę",
        "boards.none": "Brak płytek.",
        "boards.none_connected": "Żadna płytka nie jest podłączona.",
        "boards.on": "{name} włączona",
        "boards.set_up": "Skonfiguruj płytki",
        "boards.settings": "Ustawienia płytki",
        "boards.settings_of": "Ustawienia: {name}",
        "boards.title": "Płytki",
        "by": "Autor:",
        "calibrate": "Kalibruj",
        "cancel": "Anuluj",
        "check": "Sprawdź uaktualnienia…",
        "check_connection": "Sprawdź połączenie i spróbuj ponownie.",
        "check_failed": "Nie udało się sprawdzić uaktualnień",
        "checking_signature": "Sprawdzanie podpisu…",
        "choose": "Wybierz",
        "choose_language": "Wybierz język",
        "clear": "Wyczyść",
        "click_to_update": "Masz wersję {version}. Kliknij, aby uaktualnić.",
        "close": "Zamknij",
        "connected": "Połączono: {port}",
        "continue": "Dalej",
        "daily": "Codziennie",
        "default_profile": "Domyślny",
        "device.pick_input": "Wybierz wejście MIDI",
        "device.remove": "Usuń płytkę",
        "device.remove_info": "Jej profile i kalibracja zostaną usunięte.",
        "device.type": "Typ",
        "device.type.diy": "Własnej roboty (Arduino)",
        "device.type.midi": "Inne MIDI",
        "device.type.smc": "SMC-Mixer",
        "device.used_by": "{port} (używa {board})",
        "dock": "Zostaw w Docku",
        "dock_restart": "Uruchom ponownie Dock",
        "dock_restart_text": "Aby to zmienić, macOS musi ponownie uruchomić Dock. Ekran i pasek menu na chwilę mrugną.",
        "dock_restart_title": "Uruchomić ponownie Dock?",
        "download": "Pobierz",
        "download_failed": "Pobieranie nie powiodło się.",
        "downloading": "Pobieranie wersji {version}…",
        "finish": "Zakończ",
        "general.app": "Aplikacja",
        "hide_icon": "Ukryj ikonę na pasku menu",
        "hide_icon_note": "Otwórz TheeJ ponownie, aby tu wrócić.",
        "icon": "Ikona",
        "icon.app": "Ikona aplikacji",
        "icon.dial": "Pokrętło",
        "icon.mixer": "Mikser",
        "inspired_by": "Inspiracja:",
        "install_now": "Zainstaluj teraz wersję {version}",
        "installed": "Wersja {version} jest zainstalowana.",
        "installing": "Instalowanie…",
        "job.brightness": "Jasność ekranu {n}",
        "job.builtin_brightness": "Jasność wbudowanego ekranu",
        "job.builtin_contrast": "Kontrast wbudowanego ekranu",
        "job.builtin_keyboard": "Podświetlenie wbudowanej klawiatury",
        "job.contrast": "Kontrast ekranu {n}",
        "job.empty": "Puste",
        "job.external_keyboard": "Podświetlenie zewnętrznej klawiatury",
        "job.master": "Głośność główna",
        "job.microphone": "Głośność mikrofonu",
        "job.night_shift": "Ciepło Night Shift",
        "job.nothing": "Nic",
        "job.zoom": "Powiększenie ekranu",
        "knob": "Pokrętło {letter}",
        "knobs": "Pokrętła",
        "language": "Język",
        "language_note": "Możesz go później zmienić w Ustawieniach lub w menu.",
        "later": "Później",
        "lights": "Podświetlenie przycisków",
        "lights.ball": "Piłka",
        "lights.bars": "Słupki",
        "lights.blink": "Miganie",
        "lights.bounce": "Odbicie",
        "lights.breathe": "Oddech",
        "lights.chase": "Pościg",
        "lights.checker": "Szachownica",
        "lights.clock": "Zegar binarny",
        "lights.comet": "Kometa",
        "lights.eq": "Korektor",
        "lights.eq2": "Korektor 2",
        "lights.eqgame": "Korektor do gier",
        "lights.explode": "Wybuch",
        "lights.fill": "Wypełnianie",
        "lights.fire": "Ogień",
        "lights.heartbeat": "Bicie serca",
        "lights.helix": "Helisa",
        "lights.matrix": "Matrix",
        "lights.off": "Wyłączone",
        "lights.on": "Włączone",
        "lights.orbit": "Orbita",
        "lights.rain": "Deszcz",
        "lights.random": "Losowo",
        "lights.rise": "Wznoszenie",
        "lights.snake": "Wąż",
        "lights.sparkle": "Iskrzenie",
        "lights.stars": "Gwiazdy",
        "lights.wave": "Fala",
        "lights.zigzag": "Zygzak",
        "lights_note": "Wciśnięte przyciski i wyciszenia nadal się świecą.",
        "list.buttons": "Przyciski",
        "list.faders": "Suwaki",
        "list.none": "Brak",
        "login": "Uruchamiaj przy logowaniu",
        "m1ddc.note": "Do jasności i kontrastu ekranów zewnętrznych",
        "m1ddc.installed": "Zainstalowano",
        "m1ddc.missing": "Nie zainstalowano",
        "m1ddc.install": "Zainstaluj",
        "m1ddc.refresh": "Odśwież",
        "m1ddc.support": "Pomoc:",
        "made_by": "Autor:",
        "menu.board": "{name}: {status}",
        "mixer.fader": "Suwak {n}",
        "mixer.knob": "Pokrętło {n}",
        "mixer_port_note": "Wybierz mikser MIDI, aby używać go obok płytki.",
        "name": "Nazwa",
        "needs_calibration": "Wymaga kalibracji",
        "never": "Nigdy",
        "newest": "TheeJ {version} to obecnie najnowsza dostępna wersja.",
        "next_profile": "Następny profil",
        "not_connected": "Nie połączono",
        "not_signed": "Pobrany plik nie jest podpisany przez Zolfer Figueiredo.",
        "now_using": "Używasz teraz TheeJ {version}, najnowszej dostępnej wersji.",
        "ok": "OK",
        "on_windows": "Na Windowsie? Pobierz",
        "open_settings": "Otwórz Ustawienia systemowe",
        "other": "Inna…",
        "port": "Urządzenie",
        "port_auto": "Automatycznie",
        "port_busy": "{port} jest używany przez inną aplikację",
        "port_forced": "Ustawiony na {port} przy uruchomieniu TheeJ.",
        "port_note": "W trybie automatycznym TheeJ sam znajdzie płytkę.",
        "press_shortcut": "Naciśnij skrót",
        "previous_profile": "Poprzedni profil",
        "profile": "Profil",
        "profile.edit": "Edytuj profil…",
        "profile_list": "Lista profili",
        "profile_n": "Profil {n}",
        "quit": "Zakończ TheeJ",
        "reconnect": "Połącz ponownie",
        "record_shortcut": "Nagraj skrót",
        "refresh": "Odśwież",
        "remove": "Usuń",
        "remove_named": "Usunąć „{name}”?",
        "remove_profile": "Usuń ten profil",
        "remove_profile_info": "Jego zadania pokręteł i skrót znikną razem z nim.",
        "remove_shortcut": "Usuń skrót",
        "remove_this_profile": "Usunąć ten profil?",
        "reopen": "Otwórz ponownie",
        "reopen_failed": "Nie udało się otworzyć ponownie: {error} Zakończ aplikację i otwórz ją samodzielnie.",
        "save": "Zapisz",
        "section.apps": "Aplikacje",
        "section.brightness": "Jasność",
        "section.contrast": "Kontrast",
        "section.keyboard": "Podświetlenie klawiatury",
        "section.night_shift": "Night Shift",
        "section.volume": "Głośność",
        "section.zoom": "Powiększenie",
        "settings": "Ustawienia",
        "short.builtin": "Wbudowana",
        "short.builtin_display": "Wbudowany ekran",
        "short.external": "Zewnętrzna",
        "short.screen": "Ekran {n}",
        "short.warmth": "Ciepło",
        "shortcut": "Skrót",
        "shortcut.also_used": "Używane też przez {names}",
        "shortcut.clash": "Ta płytka używa już tego skrótu. Spróbuj innego.",
        "shortcut.taken": "Inna aplikacja używa już tego skrótu. Spróbuj innego.",
        "shortcut_tip": "Użyj ⌘ lub ⌃ z klawiszem. Delete usuwa skrót, Escape anuluje.",
        "show_data": "Pokaż dane poniżej",
        "show_name": "Pokazuj nazwę profilu",
        "skip": "Pomiń",
        "smc.bank_left": "Poprzedni bank",
        "smc.bank_right": "Następny bank",
        "smc.down": "W dół",
        "smc.hint": "Porusz lub naciśnij element na mikserze albo kliknij go tutaj, aby wybrać, co robi.",
        "smc.left": "W lewo",
        "smc.record": "Nagrywanie",
        "smc.right": "W prawo",
        "smc.square": "Kwadrat {n}",
        "smc.up": "W górę",
        "space": "Spacja",
        "speed": "Szybkość",
        "speed.fast": "Szybko",
        "speed.medium": "Średnio",
        "speed.slow": "Wolno (zalecane)",
        "speed.superFast": "Bardzo szybko",
        "speed_note": "Jak szybko zmiana działa po obrocie.",
        "status": "Stan",
        "status.connected": "Połączona",
        "status.disconnected": "Rozłączona",
        "status.off": "Wyłączona",
        "tab.about": "Informacje",
        "tab.boards": "Płytki",
        "tab.general": "Ogólne",
        "tool_failed": "{tool}: niepowodzenie ({code}).",
        "up_to_date": "Masz najnowszą wersję!",
        "update_available": "Dostępne uaktualnienie!",
        "update_complete": "Uaktualnienie zakończone!",
        "update_failed": "Nie udało się zainstalować uaktualnienia",
        "update_now": "Uaktualnij teraz",
        "update_question": "Masz wersję {version}. Uaktualnić teraz?",
        "updating_to": "Uaktualnianie TheeJ do {version}",
        "version": "Wersja {version}",
        "view.draw": "Rysunek",
        "view.list": "Lista",
        "website": "Strona",
        "weekly": "Co tydzień",
        "wizard.count": "{n} z {of}",
        "wizard.done": "Wszystkie elementy znalezione. Naciśnij Zakończ, aby je zachować.",
        "wizard.find": "Przesuń {name} z powrotem na 0%.",
        "wizard.full": "Teraz ustaw każde pokrętło i suwak na 100%, a potem naciśnij Dalej.",
        "wizard.mismatch": "To był inny przycisk. Naciśnij {name} trzy razy.",
        "wizard.nothing": "Nic się nie poruszyło między 0% a 100%.",
        "wizard.press": "Naciśnij {name} trzy razy.",
        "wizard.redo": "Zacznij od nowa",
        "wizard.step": "{i} z {n}",
        "wizard.title": "Kalibruj: {name}",
        "wizard.unswept": "To nie poruszyło się między 0% a 100%. Naciśnij Zacznij od nowa.",
        "wizard.waiting": "Czekam na połączenie {name}.",
        "wizard.wrong": "To jest {other}. Przesuń {name}.",
        "wizard.zero": "Ustaw każde pokrętło i suwak na 0%, a potem naciśnij Dalej.",
        "wrong_download": "Pobrany plik to nie TheeJ {version}.",
    ]
}
