// Português. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let pt: [String: String] = [
        "about": "Sobre o TheeJ",
        "add_knob": "Adicionar um botão",
        "add_profile": "Adicionar um perfil",
        "applications_only": "O TheeJ só se atualiza quando é executado da pasta Aplicativos.",
        "audio_text": "Para ajustar o volume de um app, o TheeJ reproduz o som desse app no nível do botão, o que o macOS considera uma gravação. Permita o TheeJ em “Gravação de Tela e Áudio do Sistema”, em “Privacidade e Segurança”, depois encerre o TheeJ e abra-o de novo.",
        "audio_title": "O TheeJ ainda não pode ajustar o volume dos apps",
        "auto": "Verificar automaticamente",
        "available": "TheeJ {version} está disponível",
        "by": "Por",
        "cal.all_found": "Todos os botões encontrados",
        "cal.all_found_text": "Sua placa envia {n} valores e cada um já tem seu botão, então estão todos aí. Clique em Concluir para escolher o que eles fazem.",
        "cal.finish_later": "Concluir para aqui e deixa esse botão para depois.",
        "cal.hold": "Seus botões não fazem nada até você concluir.",
        "cal.move": "Mova o botão {letter} de uma ponta à outra.",
        "cal.move_first": "Mova o botão {letter} de uma ponta à outra, para o TheeJ saber qual botão é qual. Depois, cada botão é girado por {n} segundos, o que limpa um botão que pula.",
        "cal.no_knob": "Se você não tem um botão {letter}, clique em Concluir.",
        "cal.paused": "Em pausa. {left}. Continue girando o botão {letter}.",
        "cal.skip_keeps": "Ele já está configurado, então Pular o mantém como está.",
        "cal.turn": "Encontrado. Agora gire para lá e para cá, de uma ponta à outra, por {n} segundos. O tempo só corre enquanto ele gira. Pule se ele não precisa de limpeza.",
        "cal.waiting_board": "Esperando a placa conectar",
        "cal.waiting_knob": "Esperando o botão {letter} se mover",
        "cal.wrong": "Esse é o botão {wrong}. Mova o botão {letter}.",
        "calibrate": "Calibrar",
        "calibration_title": "Calibração do TheeJ",
        "cancel": "Cancelar",
        "check": "Buscar atualizações…",
        "check_connection": "Verifique sua conexão e tente de novo.",
        "check_failed": "Não foi possível buscar atualizações",
        "checking_signature": "Verificando a assinatura…",
        "choose": "Escolher",
        "choose_language": "Escolha seu idioma",
        "clear": "Limpar",
        "click_to_update": "Você tem a {version}. Clique para atualizar.",
        "close": "Fechar",
        "connected": "Conectado: {port}",
        "continue": "Continuar",
        "daily": "Diariamente",
        "default_profile": "Padrão",
        "dock": "Manter no Dock",
        "dock_restart": "Reiniciar o Dock",
        "dock_restart_text": "Para mudar isso, o macOS precisa reiniciar o Dock. A tela e a barra de menus vão piscar por um instante.",
        "dock_restart_title": "Reiniciar o Dock?",
        "download": "Baixar",
        "download_failed": "O download falhou.",
        "downloading": "Baixando a versão {version}…",
        "finish": "Concluir",
        "hide_icon": "Ocultar ícone da barra de menus",
        "hide_icon_note": "Abra o TheeJ de novo para voltar aqui.",
        "icon": "Ícone",
        "icon.app": "Ícone do app",
        "icon.dial": "Dial",
        "icon.mixer": "Mixer",
        "inspired_by": "Inspirado em",
        "install_now": "Instalar a versão {version} agora",
        "installed": "A versão {version} está instalada.",
        "installing": "Instalando…",
        "invert": "Inverter botões",
        "invert_note": "Para potenciômetros ligados ao contrário.",
        "job.brightness": "Brilho da tela {n}",
        "job.builtin_brightness": "Brilho da tela integrada",
        "job.builtin_contrast": "Contraste da tela integrada",
        "job.builtin_keyboard": "Luz do teclado integrado",
        "job.contrast": "Contraste da tela {n}",
        "job.external_keyboard": "Luz do teclado externo",
        "job.master": "Volume geral",
        "job.microphone": "Volume do microfone",
        "job.night_shift": "Temperatura do Night Shift",
        "job.nothing": "Nada",
        "job.zoom": "Zoom da tela",
        "jobs_note": "Marque uma ou mais funções por botão, para este perfil.",
        "knob": "Botão {letter}",
        "knobs": "Botões",
        "knobs_found.one": "{n} botão encontrado",
        "knobs_found.other": "{n} botões encontrados",
        "language": "Idioma",
        "language_note": "Você pode mudar depois nos Ajustes ou no menu.",
        "later": "Depois",
        "login": "Abrir ao iniciar sessão",
        "m1ddc.note": "Para brilho e contraste de telas externas",
        "m1ddc.installed": "Instalado",
        "m1ddc.missing": "Não instalado",
        "m1ddc.install": "Instalar",
        "m1ddc.refresh": "Atualizar",
        "m1ddc.support": "Suporte:",
        "made_by": "Feito por",
        "menu_bar": "Barra de menus",
        "name": "Nome",
        "needs_calibration": "Precisa de calibração",
        "never": "Nunca",
        "newest": "TheeJ {version} é a versão mais recente disponível.",
        "next_profile": "Próximo perfil",
        "no_knobs": "Nenhum botão. Calibrar encontra os botões, ou pressione + para adicionar um.",
        "not_connected": "Não conectado",
        "not_signed": "O download não está assinado por Zolfer Figueiredo.",
        "now_using": "Agora você está usando o TheeJ {version}, a versão mais recente disponível.",
        "ok": "OK",
        "open_settings": "Abrir Ajustes do Sistema",
        "other": "Outro…",
        "press_shortcut": "Pressione o atalho",
        "previous_profile": "Perfil anterior",
        "profile": "Perfil",
        "profile_list": "Lista de perfis",
        "profile_n": "Perfil {n}",
        "profiles": "Perfis",
        "quit": "Encerrar TheeJ",
        "reconnect": "Reconectar",
        "record_shortcut": "Gravar atalho",
        "remove": "Remover",
        "remove_knob": "Remover o último botão",
        "remove_knob_info": "O que ele faz em todos os perfis é removido junto.",
        "remove_knob_q": "Remover o botão {letter}?",
        "remove_named": "Remover “{name}”?",
        "remove_profile": "Remover este perfil",
        "remove_profile_info": "As funções dos botões e o atalho dele são removidos junto.",
        "remove_shortcut": "Remover atalho",
        "remove_this_profile": "Remover este perfil?",
        "reopen": "Reabrir",
        "reopen_failed": "Não foi possível reabrir: {error} Encerre o app e abra-o você mesmo.",
        "save": "Salvar",
        "seconds_left.one": "Falta {n} segundo",
        "seconds_left.other": "Faltam {n} segundos",
        "section.apps": "Apps",
        "section.brightness": "Brilho",
        "section.contrast": "Contraste",
        "section.keyboard": "Luz do teclado",
        "section.night_shift": "Night Shift",
        "section.volume": "Volume",
        "section.zoom": "Zoom",
        "sensitivity": "Sensibilidade",
        "settings": "Ajustes",
        "short.builtin": "Integrado",
        "short.builtin_display": "Tela integrada",
        "short.external": "Externo",
        "short.screen": "Tela {n}",
        "short.warmth": "Temperatura",
        "shortcut": "Atalho",
        "shortcut_tip": "Use ⌘ ou ⌃ com uma tecla. Apagar limpa o atalho, Esc cancela.",
        "shortcuts": "Atalhos",
        "show_data": "Mostrar dados abaixo",
        "show_name": "Mostrar nome do perfil",
        "skip": "Pular",
        "space": "Espaço",
        "speed": "Velocidade",
        "speed.fast": "Rápida",
        "speed.medium": "Média",
        "speed.slow": "Lenta (recomendada)",
        "speed.superFast": "Super-rápida",
        "speed_note": "Quão rápido um giro se aplica.",
        "tab.about": "Sobre",
        "tab.app": "Ajustes do app",
        "tab.general": "Geral",
        "tool_failed": "{tool} falhou ({code}).",
        "up_to_date": "Você está atualizado!",
        "update_available": "Atualização disponível!",
        "update_complete": "Atualização concluída!",
        "update_failed": "Não foi possível instalar a atualização",
        "update_now": "Instalar agora",
        "update_question": "Você tem a {version}. Atualizar agora?",
        "updating_to": "Atualizando TheeJ para {version}",
        "version": "Versão {version}",
        "website": "Site",
        "weekly": "Semanalmente",
        "wrong_download": "O download não é o TheeJ {version}.",
    ]
}
