// Русский. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let ru: [String: String] = [
        "about": "О программе TheeJ",
        "add_knob": "Добавить ручку",
        "add_profile": "Добавить профиль",
        "applications_only": "TheeJ обновляется сам, только если запущен из папки «Программы».",
        "audio_text": "Чтобы менять громкость приложения, TheeJ воспроизводит его звук на уровне ручки, а macOS считает это записью. Разрешите TheeJ в разделе «Запись экрана и системного аудио» в «Конфиденциальность и безопасность», затем завершите TheeJ и откройте его снова.",
        "audio_title": "TheeJ пока не может менять громкость приложений",
        "auto": "Проверять автоматически",
        "available": "Доступна версия TheeJ {version}",
        "by": "Автор:",
        "cal.all_found": "Все ручки найдены",
        "cal.all_found_text": "Плата передаёт значений: {n}. У каждого теперь есть своя ручка, так что это все. Нажмите «Готово», чтобы выбрать, что они делают.",
        "cal.finish_later": "«Готово» остановится здесь и оставит её на потом.",
        "cal.hold": "Ручки ничего не меняют, пока вы не закончите.",
        "cal.move": "Проверните ручку {letter} от края до края.",
        "cal.move_first": "Проверните ручку {letter} от края до края, чтобы TheeJ понял, какая ручка где. Затем каждую ручку нужно крутить {n} секунд: это прочищает дёрганую ручку.",
        "cal.no_knob": "Если ручки {letter} у вас нет, нажмите «Готово».",
        "cal.paused": "Пауза. {left}. Продолжайте крутить ручку {letter}.",
        "cal.skip_keeps": "Она уже настроена, так что «Пропустить» оставит её как есть.",
        "cal.turn": "Нашлась. Теперь крутите её туда и обратно, от края до края, {n} секунд. Время идёт, только пока она вращается. Пропустите, если чистка не нужна.",
        "cal.waiting_board": "Жду подключения платы",
        "cal.waiting_knob": "Жду движения ручки {letter}",
        "cal.wrong": "Это ручка {wrong}. Поверните ручку {letter}.",
        "calibrate": "Калибровать",
        "calibration_title": "Калибровка TheeJ",
        "cancel": "Отменить",
        "check": "Проверить обновления…",
        "check_connection": "Проверьте подключение и повторите попытку.",
        "check_failed": "Не удалось проверить обновления",
        "checking_signature": "Проверка подписи…",
        "choose": "Выбрать",
        "choose_language": "Выберите язык",
        "click_to_update": "У вас {version}. Нажмите, чтобы обновить.",
        "close": "Закрыть",
        "connected": "Подключено: {port}",
        "continue": "Продолжить",
        "daily": "Ежедневно",
        "default_profile": "По умолчанию",
        "dock": "Оставить в Dock",
        "dock_restart": "Перезапустить Dock",
        "dock_restart_text": "Для этого macOS нужно перезапустить Dock. Экран и строка меню на мгновение мигнут.",
        "dock_restart_title": "Перезапустить Dock?",
        "download": "Скачать",
        "download_failed": "Не удалось загрузить.",
        "downloading": "Загрузка версии {version}…",
        "finish": "Готово",
        "hide_icon": "Скрыть значок в строке меню",
        "hide_icon_note": "Откройте TheeJ ещё раз, чтобы вернуться сюда.",
        "icon": "Значок",
        "icon.app": "Значок приложения",
        "icon.dial": "Регулятор",
        "icon.mixer": "Микшер",
        "inspired_by": "Вдохновлено:",
        "install_now": "Установить версию {version} сейчас",
        "installed": "Версия {version} установлена.",
        "installing": "Установка…",
        "invert": "Инвертировать ручки",
        "invert_note": "Для потенциометров, подключённых наоборот.",
        "job.brightness": "Яркость экрана {n}",
        "job.builtin_brightness": "Яркость встроенного дисплея",
        "job.builtin_contrast": "Контраст встроенного дисплея",
        "job.builtin_keyboard": "Подсветка встроенной клавиатуры",
        "job.contrast": "Контраст экрана {n}",
        "job.external_keyboard": "Подсветка внешней клавиатуры",
        "job.master": "Общая громкость",
        "job.microphone": "Громкость микрофона",
        "job.night_shift": "Теплота Night Shift",
        "job.nothing": "Ничего",
        "jobs_note": "Отметьте задачи каждой ручки в этом профиле.",
        "knob": "Ручка {letter}",
        "knobs": "Ручки",
        "knobs_found.few": "Найдено {n} ручки",
        "knobs_found.many": "Найдено {n} ручек",
        "knobs_found.one": "Найдена {n} ручка",
        "knobs_found.other": "Найдено {n} ручек",
        "language": "Язык",
        "language_note": "Его можно изменить позже в настройках или в меню.",
        "later": "Позже",
        "login": "Запускать при входе",
        "m1ddc.note": "Для яркости и контраста внешних экранов",
        "m1ddc.installed": "Установлено",
        "m1ddc.missing": "Не установлено",
        "m1ddc.install": "Установить",
        "m1ddc.refresh": "Обновить",
        "m1ddc.support": "Поддержка:",
        "made_by": "Автор:",
        "menu_bar": "Строка меню",
        "name": "Имя",
        "needs_calibration": "Нужна калибровка",
        "never": "Никогда",
        "newest": "TheeJ {version}: это самая новая доступная версия.",
        "next_profile": "Следующий профиль",
        "no_knobs": "Ручек нет. «Калибровать» найдёт их, или нажмите +, чтобы добавить одну.",
        "not_connected": "Не подключено",
        "not_signed": "Загрузка не подписана Zolfer Figueiredo.",
        "now_using": "Теперь вы используете TheeJ {version}, самую новую доступную версию.",
        "ok": "OK",
        "open_settings": "Открыть Системные настройки",
        "other": "Другое…",
        "press_shortcut": "Нажмите сочетание",
        "previous_profile": "Предыдущий профиль",
        "profile": "Профиль",
        "profile_list": "Список профилей",
        "profile_n": "Профиль {n}",
        "profiles": "Профили",
        "quit": "Завершить TheeJ",
        "reconnect": "Переподключить",
        "record_shortcut": "Записать сочетание",
        "remove": "Удалить",
        "remove_knob": "Удалить последнюю ручку",
        "remove_knob_info": "Её задачи во всех профилях удалятся вместе с ней.",
        "remove_knob_q": "Удалить ручку {letter}?",
        "remove_named": "Удалить «{name}»?",
        "remove_profile": "Удалить этот профиль",
        "remove_profile_info": "Его задачи ручек и сочетание клавиш удалятся вместе с ним.",
        "remove_shortcut": "Удалить сочетание клавиш",
        "remove_this_profile": "Удалить этот профиль?",
        "reopen": "Открыть снова",
        "reopen_failed": "Не удалось открыть снова: {error} Завершите приложение и откройте его сами.",
        "save": "Сохранить",
        "seconds_left.few": "Осталось {n} секунды",
        "seconds_left.many": "Осталось {n} секунд",
        "seconds_left.one": "Осталась {n} секунда",
        "seconds_left.other": "Осталось {n} секунд",
        "section.apps": "Приложения",
        "section.brightness": "Яркость",
        "section.contrast": "Контраст",
        "section.keyboard": "Подсветка клавиатуры",
        "section.night_shift": "Night Shift",
        "section.volume": "Громкость",
        "sensitivity": "Чувствительность",
        "settings": "Настройки",
        "short.builtin": "Встроенная",
        "short.builtin_display": "Встроенный дисплей",
        "short.external": "Внешняя",
        "short.screen": "Экран {n}",
        "short.warmth": "Теплота",
        "shortcut": "Сочетание клавиш",
        "shortcut_tip": "Используйте ⌘ или ⌃ с клавишей. Delete стирает сочетание, Escape отменяет.",
        "shortcuts": "Сочетания клавиш",
        "show_data": "Показывать данные ниже",
        "show_name": "Показывать имя профиля",
        "skip": "Пропустить",
        "space": "Пробел",
        "speed": "Скорость",
        "speed.fast": "Быстро",
        "speed.medium": "Средне",
        "speed.slow": "Медленно (рекомендуется)",
        "speed.superFast": "Очень быстро",
        "speed_note": "Когда срабатывает поворот.",
        "tab.about": "О программе",
        "tab.app": "Настройки приложения",
        "tab.general": "Основные",
        "tool_failed": "{tool}: сбой ({code}).",
        "up_to_date": "У вас последняя версия!",
        "update_available": "Доступно обновление!",
        "update_complete": "Обновление завершено!",
        "update_failed": "Не удалось установить обновление",
        "update_now": "Установить сейчас",
        "update_question": "У вас {version}. Обновить сейчас?",
        "updating_to": "Обновление TheeJ до {version}",
        "version": "Версия {version}",
        "website": "Сайт",
        "weekly": "Еженедельно",
        "wrong_download": "Загружен не TheeJ {version}.",
    ]
}
