// Русский. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let ru: [String: String] = [
        "about": "О программе TheeJ",
        "action.close_app": "Закрыть приложение",
        "action.go_profile": "Перейти к профилю «{name}»",
        "action.group.apps": "Приложения",
        "action.group.fkeys": "Функциональные клавиши",
        "action.group.knobs": "Ручки",
        "action.group.media": "Медиа",
        "action.group.system": "Система",
        "action.keys": "Нажать сочетание клавиш",
        "action.lights_off": "Выключить подсветку кнопок",
        "action.lights_on": "Включить подсветку кнопок",
        "action.lock": "Заблокировать Mac",
        "action.mute": "Выключить звук: {name}",
        "action.mute_all": "Выключить весь звук",
        "action.mute_mic": "Выключить микрофон",
        "action.next_lights": "Следующая подсветка кнопок",
        "action.next_track": "Следующий трек",
        "action.night_light": "Night Shift вкл./выкл.",
        "action.open_app": "Открыть приложение",
        "action.open_settings": "Открыть настройки",
        "action.open_url": "Открыть сайт",
        "action.pause": "Пауза",
        "action.play": "Воспроизвести",
        "action.play_pause": "Воспроизведение/пауза",
        "action.previous_lights": "Предыдущая подсветка кнопок",
        "action.previous_track": "Предыдущий трек",
        "action.screens_off": "Выключить экраны",
        "action.sleep": "Спящий режим",
        "action.volume_down": "Тише",
        "action.volume_up": "Громче",
        "add.add": "Добавить",
        "add.name_hint": "Стол",
        "add.next": "Далее",
        "add.title": "Добавить плату",
        "add.type_note.diy": "Arduino, который передаёт ручки по USB, как в deej.",
        "add.type_note.midi": "Любой другой MIDI-контроллер. Вы показываете TheeJ, какой элемент какой.",
        "add.type_note.smc": "M-VAVE SMC-Mixer. Его элементы уже известны, калибровка не нужна.",
        "add_profile": "Добавить профиль",
        "applications_only": "TheeJ обновляется сам, только если запущен из папки «Программы».",
        "apply": "Применить",
        "audio_text": "Чтобы менять громкость приложения, TheeJ воспроизводит его звук на уровне ручки, а macOS считает это записью. Разрешите TheeJ в разделе «Запись экрана и системного аудио» в «Конфиденциальность и безопасность», затем завершите TheeJ и откройте его снова.",
        "audio_title": "TheeJ пока не может менять громкость приложений",
        "auto": "Проверять автоматически",
        "available": "Доступна версия TheeJ {version}",
        "baud_note": "Должна совпадать с Serial.begin() в скетче платы.",
        "baud_rate": "Скорость (бод)",
        "board.arrange": "Расставить рисунок",
        "board.button": "Кнопка {letter}",
        "board.down": "На ряд ниже",
        "board.empty": "У этой платы нет элементов управления.",
        "board.fader": "Фейдер {letter}",
        "board.hint": "Подвигайте или нажмите элемент на плате либо щёлкните его здесь, чтобы выбрать, что он делает.",
        "board.left": "Влево",
        "board.right": "Вправо",
        "board.up": "На ряд выше",
        "boards.add": "Добавить плату",
        "boards.none": "Плат пока нет.",
        "boards.none_connected": "Нет подключённых плат.",
        "boards.on": "{name}: вкл.",
        "boards.set_up": "Настроить платы",
        "boards.settings": "Настройки платы",
        "boards.settings_of": "Настройки: {name}",
        "boards.title": "Платы",
        "by": "Автор:",
        "calibrate": "Калибровать",
        "cancel": "Отменить",
        "check": "Проверить обновления…",
        "check_connection": "Проверьте подключение и повторите попытку.",
        "check_failed": "Не удалось проверить обновления",
        "checking_signature": "Проверка подписи…",
        "choose": "Выбрать",
        "choose_language": "Выберите язык",
        "clear": "Очистить",
        "click_to_update": "У вас {version}. Нажмите, чтобы обновить.",
        "close": "Закрыть",
        "connected": "Подключено: {port}",
        "continue": "Продолжить",
        "daily": "Ежедневно",
        "default_profile": "По умолчанию",
        "device.pick_input": "Выберите MIDI-вход",
        "device.remove": "Удалить плату",
        "device.remove_info": "Её профили и калибровка тоже будут удалены.",
        "device.type": "Тип",
        "device.type.diy": "Самодельная (Arduino)",
        "device.type.midi": "Другой MIDI",
        "device.type.smc": "SMC-Mixer",
        "device.used_by": "{port} (занят: {board})",
        "dock": "Оставить в Dock",
        "dock_restart": "Перезапустить Dock",
        "dock_restart_text": "Для этого macOS нужно перезапустить Dock. Экран и строка меню на мгновение мигнут.",
        "dock_restart_title": "Перезапустить Dock?",
        "download": "Скачать",
        "download_failed": "Не удалось загрузить.",
        "downloading": "Загрузка версии {version}…",
        "finish": "Готово",
        "general.app": "Приложение",
        "hide_icon": "Скрыть значок в строке меню",
        "hide_icon_note": "Откройте TheeJ ещё раз, чтобы вернуться сюда.",
        "icon": "Значок",
        "icon.app": "Значок приложения",
        "icon.dial": "Регулятор",
        "icon.mixer": "Микшер",
        "import_failed": "Не удалось прочитать этот файл.",
        "import_skipped": "Не импортировано: {items}",
        "inspired_by": "Вдохновлено:",
        "install_now": "Установить версию {version} сейчас",
        "installed": "Версия {version} установлена.",
        "installing": "Установка…",
        "job.brightness": "Яркость экрана {n}",
        "job.builtin_brightness": "Яркость встроенного дисплея",
        "job.builtin_contrast": "Контраст встроенного дисплея",
        "job.builtin_keyboard": "Подсветка встроенной клавиатуры",
        "job.contrast": "Контраст экрана {n}",
        "job.empty": "Пусто",
        "job.external_keyboard": "Подсветка внешней клавиатуры",
        "job.focused_app": "Активное приложение",
        "job.master": "Общая громкость",
        "job.microphone": "Громкость микрофона",
        "job.night_shift": "Теплота Night Shift",
        "job.nothing": "Ничего",
        "job.other_apps": "Остальные приложения",
        "job.system_sounds": "Звуки системы",
        "job.zoom": "Увеличение экрана",
        "knob": "Ручка {letter}",
        "knobs": "Ручки",
        "language": "Язык",
        "language_note": "Его можно изменить позже в настройках или в меню.",
        "later": "Позже",
        "lights": "Подсветка кнопок",
        "lights.ball": "Мяч",
        "lights.bars": "Столбики",
        "lights.blink": "Мигание",
        "lights.bounce": "Отскок",
        "lights.breathe": "Дыхание",
        "lights.chase": "Бегущий огонь",
        "lights.checker": "Шахматы",
        "lights.clock": "Двоичные часы",
        "lights.comet": "Комета",
        "lights.eq": "Эквалайзер",
        "lights.eq2": "Эквалайзер 2",
        "lights.eqgame": "Игровой эквалайзер",
        "lights.explode": "Взрыв",
        "lights.fill": "Заполнение",
        "lights.fire": "Огонь",
        "lights.heartbeat": "Сердцебиение",
        "lights.helix": "Спираль",
        "lights.matrix": "Матрица",
        "lights.off": "Выкл.",
        "lights.on": "Вкл.",
        "lights.orbit": "Орбита",
        "lights.rain": "Дождь",
        "lights.random": "Случайно",
        "lights.rise": "Подъём",
        "lights.snake": "Змейка",
        "lights.sparkle": "Мерцание",
        "lights.stars": "Звёзды",
        "lights.wave": "Волна",
        "lights.zigzag": "Зигзаг",
        "lights_note": "Нажатые кнопки и отключение звука по-прежнему подсвечиваются.",
        "list.buttons": "Кнопки",
        "list.faders": "Фейдеры",
        "list.none": "Нет",
        "login": "Запускать при входе",
        "m1ddc.note": "Для яркости и контраста внешних экранов",
        "m1ddc.installed": "Установлено",
        "m1ddc.missing": "Не установлено",
        "m1ddc.install": "Установить",
        "m1ddc.refresh": "Обновить",
        "m1ddc.support": "Поддержка:",
        "made_by": "Автор:",
        "menu.board": "{name}: {status}",
        "mixer.fader": "Фейдер {n}",
        "mixer.knob": "Ручка {n}",
        "mixer_port_note": "Выберите MIDI-микшер, чтобы использовать его вместе с платой.",
        "name": "Имя",
        "needs_calibration": "Нужна калибровка",
        "never": "Никогда",
        "newest": "TheeJ {version}: это самая новая доступная версия.",
        "next_profile": "Следующий профиль",
        "not_connected": "Не подключено",
        "not_signed": "Загрузка не подписана Zolfer Figueiredo.",
        "now_using": "Теперь вы используете TheeJ {version}, самую новую доступную версию.",
        "ok": "OK",
        "on_windows": "На Windows? Скачайте",
        "open_settings": "Открыть Системные настройки",
        "other": "Другое…",
        "port": "Устройство",
        "port_auto": "Автоматически",
        "port_busy": "{port} занят другим приложением",
        "port_forced": "Задан как {port} при запуске TheeJ.",
        "port_note": "В автоматическом режиме TheeJ сам находит плату.",
        "press_shortcut": "Нажмите сочетание",
        "previous_profile": "Предыдущий профиль",
        "profile": "Профиль",
        "profile.edit": "Изменить профиль…",
        "profile.export": "Экспорт…",
        "profile.export_failed": "Не удалось сохранить профиль.",
        "profile.import": "Импорт…",
        "profile_list": "Список профилей",
        "profile_n": "Профиль {n}",
        "quit": "Завершить TheeJ",
        "reconnect": "Переподключить",
        "record_shortcut": "Записать сочетание",
        "refresh": "Обновить",
        "remove": "Удалить",
        "remove_named": "Удалить «{name}»?",
        "remove_profile": "Удалить этот профиль",
        "remove_profile_info": "Его задачи ручек и сочетание клавиш удалятся вместе с ним.",
        "remove_shortcut": "Удалить сочетание клавиш",
        "remove_this_profile": "Удалить этот профиль?",
        "reopen": "Открыть снова",
        "reopen_failed": "Не удалось открыть снова: {error} Завершите приложение и откройте его сами.",
        "save": "Сохранить",
        "section.apps": "Приложения",
        "section.brightness": "Яркость",
        "section.contrast": "Контраст",
        "section.keyboard": "Подсветка клавиатуры",
        "section.night_shift": "Night Shift",
        "section.volume": "Громкость",
        "section.zoom": "Увеличение",
        "settings": "Настройки",
        "setup.board": "Плата {n} из {of}",
        "setup.note": "Посчитайте платы Arduino, SMC-Mixer и другие MIDI-контроллеры. Вы добавите их по одной.",
        "setup.title": "Сколько у вас плат?",
        "short.builtin": "Встроенная",
        "short.builtin_display": "Встроенный дисплей",
        "short.external": "Внешняя",
        "short.screen": "Экран {n}",
        "short.warmth": "Теплота",
        "shortcut": "Сочетание клавиш",
        "shortcut.also_used": "Также используется: {names}",
        "shortcut.clash": "Это сочетание уже есть у этой платы. Попробуйте другое.",
        "shortcut.taken": "Это сочетание занято другим приложением. Попробуйте другое.",
        "shortcut_tip": "Используйте ⌘ или ⌃ с клавишей. Delete стирает сочетание, Escape отменяет.",
        "show_data": "Показывать данные ниже",
        "show_name": "Показывать имя профиля",
        "skip": "Пропустить",
        "smc.bank_left": "Предыдущий банк",
        "smc.bank_right": "Следующий банк",
        "smc.down": "Вниз",
        "smc.hint": "Подвигайте или нажмите элемент на микшере либо щёлкните его здесь, чтобы выбрать, что он делает.",
        "smc.left": "Влево",
        "smc.record": "Запись",
        "smc.right": "Вправо",
        "smc.square": "Квадрат {n}",
        "smc.up": "Вверх",
        "space": "Пробел",
        "speed": "Скорость",
        "speed.fast": "Быстро",
        "speed.medium": "Средне",
        "speed.slow": "Медленно (рекомендуется)",
        "speed.superFast": "Очень быстро",
        "speed_note": "Когда срабатывает поворот.",
        "status": "Состояние",
        "status.connected": "Подключена",
        "status.disconnected": "Отключена",
        "status.off": "Выкл.",
        "tab.about": "О программе",
        "tab.boards": "Платы",
        "tab.general": "Основные",
        "tool_failed": "{tool}: сбой ({code}).",
        "up_to_date": "У вас последняя версия!",
        "update_available": "Доступно обновление!",
        "update_complete": "Обновление завершено!",
        "update_failed": "Не удалось установить обновление",
        "update_now": "Установить сейчас",
        "update_question": "У вас {version}. Обновить сейчас?",
        "updating_to": "Обновление TheeJ до {version}",
        "version": "Версия {version}",
        "view.draw": "Рисунок",
        "view.list": "Список",
        "website": "Сайт",
        "weekly": "Еженедельно",
        "wizard.count": "{n} из {of}",
        "wizard.done": "Все элементы найдены. Нажмите «Готово», чтобы сохранить.",
        "wizard.find": "Верните {name} на 0%.",
        "wizard.full": "Теперь поставьте все ручки и фейдеры на 100% и нажмите «Далее».",
        "wizard.mismatch": "Это была другая кнопка. Нажмите {name} три раза.",
        "wizard.nothing": "Между 0% и 100% ничего не сдвинулось.",
        "wizard.press": "Нажмите {name} три раза.",
        "wizard.redo": "Начать заново",
        "wizard.step": "{i} из {n}",
        "wizard.title": "Калибровка: {name}",
        "wizard.unswept": "Это не сдвигалось между 0% и 100%. Нажмите «Начать заново».",
        "wizard.waiting": "Ожидание подключения: {name}.",
        "wizard.wrong": "Это {other}. Переместите {name}.",
        "wizard.zero": "Поставьте все ручки и фейдеры на 0% и нажмите «Далее».",
        "wrong_download": "Загружен не TheeJ {version}.",
    ]
}
