// Українська. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let uk: [String: String] = [
        "about": "Про TheeJ",
        "action.close_app": "Закрити застосунок",
        "action.go_profile": "Перейти до профілю «{name}»",
        "action.group.apps": "Застосунки",
        "action.group.fkeys": "Функціональні клавіші",
        "action.group.knobs": "Ручки",
        "action.group.media": "Медіа",
        "action.group.system": "Система",
        "action.keys": "Натиснути сполучення клавіш",
        "action.lock": "Заблокувати Mac",
        "action.mute": "Вимкнути звук: {name}",
        "action.mute_all": "Вимкнути весь звук",
        "action.mute_mic": "Вимкнути мікрофон",
        "action.next_track": "Наступний трек",
        "action.night_light": "Night Shift увімк./вимк.",
        "action.open_app": "Відкрити застосунок",
        "action.open_settings": "Відкрити параметри",
        "action.open_url": "Відкрити сайт",
        "action.pause": "Пауза",
        "action.play": "Відтворити",
        "action.play_pause": "Відтворення/пауза",
        "action.previous_track": "Попередній трек",
        "action.screens_off": "Вимкнути екрани",
        "action.sleep": "Режим сну",
        "action.volume_down": "Тихіше",
        "action.volume_up": "Гучніше",
        "add.add": "Додати",
        "add.name_hint": "Стіл",
        "add.next": "Далі",
        "add.title": "Додати плату",
        "add.type_note.diy": "Arduino, що передає ручки через USB, як у deej.",
        "add.type_note.midi": "Будь-який інший MIDI-контролер. Ви показуєте TheeJ, який елемент який.",
        "add.type_note.smc": "M-VAVE SMC-Mixer. Його елементи вже відомі, калібрування не потрібне.",
        "add_profile": "Додати профіль",
        "applications_only": "TheeJ оновлюється сам, лише коли запущений із папки «Програми».",
        "apply": "Застосувати",
        "audio_text": "Щоб змінювати гучність застосунку, TheeJ відтворює його звук на рівні ручки, а macOS вважає це записом. Дозвольте TheeJ у розділі «Запис екрана й системного аудіо» в «Приватність і безпека», потім завершіть TheeJ і відкрийте його знову.",
        "audio_title": "TheeJ поки не може змінювати гучність застосунків",
        "auto": "Перевіряти автоматично",
        "available": "Доступна версія TheeJ {version}",
        "baud_note": "Має збігатися з Serial.begin() у скетчі плати.",
        "baud_rate": "Швидкість (бод)",
        "board.button": "Кнопка {letter}",
        "board.empty": "Ця плата не має елементів керування.",
        "board.fader": "Фейдер {letter}",
        "board.hint": "Порухайте або натисніть елемент на платі чи клацніть його тут, щоб вибрати, що він робить.",
        "boards.add": "Додати плату",
        "boards.none": "Плат ще немає.",
        "boards.none_connected": "Немає підключених плат.",
        "boards.on": "{name}: увімк.",
        "boards.set_up": "Налаштувати плати",
        "boards.settings": "Налаштування плати",
        "boards.settings_of": "Налаштування: {name}",
        "boards.title": "Плати",
        "by": "Автор:",
        "calibrate": "Калібрувати",
        "cancel": "Скасувати",
        "check": "Перевірити оновлення…",
        "check_connection": "Перевірте з’єднання та спробуйте ще раз.",
        "check_failed": "Не вдалося перевірити оновлення",
        "checking_signature": "Перевірка підпису…",
        "choose": "Вибрати",
        "choose_language": "Виберіть мову",
        "clear": "Очистити",
        "click_to_update": "У вас {version}. Натисніть, щоб оновити.",
        "close": "Закрити",
        "connected": "Під’єднано: {port}",
        "continue": "Продовжити",
        "daily": "Щодня",
        "default_profile": "Типовий",
        "device.pick_input": "Виберіть MIDI-вхід",
        "device.remove": "Видалити плату",
        "device.remove_info": "Її профілі та калібрування теж буде видалено.",
        "device.type": "Тип",
        "device.type.diy": "Саморобна (Arduino)",
        "device.type.midi": "Інший MIDI",
        "device.type.smc": "SMC-Mixer",
        "device.used_by": "{port} (зайнятий: {board})",
        "dock": "Залишити в Dock",
        "dock_restart": "Перезапустити Dock",
        "dock_restart_text": "Для цього macOS має перезапустити Dock. Екран і рядок меню на мить блимнуть.",
        "dock_restart_title": "Перезапустити Dock?",
        "download": "Завантажити",
        "download_failed": "Не вдалося завантажити.",
        "downloading": "Завантаження версії {version}…",
        "finish": "Готово",
        "general.app": "Застосунок",
        "hide_icon": "Сховати іконку в рядку меню",
        "hide_icon_note": "Відкрийте TheeJ ще раз, щоб повернутися сюди.",
        "icon": "Іконка",
        "icon.app": "Іконка застосунку",
        "icon.dial": "Регулятор",
        "icon.mixer": "Мікшер",
        "inspired_by": "Натхнено:",
        "install_now": "Встановити версію {version} зараз",
        "installed": "Версію {version} встановлено.",
        "installing": "Встановлення…",
        "job.brightness": "Яскравість екрана {n}",
        "job.builtin_brightness": "Яскравість вбудованого дисплея",
        "job.builtin_contrast": "Контраст вбудованого дисплея",
        "job.builtin_keyboard": "Підсвітка вбудованої клавіатури",
        "job.contrast": "Контраст екрана {n}",
        "job.empty": "Порожньо",
        "job.external_keyboard": "Підсвітка зовнішньої клавіатури",
        "job.master": "Загальна гучність",
        "job.microphone": "Гучність мікрофона",
        "job.night_shift": "Теплота Night Shift",
        "job.nothing": "Нічого",
        "job.zoom": "Збільшення екрана",
        "knob": "Ручка {letter}",
        "knobs": "Ручки",
        "language": "Мова",
        "language_note": "Її можна змінити пізніше в параметрах або в меню.",
        "later": "Пізніше",
        "list.buttons": "Кнопки",
        "list.faders": "Фейдери",
        "list.none": "Немає",
        "login": "Запускати під час входу",
        "m1ddc.note": "Для яскравості й контрасту зовнішніх екранів",
        "m1ddc.installed": "Встановлено",
        "m1ddc.missing": "Не встановлено",
        "m1ddc.install": "Встановити",
        "m1ddc.refresh": "Оновити",
        "m1ddc.support": "Підтримка:",
        "made_by": "Автор:",
        "menu.board": "{name}: {status}",
        "mixer.fader": "Фейдер {n}",
        "mixer.knob": "Ручка {n}",
        "mixer_port_note": "Виберіть MIDI-мікшер, щоб використовувати його разом із платою.",
        "name": "Назва",
        "needs_calibration": "Потрібне калібрування",
        "never": "Ніколи",
        "newest": "TheeJ {version}: це найновіша доступна версія.",
        "next_profile": "Наступний профіль",
        "not_connected": "Не під’єднано",
        "not_signed": "Завантаження не підписано Zolfer Figueiredo.",
        "now_using": "Тепер ви використовуєте TheeJ {version}, найновішу доступну версію.",
        "ok": "OK",
        "on_windows": "На Windows? Завантажте",
        "open_settings": "Відкрити Системні параметри",
        "other": "Інше…",
        "port": "Пристрій",
        "port_auto": "Автоматично",
        "port_busy": "{port} зайнятий іншим застосунком",
        "port_forced": "Задано як {port} під час запуску TheeJ.",
        "port_note": "В автоматичному режимі TheeJ сам знаходить плату.",
        "press_shortcut": "Натисніть клавіші",
        "previous_profile": "Попередній профіль",
        "profile": "Профіль",
        "profile.edit": "Змінити профіль…",
        "profile_list": "Список профілів",
        "profile_n": "Профіль {n}",
        "quit": "Завершити TheeJ",
        "reconnect": "Під’єднати знову",
        "record_shortcut": "Нове сполучення",
        "refresh": "Оновити",
        "remove": "Вилучити",
        "remove_named": "Вилучити «{name}»?",
        "remove_profile": "Вилучити цей профіль",
        "remove_profile_info": "Його завдання ручок і сполучення клавіш зникнуть разом із ним.",
        "remove_shortcut": "Вилучити сполучення клавіш",
        "remove_this_profile": "Вилучити цей профіль?",
        "reopen": "Відкрити знову",
        "reopen_failed": "Не вдалося відкрити знову: {error} Завершіть програму й відкрийте її самі.",
        "save": "Зберегти",
        "section.apps": "Застосунки",
        "section.brightness": "Яскравість",
        "section.contrast": "Контраст",
        "section.keyboard": "Підсвітка клавіатури",
        "section.night_shift": "Night Shift",
        "section.volume": "Гучність",
        "section.zoom": "Збільшення",
        "settings": "Параметри",
        "short.builtin": "Вбудована",
        "short.builtin_display": "Вбудований дисплей",
        "short.external": "Зовнішня",
        "short.screen": "Екран {n}",
        "short.warmth": "Теплота",
        "shortcut": "Сполучення клавіш",
        "shortcut.also_used": "Також використовує: {names}",
        "shortcut.clash": "Це сполучення вже є в цієї плати. Спробуйте інше.",
        "shortcut.taken": "Це сполучення зайняте іншою програмою. Спробуйте інше.",
        "shortcut_tip": "Використовуйте ⌘ або ⌃ з клавішею. Delete стирає сполучення, Escape скасовує.",
        "show_data": "Показувати дані нижче",
        "show_name": "Показувати назву профілю",
        "skip": "Пропустити",
        "smc.bank_left": "Попередній банк",
        "smc.bank_right": "Наступний банк",
        "smc.down": "Вниз",
        "smc.hint": "Порухайте або натисніть елемент на мікшері чи клацніть його тут, щоб вибрати, що він робить.",
        "smc.left": "Ліворуч",
        "smc.record": "Запис",
        "smc.right": "Праворуч",
        "smc.square": "Квадрат {n}",
        "smc.up": "Вгору",
        "space": "Пробіл",
        "speed": "Швидкість",
        "speed.fast": "Швидко",
        "speed.medium": "Середньо",
        "speed.slow": "Повільно (рекомендовано)",
        "speed.superFast": "Дуже швидко",
        "speed_note": "Коли спрацьовує поворот.",
        "status": "Стан",
        "status.connected": "Підключена",
        "status.disconnected": "Відключена",
        "status.off": "Вимк.",
        "tab.about": "Про застосунок",
        "tab.boards": "Плати",
        "tab.general": "Загальні",
        "tool_failed": "{tool}: збій ({code}).",
        "up_to_date": "У вас найновіша версія!",
        "update_available": "Доступне оновлення!",
        "update_complete": "Оновлення завершено!",
        "update_failed": "Не вдалося встановити оновлення",
        "update_now": "Встановити зараз",
        "update_question": "У вас {version}. Оновити зараз?",
        "updating_to": "Оновлення TheeJ до {version}",
        "version": "Версія {version}",
        "view.draw": "Малюнок",
        "view.list": "Список",
        "website": "Сайт",
        "weekly": "Щотижня",
        "wizard.count": "{n} з {of}",
        "wizard.done": "Усі елементи знайдено. Натисніть «Готово», щоб зберегти.",
        "wizard.find": "Поверніть {name} на 0%.",
        "wizard.full": "Тепер поставте всі ручки й фейдери на 100% і натисніть «Далі».",
        "wizard.mismatch": "Це була інша кнопка. Натисніть {name} тричі.",
        "wizard.nothing": "Між 0% і 100% нічого не зрушило.",
        "wizard.press": "Натисніть {name} тричі.",
        "wizard.redo": "Почати знову",
        "wizard.step": "{i} з {n}",
        "wizard.title": "Калібрування: {name}",
        "wizard.unswept": "Це не зрушувалося між 0% і 100%. Натисніть «Почати знову».",
        "wizard.waiting": "Очікування підключення: {name}.",
        "wizard.wrong": "Це {other}. Перемістіть {name}.",
        "wizard.zero": "Поставте всі ручки й фейдери на 0% і натисніть «Далі».",
        "wrong_download": "Завантажено не TheeJ {version}.",
    ]
}
