// Українська. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let uk: [String: String] = [
        "about": "Про TheeJ",
        "add_knob": "Додати ручку",
        "add_profile": "Додати профіль",
        "applications_only": "TheeJ оновлюється сам, лише коли запущений із папки «Програми».",
        "audio_text": "Щоб змінювати гучність застосунку, TheeJ відтворює його звук на рівні ручки, а macOS вважає це записом. Дозвольте TheeJ у розділі «Запис екрана й системного аудіо» в «Приватність і безпека», потім завершіть TheeJ і відкрийте його знову.",
        "audio_title": "TheeJ поки не може змінювати гучність застосунків",
        "auto": "Перевіряти автоматично",
        "available": "Доступна версія TheeJ {version}",
        "by": "Автор:",
        "cal.all_found": "Усі ручки знайдено",
        "cal.all_found_text": "Плата передає значень: {n}. Кожне тепер має свою ручку, тож це всі. Натисніть «Готово», щоб вибрати, що вони роблять.",
        "cal.finish_later": "«Готово» зупиниться тут і залишить її на потім.",
        "cal.hold": "Ручки нічого не змінюють, доки ви не закінчите.",
        "cal.move": "Прокрутіть ручку {letter} від краю до краю.",
        "cal.move_first": "Прокрутіть ручку {letter} від краю до краю, щоб TheeJ зрозумів, яка ручка де. Потім кожну ручку треба крутити {n} секунд: це прочищає смикану ручку.",
        "cal.no_knob": "Якщо ручки {letter} у вас немає, натисніть «Готово».",
        "cal.paused": "Пауза. {left}. Продовжуйте крутити ручку {letter}.",
        "cal.skip_keeps": "Її вже налаштовано, тож «Пропустити» залишить її як є.",
        "cal.turn": "Знайшлася. Тепер крутіть її туди й назад, від краю до краю, {n} секунд. Час іде, лише поки вона обертається. Пропустіть, якщо чищення не потрібне.",
        "cal.waiting_board": "Чекаю на під’єднання плати",
        "cal.waiting_knob": "Чекаю на рух ручки {letter}",
        "cal.wrong": "Це ручка {wrong}. Поверніть ручку {letter}.",
        "calibrate": "Калібрувати",
        "calibration_title": "Калібрування TheeJ",
        "cancel": "Скасувати",
        "check": "Перевірити оновлення…",
        "check_connection": "Перевірте з’єднання та спробуйте ще раз.",
        "check_failed": "Не вдалося перевірити оновлення",
        "checking_signature": "Перевірка підпису…",
        "choose": "Вибрати",
        "choose_language": "Виберіть мову",
        "clear": "Очистити",
        "click_to_update": "У вас {version}. Натисніть, щоб оновити.",
        "close": "Закрити",
        "connected": "Під’єднано: {port}",
        "continue": "Продовжити",
        "daily": "Щодня",
        "default_profile": "Типовий",
        "dock": "Залишити в Dock",
        "dock_restart": "Перезапустити Dock",
        "dock_restart_text": "Для цього macOS має перезапустити Dock. Екран і рядок меню на мить блимнуть.",
        "dock_restart_title": "Перезапустити Dock?",
        "download": "Завантажити",
        "download_failed": "Не вдалося завантажити.",
        "downloading": "Завантаження версії {version}…",
        "finish": "Готово",
        "hide_icon": "Сховати іконку в рядку меню",
        "hide_icon_note": "Відкрийте TheeJ ще раз, щоб повернутися сюди.",
        "icon": "Іконка",
        "icon.app": "Іконка застосунку",
        "icon.dial": "Регулятор",
        "icon.mixer": "Мікшер",
        "inspired_by": "Натхнено:",
        "install_now": "Встановити версію {version} зараз",
        "installed": "Версію {version} встановлено.",
        "installing": "Встановлення…",
        "invert": "Інвертувати ручки",
        "invert_note": "Для потенціометрів, під’єднаних навпаки.",
        "job.brightness": "Яскравість екрана {n}",
        "job.builtin_brightness": "Яскравість вбудованого дисплея",
        "job.builtin_contrast": "Контраст вбудованого дисплея",
        "job.builtin_keyboard": "Підсвітка вбудованої клавіатури",
        "job.contrast": "Контраст екрана {n}",
        "job.external_keyboard": "Підсвітка зовнішньої клавіатури",
        "job.master": "Загальна гучність",
        "job.microphone": "Гучність мікрофона",
        "job.night_shift": "Теплота Night Shift",
        "job.nothing": "Нічого",
        "job.zoom": "Збільшення екрана",
        "jobs_note": "Позначте завдання кожної ручки в цьому профілі.",
        "knob": "Ручка {letter}",
        "knobs": "Ручки",
        "knobs_found.few": "Знайдено {n} ручки",
        "knobs_found.many": "Знайдено {n} ручок",
        "knobs_found.one": "Знайдено {n} ручку",
        "knobs_found.other": "Знайдено {n} ручок",
        "language": "Мова",
        "language_note": "Її можна змінити пізніше в параметрах або в меню.",
        "later": "Пізніше",
        "login": "Запускати під час входу",
        "m1ddc.note": "Для яскравості й контрасту зовнішніх екранів",
        "m1ddc.installed": "Встановлено",
        "m1ddc.missing": "Не встановлено",
        "m1ddc.install": "Встановити",
        "m1ddc.refresh": "Оновити",
        "m1ddc.support": "Підтримка:",
        "made_by": "Автор:",
        "menu_bar": "Рядок меню",
        "name": "Назва",
        "needs_calibration": "Потрібне калібрування",
        "never": "Ніколи",
        "newest": "TheeJ {version}: це найновіша доступна версія.",
        "next_profile": "Наступний профіль",
        "no_knobs": "Ручок немає. «Калібрувати» знайде їх, або натисніть +, щоб додати одну.",
        "not_connected": "Не під’єднано",
        "not_signed": "Завантаження не підписано Zolfer Figueiredo.",
        "now_using": "Тепер ви використовуєте TheeJ {version}, найновішу доступну версію.",
        "ok": "OK",
        "open_settings": "Відкрити Системні параметри",
        "other": "Інше…",
        "press_shortcut": "Натисніть клавіші",
        "previous_profile": "Попередній профіль",
        "profile": "Профіль",
        "profile_list": "Список профілів",
        "profile_n": "Профіль {n}",
        "profiles": "Профілі",
        "quit": "Завершити TheeJ",
        "reconnect": "Під’єднати знову",
        "record_shortcut": "Нове сполучення",
        "remove": "Вилучити",
        "remove_knob": "Вилучити останню ручку",
        "remove_knob_info": "Її завдання в усіх профілях зникнуть разом із нею.",
        "remove_knob_q": "Вилучити ручку {letter}?",
        "remove_named": "Вилучити «{name}»?",
        "remove_profile": "Вилучити цей профіль",
        "remove_profile_info": "Його завдання ручок і сполучення клавіш зникнуть разом із ним.",
        "remove_shortcut": "Вилучити сполучення клавіш",
        "remove_this_profile": "Вилучити цей профіль?",
        "reopen": "Відкрити знову",
        "reopen_failed": "Не вдалося відкрити знову: {error} Завершіть програму й відкрийте її самі.",
        "save": "Зберегти",
        "seconds_left.few": "Залишилося {n} секунди",
        "seconds_left.many": "Залишилося {n} секунд",
        "seconds_left.one": "Залишилася {n} секунда",
        "seconds_left.other": "Залишилося {n} секунд",
        "section.apps": "Застосунки",
        "section.brightness": "Яскравість",
        "section.contrast": "Контраст",
        "section.keyboard": "Підсвітка клавіатури",
        "section.night_shift": "Night Shift",
        "section.volume": "Гучність",
        "section.zoom": "Збільшення",
        "sensitivity": "Чутливість",
        "settings": "Параметри",
        "short.builtin": "Вбудована",
        "short.builtin_display": "Вбудований дисплей",
        "short.external": "Зовнішня",
        "short.screen": "Екран {n}",
        "short.warmth": "Теплота",
        "shortcut": "Сполучення клавіш",
        "shortcut_tip": "Використовуйте ⌘ або ⌃ з клавішею. Delete стирає сполучення, Escape скасовує.",
        "shortcuts": "Сполучення клавіш",
        "show_data": "Показувати дані нижче",
        "show_name": "Показувати назву профілю",
        "skip": "Пропустити",
        "space": "Пробіл",
        "speed": "Швидкість",
        "speed.fast": "Швидко",
        "speed.medium": "Середньо",
        "speed.slow": "Повільно (рекомендовано)",
        "speed.superFast": "Дуже швидко",
        "speed_note": "Коли спрацьовує поворот.",
        "tab.about": "Про застосунок",
        "tab.app": "Параметри застосунку",
        "tab.general": "Загальні",
        "tool_failed": "{tool}: збій ({code}).",
        "up_to_date": "У вас найновіша версія!",
        "update_available": "Доступне оновлення!",
        "update_complete": "Оновлення завершено!",
        "update_failed": "Не вдалося встановити оновлення",
        "update_now": "Встановити зараз",
        "update_question": "У вас {version}. Оновити зараз?",
        "updating_to": "Оновлення TheeJ до {version}",
        "version": "Версія {version}",
        "website": "Сайт",
        "weekly": "Щотижня",
        "wrong_download": "Завантажено не TheeJ {version}.",
    ]
}
