// 中文. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let zh: [String: String] = [
        "about": "关于 TheeJ",
        "add_knob": "添加旋钮",
        "add_profile": "添加配置方案",
        "applications_only": "TheeJ 仅在从“应用程序”文件夹运行时才会自行更新。",
        "apply": "应用",
        "audio_text": "要调节某个应用的音量，TheeJ 会按旋钮的音量重新播放该应用的声音，macOS 将此视为录音。请在“隐私与安全性”的“录屏与系统录音”中允许 TheeJ，然后退出 TheeJ 并重新打开。",
        "audio_title": "TheeJ 还不能调节应用音量",
        "auto": "自动检查",
        "available": "TheeJ {version} 已可用",
        "by": "作者:",
        "cal.all_found": "已找到所有旋钮",
        "cal.all_found_text": "你的板子发送 {n} 个数值，每个都已对应一个旋钮，所以全部找到了。点“完成”来选择它们的功能。",
        "cal.finish_later": "点“完成”会停在这里，把它留到以后。",
        "cal.hold": "完成之前，旋钮不会起作用。",
        "cal.move": "把旋钮 {letter} 从一端转到另一端。",
        "cal.move_first": "把旋钮 {letter} 从一端转到另一端，这样 TheeJ 才能分清每个旋钮。之后每个旋钮要转动 {n} 秒，可以把跳动的旋钮转干净。",
        "cal.no_knob": "如果没有旋钮 {letter}，请点“完成”。",
        "cal.paused": "已暂停，{left}。请继续转动旋钮 {letter}。",
        "cal.skip_keeps": "它已经设置好了，点“跳过”会保持原样。",
        "cal.turn": "找到了。现在把它从一端到另一端来回转动 {n} 秒。只有转动时才会计时。如果不需要清洁，可以跳过。",
        "cal.waiting_board": "正在等待板子连接",
        "cal.waiting_knob": "正在等待旋钮 {letter} 转动",
        "cal.wrong": "那是旋钮 {wrong}。请转动旋钮 {letter}。",
        "calibrate": "校准",
        "calibration_title": "TheeJ 校准",
        "cancel": "取消",
        "check": "检查更新…",
        "check_connection": "请检查网络连接后重试。",
        "check_failed": "无法检查更新",
        "checking_signature": "正在检查签名…",
        "choose": "选取",
        "choose_language": "选择语言",
        "clear": "清除",
        "click_to_update": "当前版本为 {version}。点按即可更新。",
        "close": "关闭",
        "connected": "已连接：{port}",
        "continue": "继续",
        "daily": "每天",
        "default_profile": "默认",
        "dock": "保留在 Dock 中",
        "dock_restart": "重新启动程序坞",
        "dock_restart_text": "要更改此设置，macOS 需要重新启动程序坞。屏幕和菜单栏会闪烁一下。",
        "dock_restart_title": "重新启动程序坞？",
        "download": "下载",
        "download_failed": "下载失败。",
        "downloading": "正在下载版本 {version}…",
        "finish": "完成",
        "hide_icon": "隐藏菜单栏图标",
        "hide_icon_note": "再次打开 TheeJ 即可回到这里。",
        "icon": "图标",
        "icon.app": "应用图标",
        "icon.dial": "旋钮",
        "icon.mixer": "调音台",
        "inspired_by": "灵感来自",
        "install_now": "立即安装版本 {version}",
        "installed": "版本 {version} 已安装。",
        "installing": "正在安装…",
        "invert": "反转旋钮",
        "invert_note": "适用于接线相反的电位器。",
        "job.brightness": "屏幕 {n} 亮度",
        "job.builtin_brightness": "内建显示器亮度",
        "job.builtin_contrast": "内建显示器对比度",
        "job.builtin_keyboard": "内建键盘背光",
        "job.contrast": "屏幕 {n} 对比度",
        "job.external_keyboard": "外接键盘背光",
        "job.master": "主音量",
        "job.microphone": "麦克风音量",
        "job.night_shift": "Night Shift 色温",
        "job.nothing": "无",
        "job.zoom": "屏幕缩放",
        "jobs_note": "为此配置方案中的每个旋钮勾选一项或多项功能。",
        "knob": "旋钮 {letter}",
        "knobs": "旋钮",
        "knobs_found.other": "已找到 {n} 个旋钮",
        "language": "语言",
        "language_note": "以后可以在设置或菜单中更改。",
        "later": "稍后",
        "login": "登录时启动",
        "m1ddc.note": "用于外部屏幕的亮度和对比度",
        "m1ddc.installed": "已安装",
        "m1ddc.missing": "未安装",
        "m1ddc.install": "安装",
        "m1ddc.refresh": "刷新",
        "m1ddc.support": "支持:",
        "made_by": "作者:",
        "menu_bar": "菜单栏",
        "name": "名称",
        "needs_calibration": "需要校准",
        "never": "从不",
        "newest": "TheeJ {version} 是目前最新的版本。",
        "next_profile": "下一个配置方案",
        "no_knobs": "没有旋钮。“校准”会找到它们，或按 + 添加一个。",
        "not_connected": "未连接",
        "not_signed": "下载的文件不是由 Zolfer Figueiredo 签名的。",
        "now_using": "你现在使用的是 TheeJ {version}，这是目前最新的版本。",
        "ok": "好",
        "on_windows": "Windows 版本:",
        "open_settings": "打开系统设置",
        "other": "其他…",
        "press_shortcut": "按下快捷键",
        "previous_profile": "上一个配置方案",
        "profile": "配置方案",
        "profile_list": "配置方案列表",
        "profile_n": "配置方案 {n}",
        "profiles": "配置方案",
        "quit": "退出 TheeJ",
        "reconnect": "重新连接",
        "record_shortcut": "录制快捷键",
        "remove": "移除",
        "remove_knob": "移除最后一个旋钮",
        "remove_knob_info": "它在所有配置方案中的功能会一并移除。",
        "remove_knob_q": "移除旋钮 {letter}？",
        "remove_named": "移除“{name}”？",
        "remove_profile": "移除此配置方案",
        "remove_profile_info": "它的旋钮功能和快捷键会一并移除。",
        "remove_shortcut": "移除快捷键",
        "remove_this_profile": "移除此配置方案？",
        "reopen": "重新打开",
        "reopen_failed": "无法重新打开：{error} 请退出应用后自行打开。",
        "seconds_left.other": "还剩 {n} 秒",
        "section.apps": "应用",
        "section.brightness": "亮度",
        "section.contrast": "对比度",
        "section.keyboard": "键盘背光",
        "section.night_shift": "Night Shift",
        "section.volume": "音量",
        "section.zoom": "缩放",
        "sensitivity": "灵敏度",
        "settings": "设置",
        "short.builtin": "内建",
        "short.builtin_display": "内建显示器",
        "short.external": "外接",
        "short.screen": "屏幕 {n}",
        "short.warmth": "色温",
        "shortcut": "快捷键",
        "shortcut_tip": "请将 ⌘ 或 ⌃ 与一个按键组合使用。Delete 清除，Escape 取消。",
        "shortcuts": "快捷键",
        "show_data": "在下方显示数据",
        "show_name": "显示配置方案名称",
        "skip": "跳过",
        "space": "空格",
        "speed": "速度",
        "speed.fast": "快",
        "speed.medium": "中",
        "speed.slow": "慢（推荐）",
        "speed.superFast": "超快",
        "speed_note": "转动后更改多久生效。",
        "tab.about": "关于",
        "tab.app": "应用设置",
        "tab.general": "通用",
        "tool_failed": "{tool} 失败（{code}）。",
        "up_to_date": "已是最新版本！",
        "update_available": "有可用更新！",
        "update_complete": "更新完成！",
        "update_failed": "无法安装更新",
        "update_now": "立即更新",
        "update_question": "当前版本为 {version}。现在更新吗？",
        "updating_to": "正在将 TheeJ 更新到 {version}",
        "version": "版本 {version}",
        "website": "网站",
        "weekly": "每周",
        "wrong_download": "下载的文件不是 TheeJ {version}。",
    ]
}
