// 中文. The menu tail, About and update strings are the ones ClaudioStat uses.
extension Strings {
    static let zh: [String: String] = [
        "about": "关于 TheeJ",
        "action.close_app": "关闭应用",
        "action.go_profile": "切换到 {name}",
        "action.group.apps": "应用",
        "action.group.fkeys": "功能键",
        "action.group.knobs": "旋钮",
        "action.group.media": "媒体",
        "action.group.system": "系统",
        "action.keys": "按下快捷键",
        "action.lights_off": "关闭按钮灯光",
        "action.lights_on": "打开按钮灯光",
        "action.lock": "锁定 Mac",
        "action.mute": "静音{name}",
        "action.mute_all": "全部静音",
        "action.mute_mic": "麦克风静音",
        "action.next_lights": "下一种按钮灯光",
        "action.next_track": "下一曲",
        "action.night_light": "Night Shift开/关",
        "action.open_app": "打开应用",
        "action.open_settings": "打开设置",
        "action.open_url": "打开网站",
        "action.pause": "暂停",
        "action.play": "播放",
        "action.play_pause": "播放/暂停",
        "action.previous_lights": "上一种按钮灯光",
        "action.previous_track": "上一曲",
        "action.screens_off": "关闭屏幕",
        "action.sleep": "睡眠",
        "action.volume_down": "调低音量",
        "action.volume_up": "调高音量",
        "add.add": "添加",
        "add.name_hint": "书桌",
        "add.next": "下一步",
        "add.title": "添加设备板",
        "add.type_note.diy": "像 deej 那样通过 USB 发送旋钮数值的 Arduino。",
        "add.type_note.midi": "其他任何 MIDI 控制器。你告诉 TheeJ 哪个控件是哪个。",
        "add.type_note.smc": "M-VAVE SMC-Mixer。它的控件是已知的，因此无需校准。",
        "add_profile": "添加配置方案",
        "applications_only": "TheeJ 仅在从“应用程序”文件夹运行时才会自行更新。",
        "apply": "应用",
        "audio_text": "要调节某个应用的音量，TheeJ 会按旋钮的音量重新播放该应用的声音，macOS 将此视为录音。请在“隐私与安全性”的“录屏与系统录音”中允许 TheeJ，然后退出 TheeJ 并重新打开。",
        "audio_title": "TheeJ 还不能调节应用音量",
        "auto": "自动检查",
        "available": "TheeJ {version} 已可用",
        "baud_note": "必须与开发板程序中的 Serial.begin() 一致。",
        "baud_rate": "波特率",
        "board.button": "按钮 {letter}",
        "board.empty": "此设备板没有控件。",
        "board.fader": "推子 {letter}",
        "board.hint": "在设备板上移动或按下控件，或在这里点击它，即可选择它的功能。",
        "boards.add": "添加设备板",
        "boards.none": "还没有设备板。",
        "boards.none_connected": "没有已连接的设备板。",
        "boards.on": "{name} 开",
        "boards.set_up": "设置设备板",
        "boards.settings": "设备板设置",
        "boards.settings_of": "{name} 设置",
        "boards.title": "设备板",
        "by": "作者:",
        "calibrate": "校准",
        "cancel": "取消",
        "check": "检查更新…",
        "check_connection": "请检查网络连接后重试。",
        "check_failed": "无法检查更新",
        "checking_signature": "正在检查签名…",
        "choose": "选取",
        "choose_language": "选择语言",
        "clear": "清除",
        "click_to_update": "当前版本为 {version}。点按即可更新。",
        "close": "关闭",
        "connected": "已连接：{port}",
        "continue": "继续",
        "daily": "每天",
        "default_profile": "默认",
        "device.pick_input": "选择 MIDI 输入",
        "device.remove": "移除设备板",
        "device.remove_info": "它的配置文件和校准也会一起移除。",
        "device.type": "类型",
        "device.type.diy": "自制 (Arduino)",
        "device.type.midi": "其他 MIDI",
        "device.type.smc": "SMC-Mixer",
        "device.used_by": "{port}（{board} 正在使用）",
        "dock": "保留在 Dock 中",
        "dock_restart": "重新启动程序坞",
        "dock_restart_text": "要更改此设置，macOS 需要重新启动程序坞。屏幕和菜单栏会闪烁一下。",
        "dock_restart_title": "重新启动程序坞？",
        "download": "下载",
        "download_failed": "下载失败。",
        "downloading": "正在下载版本 {version}…",
        "finish": "完成",
        "general.app": "应用",
        "hide_icon": "隐藏菜单栏图标",
        "hide_icon_note": "再次打开 TheeJ 即可回到这里。",
        "icon": "图标",
        "icon.app": "应用图标",
        "icon.dial": "旋钮",
        "icon.mixer": "调音台",
        "inspired_by": "灵感来自",
        "install_now": "立即安装版本 {version}",
        "installed": "版本 {version} 已安装。",
        "installing": "正在安装…",
        "job.brightness": "屏幕 {n} 亮度",
        "job.builtin_brightness": "内建显示器亮度",
        "job.builtin_contrast": "内建显示器对比度",
        "job.builtin_keyboard": "内建键盘背光",
        "job.contrast": "屏幕 {n} 对比度",
        "job.empty": "空",
        "job.external_keyboard": "外接键盘背光",
        "job.master": "主音量",
        "job.microphone": "麦克风音量",
        "job.night_shift": "Night Shift 色温",
        "job.nothing": "无",
        "job.zoom": "屏幕缩放",
        "knob": "旋钮 {letter}",
        "knobs": "旋钮",
        "language": "语言",
        "language_note": "以后可以在设置或菜单中更改。",
        "later": "稍后",
        "lights": "按钮灯光",
        "lights.ball": "弹球",
        "lights.bars": "柱状",
        "lights.blink": "闪烁",
        "lights.bounce": "弹跳",
        "lights.breathe": "呼吸",
        "lights.chase": "追逐",
        "lights.checker": "棋盘",
        "lights.clock": "二进制时钟",
        "lights.comet": "彗星",
        "lights.eq": "均衡器",
        "lights.eq2": "均衡器 2",
        "lights.eqgame": "游戏均衡器",
        "lights.explode": "爆炸",
        "lights.fill": "填充",
        "lights.fire": "火焰",
        "lights.heartbeat": "心跳",
        "lights.helix": "螺旋",
        "lights.matrix": "矩阵",
        "lights.off": "关",
        "lights.on": "开",
        "lights.orbit": "环绕",
        "lights.rain": "雨滴",
        "lights.random": "随机",
        "lights.rise": "上升",
        "lights.snake": "贪吃蛇",
        "lights.sparkle": "闪耀",
        "lights.stars": "星星",
        "lights.wave": "波浪",
        "lights.zigzag": "之字形",
        "lights_note": "按下的按钮和静音仍会亮起。",
        "list.buttons": "按钮",
        "list.faders": "推子",
        "list.none": "无",
        "login": "登录时启动",
        "m1ddc.note": "用于外部屏幕的亮度和对比度",
        "m1ddc.installed": "已安装",
        "m1ddc.missing": "未安装",
        "m1ddc.install": "安装",
        "m1ddc.refresh": "刷新",
        "m1ddc.support": "支持:",
        "made_by": "作者:",
        "menu.board": "{name}：{status}",
        "mixer.fader": "推子 {n}",
        "mixer.knob": "旋钮 {n}",
        "mixer_port_note": "选择你的 MIDI 调音台，即可与板子一起使用。",
        "name": "名称",
        "needs_calibration": "需要校准",
        "never": "从不",
        "newest": "TheeJ {version} 是目前最新的版本。",
        "next_profile": "下一个配置方案",
        "not_connected": "未连接",
        "not_signed": "下载的文件不是由 Zolfer Figueiredo 签名的。",
        "now_using": "你现在使用的是 TheeJ {version}，这是目前最新的版本。",
        "ok": "好",
        "on_windows": "Windows 版本:",
        "open_settings": "打开系统设置",
        "other": "其他…",
        "port": "设备",
        "port_auto": "自动",
        "port_busy": "{port} 正被另一个应用占用",
        "port_forced": "TheeJ 启动时已指定为 {port}。",
        "port_note": "自动模式下，TheeJ 会自行找到你的开发板。",
        "press_shortcut": "按下快捷键",
        "previous_profile": "上一个配置方案",
        "profile": "配置方案",
        "profile.edit": "编辑配置方案…",
        "profile_list": "配置方案列表",
        "profile_n": "配置方案 {n}",
        "quit": "退出 TheeJ",
        "reconnect": "重新连接",
        "record_shortcut": "录制快捷键",
        "refresh": "刷新",
        "remove": "移除",
        "remove_named": "移除“{name}”？",
        "remove_profile": "移除此配置方案",
        "remove_profile_info": "它的旋钮功能和快捷键会一并移除。",
        "remove_shortcut": "移除快捷键",
        "remove_this_profile": "移除此配置方案？",
        "reopen": "重新打开",
        "reopen_failed": "无法重新打开：{error} 请退出应用后自行打开。",
        "save": "保存",
        "section.apps": "应用",
        "section.brightness": "亮度",
        "section.contrast": "对比度",
        "section.keyboard": "键盘背光",
        "section.night_shift": "Night Shift",
        "section.volume": "音量",
        "section.zoom": "缩放",
        "settings": "设置",
        "short.builtin": "内建",
        "short.builtin_display": "内建显示器",
        "short.external": "外接",
        "short.screen": "屏幕 {n}",
        "short.warmth": "色温",
        "shortcut": "快捷键",
        "shortcut.also_used": "{names} 也在使用",
        "shortcut.clash": "此设备板已在使用该快捷键。请换一个。",
        "shortcut.taken": "其他应用已占用该快捷键。请换一个。",
        "shortcut_tip": "请将 ⌘ 或 ⌃ 与一个按键组合使用。Delete 清除，Escape 取消。",
        "show_data": "在下方显示数据",
        "show_name": "显示配置方案名称",
        "skip": "跳过",
        "smc.bank_left": "上一组",
        "smc.bank_right": "下一组",
        "smc.down": "下",
        "smc.hint": "在调音台上移动或按下控件，或在这里点击它，即可选择它的功能。",
        "smc.left": "左",
        "smc.record": "录音",
        "smc.right": "右",
        "smc.square": "方块 {n}",
        "smc.up": "上",
        "space": "空格",
        "speed": "速度",
        "speed.fast": "快",
        "speed.medium": "中",
        "speed.slow": "慢（推荐）",
        "speed.superFast": "超快",
        "speed_note": "转动后更改多久生效。",
        "status": "状态",
        "status.connected": "已连接",
        "status.disconnected": "未连接",
        "status.off": "关",
        "tab.about": "关于",
        "tab.boards": "设备板",
        "tab.general": "通用",
        "tool_failed": "{tool} 失败（{code}）。",
        "up_to_date": "已是最新版本！",
        "update_available": "有可用更新！",
        "update_complete": "更新完成！",
        "update_failed": "无法安装更新",
        "update_now": "立即更新",
        "update_question": "当前版本为 {version}。现在更新吗？",
        "updating_to": "正在将 TheeJ 更新到 {version}",
        "version": "版本 {version}",
        "view.draw": "图示",
        "view.list": "列表",
        "website": "网站",
        "weekly": "每周",
        "wizard.count": "{n}/{of}",
        "wizard.done": "所有控件都已找到。按“完成”保留它们。",
        "wizard.find": "把 {name} 调回 0%。",
        "wizard.full": "现在把每个旋钮和推子都调到 100%，然后点“下一步”。",
        "wizard.mismatch": "那是另一个按钮。请按 {name} 三次。",
        "wizard.nothing": "在 0% 和 100% 之间没有任何东西移动。",
        "wizard.press": "按 {name} 三次。",
        "wizard.redo": "重新开始",
        "wizard.step": "{i}/{n}",
        "wizard.title": "校准 {name}",
        "wizard.unswept": "它在 0% 和 100% 之间没有移动。请点“重新开始”。",
        "wizard.waiting": "正在等待 {name} 连接。",
        "wizard.wrong": "那是 {other}。请移动 {name}。",
        "wizard.zero": "把每个旋钮和推子都调到 0%，然后点“下一步”。",
        "wrong_download": "下载的文件不是 TheeJ {version}。",
    ]
}
